import type { EmbedEventDef } from "./embedTypes";
import {
  ShoppingCart, Timer, Star, Gift,
  Trophy, Trash2,
  Ban,
  QrCode,
  ShieldOff, ShieldAlert,
  LogOut, Pencil, Volume2, VolumeX, ArrowRightLeft,
  LogIn, Hash, Shield, Moon, Zap, AlertTriangle,
  Heart, HelpCircle,
  CheckCircle, Package, ClipboardList, Tag, UserPlus, Pin, UserMinus,
  ShieldCheck, Archive, RotateCcw, Users,
} from "lucide-react";

// ─── Event definitions ───────────────────────────────────────────────────────

export const EMBED_EVENTS: EmbedEventDef[] = [
  // ── Đơn hàng ──
  { key: "don_hang_moi",      label: "Đơn hàng mới",           labelEn: "New Order",           icon: ShoppingCart, desc: "Khi admin tạo đơn /tao_don" },
  { key: "qr_thanh_toan",     label: "QR Thanh toán",          labelEn: "Payment QR",          icon: QrCode,       desc: "Gửi ảnh QR PayOS cho khách" },
  { key: "qr_thanh_toan_payos",  label: "QR Thanh toán — PayOS",   labelEn: "Payment — PayOS",    icon: QrCode, desc: "PayOS-specific payment embed" },
  { key: "qr_thanh_toan_paypal", label: "QR Thanh toán — PayPal",  labelEn: "Payment — PayPal",   icon: QrCode, desc: "PayPal-specific payment embed" },
  { key: "qr_thanh_toan_crypto", label: "QR Thanh toán — Crypto",  labelEn: "Payment — Crypto",   icon: QrCode, desc: "Crypto-specific payment embed" },
  { key: "qr_thanh_toan_manual", label: "QR Thanh toán — Manual",  labelEn: "Payment — Manual",   icon: QrCode, desc: "Manual bank transfer payment embed" },
  { key: "don_hang_het_han",  label: "Đơn hàng hết hạn",      labelEn: "Expired Order",       icon: Timer,        desc: "Khi đơn quá 15 phút chưa thanh toán" },
  { key: "ghi_chu_don_hang",  label: "Ghi chú đơn hàng",      labelEn: "Order Note",          icon: ShoppingCart, desc: "Khi admin thêm ghi chú vào đơn hàng" },
  { key: "bang_gia",          label: "Bảng giá sản phẩm",     labelEn: "Price List",          icon: ShoppingCart, desc: "Embed tổng quan khi dùng /bang_gia hoặc /san_pham" },
  { key: "san_pham_detail",   label: "Chi tiết sản phẩm",      labelEn: "Product Detail",      icon: ShoppingCart, desc: "Embed chi tiết gói giá khi chọn sản phẩm (/san_pham)" },
  { key: "bxh_chi_tieu",      label: "BXH Chi tiêu",           labelEn: "Spending Leaderboard", icon: Trophy,       desc: "Embed bảng xếp hạng chi tiêu" },
  { key: "bxh_don_hang",      label: "BXH Đơn hàng",           labelEn: "Order Leaderboard",   icon: Trophy,       desc: "Embed bảng xếp hạng đơn hàng" },
  { key: "feedback",          label: "Feedback khách hàng",    labelEn: "Customer Feedback",   icon: Star,         desc: "Khi user dùng /feedback" },
  { key: "thanh_toan",        label: "Thanh toán thành công",  labelEn: "Payment Success",     icon: CheckCircle,  desc: "Khi khách thanh toán thành công" },
  { key: "giao_hang",         label: "Giao hàng",              labelEn: "Delivery",            icon: Package,      desc: "Khi đơn hàng được giao" },
  { key: "don_hang_chi_tiet", label: "Chi tiết đơn hàng",      labelEn: "Order Detail",        icon: ClipboardList,desc: "Embed chi tiết khi dùng /don_hang" },
  { key: "coupon",            label: "Mã giảm giá",            labelEn: "Coupon",              icon: Tag,          desc: "Khi gửi coupon cho user" },
  { key: "ban_shop",          label: "Cấm mua hàng",           labelEn: "Shop Ban",            icon: Ban,          desc: "Khi user bị cấm mua hàng" },
  { key: "unban_shop",        label: "Bỏ cấm mua hàng",        labelEn: "Shop Unban",          icon: ShieldOff,    desc: "Khi user được bỏ cấm mua hàng" },
  // ── Cộng đồng ──
  { key: "giveaway",          label: "Giveaway bắt đầu",       labelEn: "Giveaway",            icon: Gift,         desc: "Khi tạo /giveaway" },
  { key: "ket_qua_giveaway",  label: "Kết quả Giveaway",       labelEn: "Giveaway Result",     icon: Trophy,       desc: "Khi giveaway kết thúc, công bố winner" },
  { key: "reaction_role_panel",label: "Panel Reaction Role",   labelEn: "Reaction Role Panel", icon: Heart,        desc: "Panel chọn role bằng reaction" },
  { key: "starboard_post",    label: "Bài đăng Starboard",     labelEn: "Starboard Post",      icon: Star,         desc: "Khi tin nhắn được thêm vào starboard" },
  { key: "invite_join",       label: "Thành viên qua invite",  labelEn: "Invite Join",         icon: UserPlus,     desc: "Khi thành viên tham gia qua invite" },
  { key: "invite_leaderboard",label: "BXH Invite",             labelEn: "Invite Leaderboard",  icon: Trophy,       desc: "Bảng xếp hạng mời thành viên" },
  { key: "giveaway_banned",   label: "Cấm tham gia Giveaway",  labelEn: "Giveaway Banned",     icon: Ban,          desc: "Khi user bị cấm tham gia giveaway" },
  // ── Kiểm duyệt ──
  { key: "canh_bao",          label: "Cảnh báo thành viên",    labelEn: "Warning",              icon: ShieldAlert,  desc: "Khi admin dùng /warn" },
  { key: "kick",              label: "Kick thành viên",        labelEn: "Kick",                 icon: UserMinus,    desc: "Khi bot kick user" },
  { key: "ban",               label: "Ban thành viên",         labelEn: "Ban",                  icon: Ban,          desc: "Khi bot ban user" },
  { key: "unban",             label: "Unban thành viên",       labelEn: "Unban",                icon: ShieldOff,    desc: "Khi bot unban user" },
  { key: "automod_warn",      label: "AutoMod: Cảnh báo",     labelEn: "AutoMod Warning",      icon: AlertTriangle, desc: "Khi AutoMod cảnh báo user" },
  { key: "automod_mute",      label: "AutoMod: Mute",         labelEn: "AutoMod Mute",         icon: Shield,        desc: "Khi AutoMod mute user" },
  { key: "automod_kick",      label: "AutoMod: Kick",         labelEn: "AutoMod Kick",         icon: UserMinus,     desc: "Khi AutoMod kick user" },
  { key: "automod_delete",    label: "AutoMod: Xóa tin nhắn", labelEn: "AutoMod Delete",       icon: Trash2,        desc: "Khi AutoMod xóa tin nhắn vi phạm" },
  { key: "timeout",           label: "Timeout",               labelEn: "Timeout",              icon: Timer,         desc: "Khi user bị timeout" },
  { key: "softban",          label: "Softban",               labelEn: "Softban",              icon: Ban,           desc: "Khi user bị softban (ban + unban xóa tin nhắn)" },
  { key: "mute",             label: "Mute",                  labelEn: "Mute",                 icon: Shield,        desc: "Khi user bị mute/timeout bởi mod" },
  { key: "deafen",           label: "Deafen",                labelEn: "Deafen",               icon: Shield,        desc: "Khi user bị deafen trong voice" },
  { key: "rolepersist",      label: "Role Persist",          labelEn: "Role Persist",         icon: Shield,        desc: "Khi gán role cố định (persist qua leave/rejoin)" },
  { key: "temprole",         label: "Temp Role",             labelEn: "Temp Role",            icon: Timer,         desc: "Khi gán role tạm thời" },
  { key: "lockdown_start",   label: "Lockdown bắt đầu",     labelEn: "Lockdown Start",       icon: Shield,        desc: "Khi server vào chế độ lockdown" },
  { key: "lockdown_end",     label: "Lockdown kết thúc",     labelEn: "Lockdown End",         icon: ShieldOff,     desc: "Khi server thoát lockdown" },
  // ── Tiện ích ──
  { key: "afk_set",           label: "Đặt AFK",               labelEn: "AFK Set",              icon: Moon,          desc: "Khi user đặt trạng thái AFK" },
  { key: "afk_return",        label: "Trở lại từ AFK",        labelEn: "AFK Return",           icon: Zap,           desc: "Khi user AFK quay lại" },
  { key: "sticky_message",    label: "Tin nhắn ghim (Sticky)", labelEn: "Sticky Message",       icon: Pin,           desc: "Embed sticky message tự động" },
  // ── Help ──
  { key: "help_menu",         label: "Help — Menu chính",     labelEn: "Help Menu",            icon: HelpCircle,    desc: "Embed chào mừng khi dùng /help" },
  { key: "help_category",     label: "Help — Danh mục",       labelEn: "Help Category",        icon: HelpCircle,    desc: "Embed hiển thị lệnh trong một danh mục" },
  { key: "help_command",      label: "Help — Chi tiết lệnh",  labelEn: "Help Command",         icon: HelpCircle,    desc: "Embed chi tiết một lệnh cụ thể" },
  // ── Logging ──
  { key: "log_message_delete",     label: "Log: Xóa tin nhắn",       labelEn: "Message Deleted",       icon: Trash2,          desc: "Khi tin nhắn bị xóa" },
  { key: "log_message_edit",       label: "Log: Sửa tin nhắn",       labelEn: "Message Edited",        icon: Pencil,          desc: "Khi tin nhắn được sửa" },
  { key: "log_message_bulk_delete",label: "Log: Xóa hàng loạt",      labelEn: "Bulk Delete",           icon: Trash2,          desc: "Khi xóa nhiều tin nhắn cùng lúc" },
  { key: "log_voice_join",         label: "Log: Vào voice",           labelEn: "Voice Join",            icon: Volume2,         desc: "Khi user vào voice channel" },
  { key: "log_voice_leave",        label: "Log: Rời voice",           labelEn: "Voice Leave",           icon: VolumeX,         desc: "Khi user rời voice channel" },
  { key: "log_voice_move",         label: "Log: Chuyển voice",        labelEn: "Voice Move",            icon: ArrowRightLeft,  desc: "Khi user chuyển voice channel" },
  { key: "log_member_join",        label: "Log: Thành viên mới",      labelEn: "Member Join",           icon: LogIn,           desc: "Khi member tham gia server" },
  { key: "log_member_leave",       label: "Log: Thành viên rời",      labelEn: "Member Leave",          icon: LogOut,          desc: "Khi member rời server" },
  { key: "log_nickname_change",    label: "Log: Đổi nickname",        labelEn: "Nickname Change",       icon: Pencil,          desc: "Khi member đổi nickname" },
  { key: "log_role_update",        label: "Log: Thay đổi role",       labelEn: "Role Update",           icon: ShieldAlert,     desc: "Khi role của member thay đổi" },
  { key: "log_channel_create",     label: "Log: Tạo kênh",            labelEn: "Channel Created",       icon: Hash,            desc: "Khi kênh mới được tạo" },
  { key: "log_channel_delete",     label: "Log: Xóa kênh",            labelEn: "Channel Deleted",       icon: Hash,            desc: "Khi kênh bị xóa" },
  // ── Tương tác — Có mục tiêu ──
  { key: "interact_airkiss",    label: "Airkiss",       labelEn: "Air Kiss",      icon: Heart, desc: "Gửi nụ hôn gió cho người khác" },
  { key: "interact_angrystare", label: "Angry Stare",   labelEn: "Angry Stare",   icon: Heart, desc: "Nhìn giận dữ người khác" },
  { key: "interact_bite",       label: "Bite",          labelEn: "Bite",          icon: Heart, desc: "Cắn người khác" },
  { key: "interact_brofist",    label: "Brofist",       labelEn: "Brofist",       icon: Heart, desc: "Đấm tay với người khác" },
  { key: "interact_cuddle",     label: "Cuddle",        labelEn: "Cuddle",        icon: Heart, desc: "Ôm ấp người khác" },
  { key: "interact_handhold",   label: "Handhold",      labelEn: "Hand Hold",     icon: Heart, desc: "Nắm tay người khác" },
  { key: "interact_hug",        label: "Hug",           labelEn: "Hug",           icon: Heart, desc: "Ôm người khác" },
  { key: "interact_kiss",       label: "Kiss",          labelEn: "Kiss",          icon: Heart, desc: "Hôn người khác" },
  { key: "interact_lick",       label: "Lick",          labelEn: "Lick",          icon: Heart, desc: "Liếm người khác" },
  { key: "interact_nom",        label: "Nom",           labelEn: "Nom",           icon: Heart, desc: "Ăn người khác" },
  { key: "interact_nuzzle",     label: "Nuzzle",        labelEn: "Nuzzle",        icon: Heart, desc: "Cọ mũi với người khác" },
  { key: "interact_pat",        label: "Pat",           labelEn: "Pat",           icon: Heart, desc: "Xoa đầu người khác" },
  { key: "interact_pinch",      label: "Pinch",         labelEn: "Pinch",         icon: Heart, desc: "Véo người khác" },
  { key: "interact_poke",       label: "Poke",          labelEn: "Poke",          icon: Heart, desc: "Chọc người khác" },
  { key: "interact_punch",      label: "Punch",         labelEn: "Punch",         icon: Heart, desc: "Đấm người khác" },
  { key: "interact_slap",       label: "Slap",          labelEn: "Slap",          icon: Heart, desc: "Tát người khác" },
  { key: "interact_smack",      label: "Smack",         labelEn: "Smack",         icon: Heart, desc: "Đánh người khác" },
  { key: "interact_tickle",     label: "Tickle",        labelEn: "Tickle",        icon: Heart, desc: "Cù người khác" },
  { key: "interact_wave",       label: "Wave",          labelEn: "Wave",          icon: Heart, desc: "Vẫy tay với người khác" },
  { key: "interact_wink",       label: "Wink",          labelEn: "Wink",          icon: Heart, desc: "Nháy mắt với người khác" },
  { key: "interact_stare",      label: "Stare",         labelEn: "Stare",         icon: Heart, desc: "Nhìn chằm chằm người khác" },
  { key: "interact_peek",       label: "Peek",          labelEn: "Peek",          icon: Heart, desc: "Nhìn trộm người khác" },
  // ── Tương tác — Biểu cảm ──
  { key: "interact_bleh",       label: "Bleh", labelEn: "Bleh",          icon: Heart, desc: "Le lưỡi", descEn: "Stick out tongue" },
  { key: "interact_blush",      label: "Blush", labelEn: "Blush",         icon: Heart, desc: "Đỏ mặt", descEn: "Blush" },
  { key: "interact_celebrate",  label: "Celebrate", labelEn: "Celebrate",     icon: Heart, desc: "Ăn mừng", descEn: "Celebrate" },
  { key: "interact_cheers",     label: "Cheers", labelEn: "Cheers",        icon: Heart, desc: "Nâng ly", descEn: "Raise a toast" },
  { key: "interact_clap",       label: "Clap", labelEn: "Clap",          icon: Heart, desc: "Vỗ tay", descEn: "Clap" },
  { key: "interact_confused",   label: "Confused", labelEn: "Confused",      icon: Heart, desc: "Bối rối", descEn: "Look confused" },
  { key: "interact_cool",       label: "Cool", labelEn: "Cool",          icon: Heart, desc: "Ngầu", descEn: "Act cool" },
  { key: "interact_cry",        label: "Cry", labelEn: "Cry",           icon: Heart, desc: "Khóc", descEn: "Cry" },
  { key: "interact_dance",      label: "Dance", labelEn: "Dance",         icon: Heart, desc: "Nhảy", descEn: "Dance" },
  { key: "interact_drool",      label: "Drool", labelEn: "Drool",         icon: Heart, desc: "Chảy nước miếng", descEn: "Drool" },
  { key: "interact_evillaugh",  label: "Evil Laugh", labelEn: "Evil Laugh",    icon: Heart, desc: "Cười ác", descEn: "Evil laugh" },
  { key: "interact_facepalm",   label: "Facepalm", labelEn: "Facepalm",      icon: Heart, desc: "Facepalm", descEn: "Facepalm" },
  { key: "interact_happy",      label: "Happy", labelEn: "Happy",         icon: Heart, desc: "Vui vẻ", descEn: "Feel happy" },
  { key: "interact_headbang",   label: "Headbang", labelEn: "Headbang",      icon: Heart, desc: "Headbang", descEn: "Headbang" },
  { key: "interact_huh",        label: "Huh", labelEn: "Huh",           icon: Heart, desc: "Hả?", descEn: "Look puzzled" },
  { key: "interact_laugh",      label: "Laugh", labelEn: "Laugh",         icon: Heart, desc: "Cười", descEn: "Laugh" },
  { key: "interact_love",       label: "Love", labelEn: "Love",          icon: Heart, desc: "Yêu", descEn: "Express love" },
  { key: "interact_mad",        label: "Mad", labelEn: "Mad",           icon: Heart, desc: "Giận dữ", descEn: "Get mad" },
  { key: "interact_nervous",    label: "Nervous", labelEn: "Nervous",       icon: Heart, desc: "Lo lắng", descEn: "Feel nervous" },
  { key: "interact_no",         label: "No", labelEn: "No",            icon: Heart, desc: "Lắc đầu", descEn: "Shake head no" },
  { key: "interact_nosebleed",  label: "Nosebleed", labelEn: "Nosebleed",     icon: Heart, desc: "Chảy máu mũi", descEn: "Nosebleed" },
  { key: "interact_nyah",       label: "Nyah", labelEn: "Nyah",          icon: Heart, desc: "Nyah~", descEn: "Nyah~" },
  { key: "interact_pout",       label: "Pout", labelEn: "Pout",          icon: Heart, desc: "Phụng phịu", descEn: "Pout" },
  { key: "interact_roll",       label: "Roll", labelEn: "Roll",          icon: Heart, desc: "Lăn", descEn: "Roll around" },
  { key: "interact_run",        label: "Run", labelEn: "Run",           icon: Heart, desc: "Chạy", descEn: "Run away" },
  { key: "interact_sad",        label: "Sad", labelEn: "Sad",           icon: Heart, desc: "Buồn", descEn: "Feel sad" },
  { key: "interact_scared",     label: "Scared", labelEn: "Scared",        icon: Heart, desc: "Sợ hãi", descEn: "Feel scared" },
  { key: "interact_shout",      label: "Shout", labelEn: "Shout",         icon: Heart, desc: "Hét", descEn: "Shout" },
  { key: "interact_shrug",      label: "Shrug", labelEn: "Shrug",         icon: Heart, desc: "Nhún vai", descEn: "Shrug" },
  { key: "interact_shy",        label: "Shy", labelEn: "Shy",           icon: Heart, desc: "Ngại ngùng", descEn: "Feel shy" },
  { key: "interact_sigh",       label: "Sigh", labelEn: "Sigh",          icon: Heart, desc: "Thở dài", descEn: "Sigh" },
  { key: "interact_sip",        label: "Sip", labelEn: "Sip",           icon: Heart, desc: "Nhâm nhi", descEn: "Sip a drink" },
  { key: "interact_sleep",      label: "Sleep", labelEn: "Sleep",         icon: Heart, desc: "Ngủ", descEn: "Fall asleep" },
  { key: "interact_slowclap",   label: "Slow Clap", labelEn: "Slow Clap",     icon: Heart, desc: "Vỗ tay chậm", descEn: "Slow clap" },
  { key: "interact_smile",      label: "Smile", labelEn: "Smile",         icon: Heart, desc: "Cười", descEn: "Smile" },
  { key: "interact_smug",       label: "Smug", labelEn: "Smug",          icon: Heart, desc: "Tự mãn", descEn: "Look smug" },
  { key: "interact_sneeze",     label: "Sneeze", labelEn: "Sneeze",        icon: Heart, desc: "Hắt xì", descEn: "Sneeze" },
  { key: "interact_sorry",      label: "Sorry", labelEn: "Sorry",         icon: Heart, desc: "Xin lỗi", descEn: "Apologize" },
  { key: "interact_stop",       label: "Stop", labelEn: "Stop",          icon: Heart, desc: "Dừng lại", descEn: "Signal to stop" },
  { key: "interact_surprised",  label: "Surprised", labelEn: "Surprised",     icon: Heart, desc: "Ngạc nhiên", descEn: "Look surprised" },
  { key: "interact_sweat",      label: "Sweat", labelEn: "Sweat",         icon: Heart, desc: "Toát mồ hôi", descEn: "Sweat nervously" },
  { key: "interact_thumbsup",   label: "Thumbs Up", labelEn: "Thumbs Up",     icon: Heart, desc: "Thích", descEn: "Thumbs up" },
  { key: "interact_tired",      label: "Tired", labelEn: "Tired",         icon: Heart, desc: "Mệt", descEn: "Feel tired" },
  { key: "interact_woah",       label: "Woah", labelEn: "Woah",          icon: Heart, desc: "Woah", descEn: "Woah" },
  { key: "interact_yawn",       label: "Yawn", labelEn: "Yawn",          icon: Heart, desc: "Ngáp", descEn: "Yawn" },
  { key: "interact_yay",        label: "Yay", labelEn: "Yay",           icon: Heart, desc: "Yay!", descEn: "Yay!" },
  { key: "interact_yes",        label: "Yes", labelEn: "Yes",           icon: Heart, desc: "Gật đầu", descEn: "Nod yes" },
  // ── Bảo mật & Khôi phục ──
  { key: "verification_log",       label: "Xác minh thành công",     labelEn: "Verification Success",   icon: ShieldCheck,  desc: "Khi user xác minh thành công qua OAuth2" },
  { key: "verification_denied",    label: "Xác minh bị từ chối",     labelEn: "Verification Denied",    icon: ShieldAlert,  desc: "Khi user bị từ chối xác minh" },
  { key: "verify_panel",           label: "Panel xác minh",          labelEn: "Verify Panel",           icon: ShieldCheck,  desc: "Embed panel xác minh gửi trong kênh (/verify embed)" },
  { key: "verify_blacklist",       label: "Blacklist thành viên",    labelEn: "Member Blacklisted",     icon: Ban,          desc: "Khi admin blacklist thành viên khỏi xác minh" },
  { key: "verify_whitelist",       label: "Whitelist thành viên",    labelEn: "Member Whitelisted",     icon: ShieldCheck,  desc: "Khi admin gỡ blacklist thành viên" },
  { key: "backup_completed",       label: "Sao lưu hoàn tất",        labelEn: "Backup Completed",       icon: Archive,      desc: "Khi sao lưu server hoàn tất" },
  { key: "restore_started",        label: "Đang khôi phục",          labelEn: "Restore Started",        icon: RotateCcw,    desc: "Khi bắt đầu khôi phục server" },
  { key: "restore_completed",      label: "Khôi phục hoàn tất",      labelEn: "Restore Completed",      icon: CheckCircle,  desc: "Khi khôi phục server hoàn tất" },
  { key: "member_pull_started",    label: "Đang kéo thành viên",     labelEn: "Member Pull Started",    icon: Users,        desc: "Khi bắt đầu kéo thành viên về server" },
  { key: "member_pull_completed",  label: "Kéo thành viên hoàn tất", labelEn: "Member Pull Completed",  icon: UserPlus,     desc: "Khi kéo thành viên về server hoàn tất" },
  // ── Cảnh báo Server ──
  { key: "alert_mass_ban",        label: "Cảnh báo Mass Ban",       labelEn: "Mass Ban Alert",         icon: AlertTriangle, desc: "Khi phát hiện nhiều ban liên tục" },
  { key: "alert_mass_kick",       label: "Cảnh báo Mass Kick",      labelEn: "Mass Kick Alert",        icon: AlertTriangle, desc: "Khi phát hiện nhiều kick liên tục" },
  { key: "alert_channel_delete",  label: "Cảnh báo xóa kênh",      labelEn: "Channel Delete Alert",   icon: Trash2,        desc: "Khi phát hiện xóa nhiều kênh liên tục" },
  { key: "alert_role_delete",     label: "Cảnh báo xóa role",       labelEn: "Role Delete Alert",      icon: Trash2,        desc: "Khi phát hiện xóa nhiều role liên tục" },
  { key: "alert_nuke_detect",     label: "Phát hiện Nuke",          labelEn: "Nuke Detected",          icon: Zap,           desc: "Khi phát hiện hành vi phá server (nuke)" },
];

// ─── Event groups ────────────────────────────────────────────────────────────

export const EVENT_GROUPS: { label: string; labelEn: string; keys: string[] }[] = [
  { label: "Đơn hàng",    labelEn: "Orders",         keys: ["don_hang_moi", "qr_thanh_toan", "qr_thanh_toan_payos", "qr_thanh_toan_paypal", "qr_thanh_toan_crypto", "qr_thanh_toan_manual", "don_hang_het_han", "ghi_chu_don_hang", "bang_gia", "san_pham_detail", "bxh_chi_tieu", "bxh_don_hang", "feedback", "thanh_toan", "giao_hang", "don_hang_chi_tiet", "coupon", "ban_shop", "unban_shop"] },
  { label: "Cộng đồng",   labelEn: "Community",      keys: ["giveaway", "ket_qua_giveaway", "reaction_role_panel", "starboard_post", "giveaway_banned", "invite_join", "invite_leaderboard"] },
  { label: "Kiểm duyệt", labelEn: "Moderation",      keys: ["canh_bao", "kick", "ban", "unban", "softban", "mute", "deafen", "rolepersist", "temprole", "lockdown_start", "lockdown_end", "automod_warn", "automod_mute", "automod_kick", "automod_delete", "timeout"] },
  { label: "Tiện ích",    labelEn: "Utilities",       keys: ["afk_set", "afk_return", "sticky_message"] },
  { label: "Help",        labelEn: "Help",            keys: ["help_menu", "help_category", "help_command"] },
  { label: "Logging",     labelEn: "Logging",         keys: ["log_message_delete", "log_message_edit", "log_message_bulk_delete", "log_voice_join", "log_voice_leave", "log_voice_move", "log_member_join", "log_member_leave", "log_nickname_change", "log_role_update", "log_channel_create", "log_channel_delete"] },
  { label: "Tương tác — Có mục tiêu", labelEn: "Interactions — Targeted", keys: ["interact_airkiss", "interact_angrystare", "interact_bite", "interact_brofist", "interact_cuddle", "interact_handhold", "interact_hug", "interact_kiss", "interact_lick", "interact_nom", "interact_nuzzle", "interact_pat", "interact_pinch", "interact_poke", "interact_punch", "interact_slap", "interact_smack", "interact_tickle", "interact_wave", "interact_wink", "interact_stare", "interact_peek"] },
  { label: "Tương tác — Biểu cảm", labelEn: "Interactions — Expressions", keys: ["interact_bleh", "interact_blush", "interact_celebrate", "interact_cheers", "interact_clap", "interact_confused", "interact_cool", "interact_cry", "interact_dance", "interact_drool", "interact_evillaugh", "interact_facepalm", "interact_happy", "interact_headbang", "interact_huh", "interact_laugh", "interact_love", "interact_mad", "interact_nervous", "interact_no", "interact_nosebleed", "interact_nyah", "interact_pout", "interact_roll", "interact_run", "interact_sad", "interact_scared", "interact_shout", "interact_shrug", "interact_shy", "interact_sigh", "interact_sip", "interact_sleep", "interact_slowclap", "interact_smile", "interact_smug", "interact_sneeze", "interact_sorry", "interact_stop", "interact_surprised", "interact_sweat", "interact_thumbsup", "interact_tired", "interact_woah", "interact_yawn", "interact_yay", "interact_yes"] },
  { label: "Bảo mật & Khôi phục", labelEn: "Security & Recovery", keys: ["verify_panel", "verification_log", "verification_denied", "verify_blacklist", "verify_whitelist", "backup_completed", "restore_started", "restore_completed", "member_pull_started", "member_pull_completed"] },
  { label: "Cảnh báo Server", labelEn: "Server Alerts", keys: ["alert_mass_ban", "alert_mass_kick", "alert_channel_delete", "alert_role_delete", "alert_nuke_detect"] },
];

// ─── Variables reference ─────────────────────────────────────────────────────

export const VARIABLES: { token: string; desc: string; descEn: string }[] = [
  { token: "{user}",              desc: "Tên người dùng",                    descEn: "Username" },
  { token: "{user.mention}",      desc: "@mention người dùng",               descEn: "@mention of the user" },
  { token: "{user.id}",           desc: "Discord ID",                        descEn: "Discord user ID" },
  { token: "{order.id}",          desc: "Mã đơn hàng (#12345)",              descEn: "Order ID (#12345)" },
  { token: "{order.total}",       desc: "Tổng tiền (100,000)",               descEn: "Order total amount" },
  { token: "{order.status}",      desc: "Trạng thái đơn hàng",              descEn: "Order status" },
  { token: "{order.note}",        desc: "Ghi chú đơn hàng",                 descEn: "Order note" },
  { token: "{order.created_at}",  desc: "Ngày tạo đơn",                     descEn: "Order creation date" },
  { token: "{note}",              desc: "Ghi chú đơn hàng",                 descEn: "Order note" },
  { token: "{product.name}",      desc: "Tên sản phẩm",                     descEn: "Product name" },
  { token: "{product.description}", desc: "Mô tả sản phẩm",                 descEn: "Product description" },
  { token: "{package.name}",      desc: "Tên gói sản phẩm (san_pham_detail)", descEn: "Package name (san_pham_detail)" },
  { token: "{package.price}",     desc: "Giá gói sản phẩm (san_pham_detail)", descEn: "Package price (san_pham_detail)" },
  { token: "{package.description}", desc: "Mô tả gói sản phẩm (san_pham_detail)", descEn: "Package description (san_pham_detail)" },
  { token: "{product.price}",     desc: "Giá sản phẩm",                     descEn: "Product price" },
  { token: "{product.stock}",     desc: "Số lượng tồn kho",                 descEn: "Product stock quantity" },
  { token: "{product.image_url}", desc: "Ảnh sản phẩm",                     descEn: "Product image URL" },
  { token: "{qr_url}",            desc: "URL ảnh QR thanh toán",            descEn: "Payment QR image URL" },
  { token: "{transfer_content}",  desc: "Nội dung chuyển khoản",            descEn: "Bank transfer content" },
  { token: "{bank_name}",         desc: "Tên ngân hàng (manual payment)",   descEn: "Bank name (manual payment)" },
  { token: "{account_holder}",    desc: "Chủ tài khoản (manual payment)",   descEn: "Account holder (manual payment)" },
  { token: "{account_number}",    desc: "Số tài khoản (manual payment)",    descEn: "Account number (manual payment)" },
  { token: "{instructions}",      desc: "Hướng dẫn thanh toán (manual)",    descEn: "Payment instructions (manual)" },
  { token: "{coupon.code}",       desc: "Mã coupon",                        descEn: "Coupon code" },
  { token: "{coupon.discount}",   desc: "Giá trị giảm giá",                 descEn: "Discount value" },
  { token: "{coupon.type}",       desc: "Loại giảm giá (% hoặc số tiền)",   descEn: "Discount type (% or amount)" },
  { token: "{coupon.expires_at}", desc: "Hạn sử dụng coupon",               descEn: "Coupon expiry date" },
  { token: "{package}",           desc: "Nội dung gói (cho đơn custom)",    descEn: "Package content (custom order)" },
  { token: "{date}",              desc: "Ngày giờ hiện tại",                descEn: "Current date and time" },
  { token: "{server}",            desc: "Tên server",                       descEn: "Server name" },
  { token: "{member_count}",      desc: "Số thành viên",                    descEn: "Member count" },
  { token: "{prize}",             desc: "Phần thưởng (giveaway)",           descEn: "Giveaway prize" },
  { token: "{ends_at}",           desc: "Thời gian kết thúc (giveaway)",    descEn: "Giveaway end time" },
  { token: "{host}",              desc: "Người tổ chức (giveaway)",         descEn: "Giveaway host" },
  { token: "{winners_count}",     desc: "Số người thắng (giveaway)",        descEn: "Number of winners" },
  { token: "{winners}",           desc: "Tên người thắng (ket_qua_giveaway)", descEn: "Winner names" },
  { token: "{reason}",            desc: "Lý do (warn/ban/kick/cấm)",        descEn: "Reason (warn/ban/kick)" },
  { token: "{warn_count}",        desc: "Tổng số cảnh báo",                 descEn: "Total warning count" },
  { token: "{moderator}",         desc: "Người thực hiện (mod)",            descEn: "Moderator who performed the action" },
  { token: "{stars}",             desc: "Số sao (feedback)",                descEn: "Star rating (feedback)" },
  { token: "{content}",           desc: "Nội dung feedback",                descEn: "Feedback content" },
  { token: "{channel.name}",      desc: "Tên kênh Discord",                 descEn: "Discord channel name" },
  { token: "{panel.channel}",     desc: "Kênh được gửi panel",              descEn: "Channel where panel was sent" },
  { token: "{button.count}",      desc: "Số nút temp voice đang bật",       descEn: "Number of active temp voice buttons" },
  { token: "{buttons}",           desc: "Danh sách nút temp voice đang bật", descEn: "List of active temp voice buttons" },
  { token: "{channel.mention}",   desc: "Mention kênh Discord",             descEn: "Discord channel mention" },
  { token: "{channel.id}",        desc: "ID kênh Discord",                  descEn: "Discord channel ID" },
  { token: "{target}",            desc: "Tên user mục tiêu",                descEn: "Target user name" },
  { token: "{target.mention}",    desc: "Mention user mục tiêu",            descEn: "Target user @mention" },
  { token: "{target.id}",         desc: "ID user mục tiêu",                 descEn: "Target user ID" },
  { token: "{action}",            desc: "Hành động được thực hiện",         descEn: "Action performed" },
  { token: "{details}",           desc: "Chi tiết hành động",               descEn: "Action details" },
  { token: "{duration}",          desc: "Thời gian timeout / AFK",          descEn: "Timeout / AFK duration" },
  { token: "{mod}",               desc: "Tên mod thực hiện",                descEn: "Moderator name" },
  { token: "{invite_code}",       desc: "Mã invite",                        descEn: "Invite code" },
  { token: "{inviter}",           desc: "Người mời",                        descEn: "Person who sent the invite" },
  { token: "{invite.count}",      desc: "Số người được mời",                descEn: "Total invite count" },
  { token: "{top1}",              desc: "Top 1 BXH mời",                    descEn: "Invite leaderboard #1" },
  { token: "{top2}",              desc: "Top 2 BXH mời",                    descEn: "Invite leaderboard #2" },
  { token: "{top3}",              desc: "Top 3 BXH mời",                    descEn: "Invite leaderboard #3" },
  { token: "{sticky.title}",      desc: "Tiêu đề sticky",                   descEn: "Sticky message title" },
  { token: "{sticky.content}",    desc: "Nội dung sticky",                  descEn: "Sticky message content" },
  { token: "{channel}",           desc: "Mention kênh (log)",               descEn: "Channel mention (log)" },
  { token: "{before}",            desc: "Nội dung trước (edit/nick)",       descEn: "Content before (edit/nick)" },
  { token: "{after}",             desc: "Nội dung sau (edit/nick)",         descEn: "Content after (edit/nick)" },
  { token: "{message.url}",       desc: "Link tin nhắn",                    descEn: "Message link" },
  { token: "{count}",             desc: "Số lượng (bulk delete)",           descEn: "Count (bulk delete)" },
  { token: "{from}",              desc: "Kênh voice cũ",                    descEn: "Previous voice channel" },
  { token: "{to}",                desc: "Kênh voice mới",                   descEn: "New voice channel" },
  { token: "{account_age}",       desc: "Thời gian tạo tài khoản",          descEn: "Account creation age" },
  { token: "{roles}",             desc: "Danh sách role",                   descEn: "Role list" },
  { token: "{changes}",           desc: "Thay đổi role",                    descEn: "Role changes" },
  { token: "{type}",              desc: "Loại kênh",                        descEn: "Channel type" },
  { token: "{time_label}",        desc: "Thời gian BXH (Hôm nay, 7 ngày...)", descEn: "Leaderboard period (Today, 7 days...)" },
  { token: "{leaderboard_lines}", desc: "Nội dung BXH (danh sách top)",     descEn: "Leaderboard lines (top list)" },
  { token: "{updated_at}",        desc: "Thời gian cập nhật BXH",           descEn: "Leaderboard last updated" },
  { token: "{emoji}",             desc: "Emoji tương tác",                  descEn: "Interaction emoji" },
  { token: "{gif_url}",           desc: "URL ảnh GIF tương tác",            descEn: "Interaction GIF URL" },
  { token: "{role.name}",         desc: "Tên role (rolepersist/temprole)",   descEn: "Role name (rolepersist/temprole)" },
  { token: "{expires_at}",        desc: "Thời gian hết hạn (temprole)",     descEn: "Expiry time (temprole)" },
  { token: "{case_number}",       desc: "Số case xử phạt",                  descEn: "Moderation case number" },
  { token: "{note_id}",           desc: "ID ghi chú mod",                   descEn: "Moderation note ID" },
  { token: "{email}",             desc: "Email xác minh",                   descEn: "Verification email" },
  { token: "{ip}",                desc: "Địa chỉ IP xác minh",             descEn: "Verification IP address" },
  { token: "{risk_score}",        desc: "Điểm rủi ro xác minh",            descEn: "Verification risk score" },
  { token: "{user.tag}",          desc: "Tag Discord (user#0001)",          descEn: "Discord tag (user#0001)" },
  { token: "{backup_type}",       desc: "Loại sao lưu (full/config/discord)", descEn: "Backup type (full/config/discord)" },
  { token: "{channel_count}",     desc: "Số kênh trong backup",             descEn: "Channel count in backup" },
  { token: "{role_count}",        desc: "Số role trong backup",              descEn: "Role count in backup" },
  { token: "{total_members}",     desc: "Tổng thành viên cần kéo",          descEn: "Total members to pull" },
  { token: "{pulled}",            desc: "Số thành viên kéo thành công",     descEn: "Members pulled successfully" },
  { token: "{failed}",            desc: "Số thành viên kéo thất bại",       descEn: "Members pull failed" },
  { token: "{total}",             desc: "Tổng cộng",                        descEn: "Total" },
];
