import type { EmbedTemplate } from "./embedTypes";

type EmbedLang = Omit<EmbedTemplate, "id" | "event_type" | "name">;

export const DEFAULTS: Record<string, { vi: EmbedLang; en: EmbedLang }> = {
  don_hang_moi: {
    vi: {
      title: "Đơn hàng mới",
      description: "Vui lòng thanh toán để hoàn tất đơn hàng.\nHết hạn sau 15 phút.",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Đang chờ thanh toán...",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "ID Đơn", value: "#{order.id}", inline: true },
        { name: "Khách hàng", value: "{user.mention}", inline: true },
        { name: "Sản phẩm", value: "{product.name}", inline: false },
        { name: "Số tiền", value: "{order.total} VNĐ", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "New Order",
      description: "Please complete payment to finalize your order.\nExpires in 15 minutes.",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Awaiting payment...",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Order ID", value: "#{order.id}", inline: true },
        { name: "Customer", value: "{user.mention}", inline: true },
        { name: "Product", value: "{product.name}", inline: false },
        { name: "Amount", value: "{order.total} VNĐ", inline: true },
      ],
      enabled: true,
    },
  },
  don_hang_het_han: {
    vi: {
      title: "Đơn hàng đã hết hạn",
      description: "Đơn hàng #{order.id} của bạn đã hết hạn do chưa thanh toán sau 15 phút.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "Tạo đơn mới để tiếp tục mua hàng.",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Sản phẩm", value: "{product.name}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Order Expired",
      description: "Your order #{order.id} has expired due to non-payment after 15 minutes.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "Create a new order to continue shopping.",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Product", value: "{product.name}", inline: true },
      ],
      enabled: true,
    },
  },
  ghi_chu_don_hang: {
    vi: {
      title: "📝 Ghi chú đơn hàng",
      description: "Đơn hàng #{order.id} của {user.mention} vừa được cập nhật ghi chú.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Infinity Mall",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "📦 Sản phẩm", value: "{product.name}", inline: true },
        { name: "📝 Ghi chú", value: "{note}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "📝 Order Note",
      description: "Order #{order.id} by {user.mention} has been updated with a note.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Infinity Mall",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "📝 Note", value: "{note}", inline: false },
      ],
      enabled: true,
    },
  },
  bang_gia: {
    vi: {
      title: "🛒 Bảng Giá Sản Phẩm",
      description: "Chọn sản phẩm từ menu bên dưới để xem chi tiết và giá các gói.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Bấm vào tên sản phẩm bên dưới để xem chi tiết",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🛒 Product Price List",
      description: "Select a product from the menu below to view details and package prices.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Click a product name below for details",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  san_pham_detail: {
    vi: {
      title: "📦 {product.name}",
      description: "{product.description}",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "Liên hệ admin để đặt hàng",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "🔹 {package.name}", value: "💰 **{package.price}đ**\n{package.description}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "📦 {product.name}",
      description: "{product.description}",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "Contact admin to place an order",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "🔹 {package.name}", value: "💰 **{package.price}đ**\n{package.description}", inline: false },
      ],
      enabled: true,
    },
  },
  feedback: {
    vi: {
      title: "Feedback mới",
      description: "{user} đã gửi đánh giá cho {product.name}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Feedback system",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Xếp hạng", value: "{stars}", inline: true },
        { name: "Nội dung", value: "{content}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "New Feedback",
      description: "{user} submitted a review for {product.name}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Feedback system",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Rating", value: "{stars}", inline: true },
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
  },
  giveaway: {
    vi: {
      title: "GIVEAWAY",
      description: "{prize}\n\nNhấn nút bên dưới để tham gia!\nKết thúc: {ends_at}",
      color: "#FF73FA",
      author: "Tổ chức bởi {host}",
      author_icon_url: "",
      footer: "Kết thúc lúc {ends_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Số người thắng", value: "{winners_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "GIVEAWAY",
      description: "{prize}\n\nPress the button below to enter!\nEnds: {ends_at}",
      color: "#FF73FA",
      author: "Hosted by {host}",
      author_icon_url: "",
      footer: "Ends at {ends_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners_count}", inline: true },
      ],
      enabled: true,
    },
  },
  ket_qua_giveaway: {
    vi: {
      title: "Kết quả Giveaway",
      description: "Giveaway đã kết thúc!\nPhần thưởng: {prize}",
      color: "#FF73FA",
      author: "",
      author_icon_url: "",
      footer: "Chúc mừng người chiến thắng!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Người thắng", value: "{winners}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "Giveaway Results",
      description: "The giveaway has ended!\nPrize: {prize}",
      color: "#FF73FA",
      author: "",
      author_icon_url: "",
      footer: "Congratulations to the winners!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners}", inline: false },
      ],
      enabled: true,
    },
  },
  dm_welcome: {
    vi: {
      title: "👋 Chào mừng {user.name}!",
      description: "Chào mừng {user.mention} đến với **{server.name}**!\nHãy đọc kênh {rules_channel} và tận hưởng!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "{server.name}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👋 Welcome {user.name}!",
      description: "Welcome {user.mention} to **{server.name}**!\nPlease read {rules_channel} and enjoy your stay!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "{server.name}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  reaction_role_panel: {
    vi: {
      title: "🎭 Reaction Role",
      description: "Chọn role bạn muốn bằng cách react bên dưới!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "React để nhận role • Bỏ react để gỡ role",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎭 Reaction Role",
      description: "Choose the role you want by reacting below!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "React to get a role • Remove reaction to remove role",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  starboard_post: {
    vi: {
      title: "⭐ Starboard",
      description: "{user.mention} nhận ⭐ **{star_count}** sao trong {channel}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Starboard",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Nội dung", value: "{content}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "⭐ Starboard",
      description: "{user.mention} received ⭐ **{star_count}** stars in {channel}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Starboard",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
  },
  canh_bao: {
    vi: {
      title: "Cảnh báo",
      description: "{user.mention} đã nhận cảnh báo.",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Hãy tuân thủ nội quy server",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Lý do", value: "{reason}", inline: false },
        { name: "Tổng cảnh báo", value: "{warn_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Warning",
      description: "{user.mention} has received a warning.",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Please follow the server rules",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Total Warnings", value: "{warn_count}", inline: true },
      ],
      enabled: true,
    },
  },
  ticket_mo: {
    vi: {
      title: "🎫 Ticket #{ticket_id} đã được tạo",
      description: "Xin chào {user.mention}!\nTicket của bạn đã được tạo.\nVui lòng mô tả vấn đề để được hỗ trợ.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Hỗ trợ sẽ đến sớm!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Ticket ID", value: "#{ticket_id}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎫 Ticket #{ticket_id} Created",
      description: "Hello {user.mention}!\nYour ticket has been created.\nPlease describe your issue so we can assist you.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Support will be with you shortly!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Ticket ID", value: "#{ticket_id}", inline: true },
      ],
      enabled: true,
    },
  },
  ticket_dong: {
    vi: {
      title: "🔒 Ticket đã đóng",
      description: "Ticket #{ticket_id} của {user.mention} đã được đóng.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Lý do", value: "{close_reason}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "🔒 Ticket Closed",
      description: "Ticket #{ticket_id} by {user.mention} has been closed.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{close_reason}", inline: false },
      ],
      enabled: true,
    },
  },
  ticket_nhan: {
    vi: {
      title: "✋ Ticket đã được nhận",
      description: "{staff.mention} đã nhận ticket #{ticket_id}.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "Chúng tôi sẽ hỗ trợ bạn sớm nhất!",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "✋ Ticket Claimed",
      description: "{staff.mention} has claimed ticket #{ticket_id}.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "We'll assist you as soon as possible!",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  kick: {
    vi: {
      title: "👢 Đã kick khỏi server",
      description: "{user.mention} đã bị kick khỏi server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Lý do", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "👢 Kicked from Server",
      description: "{user.mention} has been kicked from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
  },
  ban: {
    vi: {
      title: "🔨 Đã bị cấm vĩnh viễn",
      description: "{user.mention} đã bị ban khỏi server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Lý do", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🔨 Permanently Banned",
      description: "{user.mention} has been banned from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
  },
  qr_thanh_toan: {
    vi: {
      title: "💳 Thanh toán đơn hàng #{order.id}",
      description: "Quét mã QR bên dưới để thanh toán.\nĐơn hàng sẽ hết hạn sau **15 phút**.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Quét QR bằng app ngân hàng",
      thumbnail_url: "",
      image_url: "{qr_url}",
      fields: [
        { name: "Số tiền", value: "{order.total} VNĐ", inline: true },
        { name: "Nội dung CK", value: "{transfer_content}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "💳 Payment for Order #{order.id}",
      description: "Scan the QR code below to pay.\nYour order will expire in **15 minutes**.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Scan QR with your banking app",
      thumbnail_url: "",
      image_url: "{qr_url}",
      fields: [
        { name: "Amount", value: "{order.total} VNĐ", inline: true },
        { name: "Transfer Note", value: "{transfer_content}", inline: true },
      ],
      enabled: true,
    },
  },
  bxh_chi_tieu: {
    vi: {
      title: "🏆 BXH Chi tiêu — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Cập nhật: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 Spending Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  bxh_don_hang: {
    vi: {
      title: "🏆 BXH Đơn hàng — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Cập nhật: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 Orders Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  unban: {
    vi: {
      title: "🔓 Unban thành viên",
      description: "{user.mention} đã được unban.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Người thực hiện", value: "{moderator}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🔓 Member Unbanned",
      description: "{user.mention} has been unbanned.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Moderator", value: "{moderator}", inline: true },
      ],
      enabled: true,
    },
  },
  ticket_unclaim: {
    vi: {
      title: "↩️ Bỏ nhận Ticket",
      description: "{staff.mention} đã bỏ nhận ticket này.",
      color: "#95A5A6",
      author: "",
      author_icon_url: "",
      footer: "Ticket #{ticket.id}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "↩️ Ticket Unclaimed",
      description: "{staff.mention} has unclaimed this ticket.",
      color: "#95A5A6",
      author: "",
      author_icon_url: "",
      footer: "Ticket #{ticket.id}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  ticket_panel: {
    vi: {
      title: "🎫 Hỗ trợ",
      description: "Chọn loại hỗ trợ bên dưới để tạo ticket.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎫 Support",
      description: "Select a support category below to create a ticket.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_message_delete: {
    vi: {
      title: "🗑️ Tin nhắn bị xóa",
      description: "Tin nhắn của {user.mention} trong {channel} đã bị xóa.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Nội dung", value: "{content}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🗑️ Message Deleted",
      description: "A message by {user.mention} in {channel} has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
  },
  log_message_edit: {
    vi: {
      title: "✏️ Tin nhắn được sửa",
      description: "{user.mention} đã sửa tin nhắn trong {channel}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Trước", value: "{before}", inline: false },
        { name: "Sau", value: "{after}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "✏️ Message Edited",
      description: "{user.mention} edited a message in {channel}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: false },
        { name: "After", value: "{after}", inline: false },
      ],
      enabled: true,
    },
  },
  log_message_bulk_delete: {
    vi: {
      title: "🗑️ Xóa hàng loạt",
      description: "**{count}** tin nhắn đã bị xóa trong {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🗑️ Bulk Delete",
      description: "**{count}** messages were deleted in {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_join: {
    vi: {
      title: "🔊 Vào voice",
      description: "{user.mention} đã vào {channel}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔊 Joined Voice",
      description: "{user.mention} joined {channel}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_leave: {
    vi: {
      title: "🔇 Rời voice",
      description: "{user.mention} đã rời {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔇 Left Voice",
      description: "{user.mention} left {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_move: {
    vi: {
      title: "🔀 Chuyển voice",
      description: "{user.mention} đã chuyển từ {from} sang {to}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔀 Moved Voice",
      description: "{user.mention} moved from {from} to {to}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_member_join: {
    vi: {
      title: "📥 Thành viên mới",
      description: "{user.mention} đã tham gia server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Tạo tài khoản", value: "{account_age}", inline: true },
        { name: "Thành viên thứ", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📥 New Member",
      description: "{user.mention} has joined the server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Account Age", value: "{account_age}", inline: true },
        { name: "Member #", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
  },
  log_member_leave: {
    vi: {
      title: "📤 Thành viên rời",
      description: "{user.mention} đã rời server.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Roles", value: "{roles}", inline: false },
        { name: "Còn lại", value: "{member_count} thành viên", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📤 Member Left",
      description: "{user.mention} has left the server.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Roles", value: "{roles}", inline: false },
        { name: "Remaining", value: "{member_count} members", inline: true },
      ],
      enabled: true,
    },
  },
  log_nickname_change: {
    vi: {
      title: "📝 Đổi nickname",
      description: "{user.mention} đã đổi nickname.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Trước", value: "{before}", inline: true },
        { name: "Sau", value: "{after}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📝 Nickname Changed",
      description: "{user.mention} changed their nickname.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: true },
        { name: "After", value: "{after}", inline: true },
      ],
      enabled: true,
    },
  },
  log_role_update: {
    vi: {
      title: "🎭 Thay đổi role",
      description: "Role của {user.mention} đã được thay đổi.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Thay đổi", value: "{changes}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🎭 Role Updated",
      description: "Roles for {user.mention} have been updated.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Changes", value: "{changes}", inline: false }],
      enabled: true,
    },
  },
  log_channel_create: {
    vi: {
      title: "📺 Kênh mới",
      description: "Kênh {channel} ({type}) đã được tạo.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📺 Channel Created",
      description: "Channel {channel} ({type}) has been created.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_channel_delete: {
    vi: {
      title: "📺 Kênh bị xóa",
      description: "Kênh **{channel.name}** ({type}) đã bị xóa.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📺 Channel Deleted",
      description: "Channel **{channel.name}** ({type}) has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  // ── AutoMod ──
  automod_warn: {
    vi: {
      title: "⚠️ AutoMod — Cảnh báo",
      description: "{user.mention} đã bị cảnh báo bởi AutoMod.\n**Lý do:** {reason}",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Kênh", value: "{channel}", inline: true }],
      enabled: true,
    },
    en: {
      title: "⚠️ AutoMod — Warning",
      description: "{user.mention} has been warned by AutoMod.\n**Reason:** {reason}",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channel", value: "{channel}", inline: true }],
      enabled: true,
    },
  },
  automod_mute: {
    vi: {
      title: "🔇 AutoMod — Mute",
      description: "{user.mention} đã bị mute bởi AutoMod.\n**Lý do:** {reason}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Thời gian", value: "{duration}", inline: true }],
      enabled: true,
    },
    en: {
      title: "🔇 AutoMod — Mute",
      description: "{user.mention} has been muted by AutoMod.\n**Reason:** {reason}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Duration", value: "{duration}", inline: true }],
      enabled: true,
    },
  },
  automod_kick: {
    vi: {
      title: "👢 AutoMod — Kick",
      description: "{user.mention} đã bị kick bởi AutoMod.\n**Lý do:** {reason}",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👢 AutoMod — Kick",
      description: "{user.mention} has been kicked by AutoMod.\n**Reason:** {reason}",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  automod_delete: {
    vi: {
      title: "🗑️ AutoMod — Xóa tin nhắn",
      description: "Tin nhắn của {user.mention} đã bị xóa bởi AutoMod.\n**Lý do:** {reason}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Nội dung", value: "{content}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🗑️ AutoMod — Message Deleted",
      description: "A message by {user.mention} was deleted by AutoMod.\n**Reason:** {reason}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
  },
  // ── AFK ──
  afk_set: {
    vi: {
      title: "💤 AFK",
      description: "{user.mention} đã đặt AFK: **{reason}**",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💤 AFK",
      description: "{user.mention} is now AFK: **{reason}**",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  afk_return: {
    vi: {
      title: "👋 Đã trở lại",
      description: "{user.mention} đã trở lại! (AFK {duration})",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👋 Welcome Back",
      description: "{user.mention} is back! (AFK {duration})",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  tempvoice_create: {
    vi: {
      title: "🔊 Voice tạm đã tạo",
      description: "{user.mention} đã tạo kênh voice **{channel.name}**.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Dùng nút bên dưới để quản lý phòng", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Kênh", value: "{channel.mention}", inline: true },
        { name: "Chủ phòng", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🔊 Temp Voice Created",
      description: "{user.mention} created a voice channel **{channel.name}**.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Use the buttons below to manage your room", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Channel", value: "{channel.mention}", inline: true },
        { name: "Owner", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
  },
  tempvoice_panel: {
    vi: {
      title: "🎙️ Điều khiển phòng voice",
      description: "Panel quản lý phòng voice tạm cho **{server}**.\n\nVào phòng voice của bạn rồi dùng các nút bên dưới để khóa, đổi tên, giới hạn, cấp quyền hoặc chuyển chủ phòng.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Temp Voice Control Panel", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Kênh gửi", value: "{panel.channel}", inline: true },
        { name: "Nút bật", value: "{button.count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎙️ Voice Room Control",
      description: "Temp voice management panel for **{server}**.\n\nJoin your voice channel and use the buttons below to lock, rename, limit, grant permissions, or transfer ownership.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Temp Voice Control Panel", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Panel Channel", value: "{panel.channel}", inline: true },
        { name: "Buttons", value: "{button.count}", inline: true },
      ],
      enabled: true,
    },
  },
  tempvoice_action: {
    vi: {
      title: "🎙️ Temp Voice Action",
      description: "{user.mention} đã **{action}** trong {channel.mention}.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Temp Voice Logs", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Mục tiêu", value: "{target.mention}", inline: true },
        { name: "Chi tiết", value: "{details}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎙️ Temp Voice Action",
      description: "{user.mention} performed **{action}** in {channel.mention}.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Temp Voice Logs", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Target", value: "{target.mention}", inline: true },
        { name: "Details", value: "{details}", inline: true },
      ],
      enabled: true,
    },
  },
  level_up: {
    vi: {
      title: "🎉 Lên Level {level}!",
      description: "Chúc mừng {user.mention} đã lên **Level {level}**!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "Tiếp tục chat để lên level nhé!", thumbnail_url: "", image_url: "",
      fields: [
        { name: "XP hiện tại", value: "{current_xp}", inline: true },
        { name: "XP tiếp theo", value: "{next_level_xp}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎉 Level Up {level}!",
      description: "Congratulations {user.mention} on reaching **Level {level}**!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "Keep chatting to level up!", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Current XP", value: "{current_xp}", inline: true },
        { name: "Next Level XP", value: "{next_level_xp}", inline: true },
      ],
      enabled: true,
    },
  },
  level_reward: {
    vi: {
      title: "🎁 Level Reward",
      description: "{user.mention} đã nhận reward **{reward.role}** ở Level {level}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎁 Level Reward",
      description: "{user.mention} received the **{reward.role}** reward at Level {level}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  leaderboard: {
    vi: {
      title: "🏆 Bảng xếp hạng XP",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "Cập nhật: {updated_at}", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 XP Leaderboard",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "Updated: {updated_at}", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_menu: {
    vi: {
      title: "📋 Trợ giúp — {bot_name}",
      description: "Xin chào {user.mention}!\nChọn **danh mục** bên dưới để xem danh sách lệnh.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Chọn danh mục để tiếp tục", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📋 Help — {bot_name}",
      description: "Hello {user.mention}!\nSelect a **category** below to view the command list.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a category to continue", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_category: {
    vi: {
      title: "{category_emoji} {category_name}",
      description: "Danh sách lệnh trong **{category_name}**:\n{commands_list}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Chọn lệnh để xem chi tiết", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "{category_emoji} {category_name}",
      description: "Commands in **{category_name}**:\n{commands_list}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a command for details", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_command: {
    vi: {
      title: "{command_emoji} `/{command_name}`",
      description: "{command_desc}",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "{bot_name}", thumbnail_url: "", image_url: "",
      fields: [{ name: "📌 Cách dùng", value: "{command_usage}", inline: false }],
      enabled: true,
    },
    en: {
      title: "{command_emoji} `/{command_name}`",
      description: "{command_desc}",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "{bot_name}", thumbnail_url: "", image_url: "",
      fields: [{ name: "📌 Usage", value: "{command_usage}", inline: false }],
      enabled: true,
    },
  },
  // ── Tương tác — Có mục tiêu ──
  interact_airkiss: {
    vi: {
      title: "😘 Airkiss!",
      description: "{user.mention} gửi nụ hôn gió cho {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😘 Airkiss!",
      description: "{user.mention} blows a kiss at {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_angrystare: {
    vi: {
      title: "😠 Angry Stare!",
      description: "{user.mention} nhìn giận dữ {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😠 Angry Stare!",
      description: "{user.mention} stares angrily at {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_bite: {
    vi: {
      title: "😬 Bite!",
      description: "{user.mention} cắn {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😬 Bite!",
      description: "{user.mention} bites {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_brofist: {
    vi: {
      title: "🤜 Brofist!",
      description: "{user.mention} đấm tay với {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤜 Brofist!",
      description: "{user.mention} fist-bumps {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cuddle: {
    vi: {
      title: "🤗 Cuddle!",
      description: "{user.mention} ôm ấp {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤗 Cuddle!",
      description: "{user.mention} cuddles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_handhold: {
    vi: {
      title: "🤝 Handhold!",
      description: "{user.mention} nắm tay {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤝 Handhold!",
      description: "{user.mention} holds hands with {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_hug: {
    vi: {
      title: "🫂 Hug!",
      description: "{user.mention} ôm {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫂 Hug!",
      description: "{user.mention} hugs {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_kiss: {
    vi: {
      title: "💋 Kiss!",
      description: "{user.mention} hôn {target.mention}",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💋 Kiss!",
      description: "{user.mention} kisses {target.mention}",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_lick: {
    vi: {
      title: "👅 Lick!",
      description: "{user.mention} liếm {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👅 Lick!",
      description: "{user.mention} licks {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nom: {
    vi: {
      title: "😋 Nom!",
      description: "{user.mention} ăn {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😋 Nom!",
      description: "{user.mention} noms on {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nuzzle: {
    vi: {
      title: "🥰 Nuzzle!",
      description: "{user.mention} cọ mũi với {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥰 Nuzzle!",
      description: "{user.mention} nuzzles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pat: {
    vi: {
      title: "🤚 Pat!",
      description: "{user.mention} xoa đầu {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤚 Pat!",
      description: "{user.mention} pats {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pinch: {
    vi: {
      title: "🤏 Pinch!",
      description: "{user.mention} véo {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤏 Pinch!",
      description: "{user.mention} pinches {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_poke: {
    vi: {
      title: "👉 Poke!",
      description: "{user.mention} chọc {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👉 Poke!",
      description: "{user.mention} pokes {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_punch: {
    vi: {
      title: "👊 Punch!",
      description: "{user.mention} đấm {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👊 Punch!",
      description: "{user.mention} punches {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_slap: {
    vi: {
      title: "🫲 Slap!",
      description: "{user.mention} tát {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫲 Slap!",
      description: "{user.mention} slaps {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smack: {
    vi: {
      title: "💥 Smack!",
      description: "{user.mention} đánh {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💥 Smack!",
      description: "{user.mention} smacks {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_tickle: {
    vi: {
      title: "🤭 Tickle!",
      description: "{user.mention} cù {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤭 Tickle!",
      description: "{user.mention} tickles {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_wave: {
    vi: {
      title: "👋 Wave!",
      description: "{user.mention} vẫy tay với {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👋 Wave!",
      description: "{user.mention} waves at {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_wink: {
    vi: {
      title: "😉 Wink!",
      description: "{user.mention} nháy mắt với {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😉 Wink!",
      description: "{user.mention} winks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_stare: {
    vi: {
      title: "👀 Stare!",
      description: "{user.mention} nhìn chằm chằm {target.mention}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👀 Stare!",
      description: "{user.mention} stares at {target.mention}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_peek: {
    vi: {
      title: "🫣 Peek!",
      description: "{user.mention} nhìn trộm {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫣 Peek!",
      description: "{user.mention} peeks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  // ── Tương tác — Biểu cảm ──
  interact_bleh: {
    vi: {
      title: "😝 Bleh!",
      description: "{user.mention} le lưỡi",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😝 Bleh!",
      description: "{user.mention} sticks their tongue out",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_blush: {
    vi: {
      title: "😊 Blush!",
      description: "{user.mention} đỏ mặt",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😊 Blush!",
      description: "{user.mention} blushes",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_celebrate: {
    vi: {
      title: "🎉 Celebrate!",
      description: "{user.mention} ăn mừng",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎉 Celebrate!",
      description: "{user.mention} celebrates",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cheers: {
    vi: {
      title: "🍻 Cheers!",
      description: "{user.mention} nâng ly",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🍻 Cheers!",
      description: "{user.mention} cheers",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_clap: {
    vi: {
      title: "👏 Clap!",
      description: "{user.mention} vỗ tay",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👏 Clap!",
      description: "{user.mention} claps",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_confused: {
    vi: {
      title: "😕 Confused!",
      description: "{user.mention} bối rối",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😕 Confused!",
      description: "{user.mention} is confused",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cool: {
    vi: {
      title: "😎 Cool!",
      description: "{user.mention} ngầu",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😎 Cool!",
      description: "{user.mention} looks cool",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cry: {
    vi: {
      title: "😢 Cry!",
      description: "{user.mention} khóc",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😢 Cry!",
      description: "{user.mention} cries",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_dance: {
    vi: {
      title: "💃 Dance!",
      description: "{user.mention} nhảy",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💃 Dance!",
      description: "{user.mention} dances",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_drool: {
    vi: {
      title: "🤤 Drool!",
      description: "{user.mention} chảy nước miếng",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤤 Drool!",
      description: "{user.mention} drools",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_evillaugh: {
    vi: {
      title: "😈 Evil Laugh!",
      description: "{user.mention} cười ác",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😈 Evil Laugh!",
      description: "{user.mention} laughs evilly",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_facepalm: {
    vi: {
      title: "🤦 Facepalm!",
      description: "{user.mention} facepalm",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤦 Facepalm!",
      description: "{user.mention} facepalms",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_happy: {
    vi: {
      title: "😄 Happy!",
      description: "{user.mention} vui vẻ",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😄 Happy!",
      description: "{user.mention} is happy",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_headbang: {
    vi: {
      title: "🤘 Headbang!",
      description: "{user.mention} headbang",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤘 Headbang!",
      description: "{user.mention} headbangs",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_huh: {
    vi: {
      title: "❓ Huh?",
      description: "{user.mention} hả?",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "❓ Huh?",
      description: "{user.mention} is confused — huh?",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_laugh: {
    vi: {
      title: "😂 Laugh!",
      description: "{user.mention} cười",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😂 Laugh!",
      description: "{user.mention} laughs",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_love: {
    vi: {
      title: "❤️ Love!",
      description: "{user.mention} yêu",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "❤️ Love!",
      description: "{user.mention} is feeling love",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_mad: {
    vi: {
      title: "😡 Mad!",
      description: "{user.mention} giận dữ",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😡 Mad!",
      description: "{user.mention} is angry",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nervous: {
    vi: {
      title: "😰 Nervous!",
      description: "{user.mention} lo lắng",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😰 Nervous!",
      description: "{user.mention} is nervous",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_no: {
    vi: {
      title: "🙅 No!",
      description: "{user.mention} lắc đầu",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙅 No!",
      description: "{user.mention} shakes their head",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nosebleed: {
    vi: {
      title: "🫠 Nosebleed!",
      description: "{user.mention} chảy máu mũi",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫠 Nosebleed!",
      description: "{user.mention} gets a nosebleed",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nyah: {
    vi: {
      title: "😜 Nyah~",
      description: "{user.mention} nyah~",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😜 Nyah~",
      description: "{user.mention} says nyah~",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pout: {
    vi: {
      title: "😤 Pout!",
      description: "{user.mention} phụng phịu",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😤 Pout!",
      description: "{user.mention} pouts",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_roll: {
    vi: {
      title: "🙄 Roll!",
      description: "{user.mention} lăn",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙄 Roll!",
      description: "{user.mention} rolls their eyes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_run: {
    vi: {
      title: "🏃 Run!",
      description: "{user.mention} chạy",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏃 Run!",
      description: "{user.mention} runs",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sad: {
    vi: {
      title: "😞 Sad!",
      description: "{user.mention} buồn",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😞 Sad!",
      description: "{user.mention} is sad",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_scared: {
    vi: {
      title: "😱 Scared!",
      description: "{user.mention} sợ hãi",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😱 Scared!",
      description: "{user.mention} is scared",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shout: {
    vi: {
      title: "📢 Shout!",
      description: "{user.mention} hét",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📢 Shout!",
      description: "{user.mention} shouts",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shrug: {
    vi: {
      title: "🤷 Shrug!",
      description: "{user.mention} nhún vai",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤷 Shrug!",
      description: "{user.mention} shrugs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shy: {
    vi: {
      title: "🙈 Shy!",
      description: "{user.mention} ngại ngùng",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙈 Shy!",
      description: "{user.mention} is shy",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sigh: {
    vi: {
      title: "😮‍💨 Sigh!",
      description: "{user.mention} thở dài",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😮‍💨 Sigh!",
      description: "{user.mention} sighs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sip: {
    vi: {
      title: "🍵 Sip!",
      description: "{user.mention} nhâm nhi",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🍵 Sip!",
      description: "{user.mention} takes a sip",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sleep: {
    vi: {
      title: "😴 Sleep!",
      description: "{user.mention} ngủ",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😴 Sleep!",
      description: "{user.mention} falls asleep",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_slowclap: {
    vi: {
      title: "👏 Slow Clap!",
      description: "{user.mention} vỗ tay chậm",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👏 Slow Clap!",
      description: "{user.mention} slow claps",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smile: {
    vi: {
      title: "😊 Smile!",
      description: "{user.mention} cười",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😊 Smile!",
      description: "{user.mention} smiles",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smug: {
    vi: {
      title: "😏 Smug!",
      description: "{user.mention} tự mãn",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😏 Smug!",
      description: "{user.mention} looks smug",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sneeze: {
    vi: {
      title: "🤧 Sneeze!",
      description: "{user.mention} hắt xì",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤧 Sneeze!",
      description: "{user.mention} sneezes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sorry: {
    vi: {
      title: "🙏 Sorry!",
      description: "{user.mention} xin lỗi",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙏 Sorry!",
      description: "{user.mention} apologizes",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_stop: {
    vi: {
      title: "🛑 Stop!",
      description: "{user.mention} dừng lại",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🛑 Stop!",
      description: "{user.mention} says stop",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_surprised: {
    vi: {
      title: "😲 Surprised!",
      description: "{user.mention} ngạc nhiên",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😲 Surprised!",
      description: "{user.mention} is surprised",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sweat: {
    vi: {
      title: "😓 Sweat!",
      description: "{user.mention} toát mồ hôi",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😓 Sweat!",
      description: "{user.mention} sweats",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_thumbsup: {
    vi: {
      title: "👍 Thumbs Up!",
      description: "{user.mention} thích",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👍 Thumbs Up!",
      description: "{user.mention} gives a thumbs up",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_tired: {
    vi: {
      title: "😩 Tired!",
      description: "{user.mention} mệt",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😩 Tired!",
      description: "{user.mention} is tired",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_woah: {
    vi: {
      title: "😮 Woah!",
      description: "{user.mention} woah",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😮 Woah!",
      description: "{user.mention} says woah",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yawn: {
    vi: {
      title: "🥱 Yawn!",
      description: "{user.mention} ngáp",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥱 Yawn!",
      description: "{user.mention} yawns",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yay: {
    vi: {
      title: "🥳 Yay!",
      description: "{user.mention} yay!",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥳 Yay!",
      description: "{user.mention} says yay!",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yes: {
    vi: {
      title: "✅ Yes!",
      description: "{user.mention} gật đầu",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "✅ Yes!",
      description: "{user.mention} nods",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  // ── Đơn hàng (bổ sung) ──
  thanh_toan: {
    vi: {
      title: "✅ Thanh toán thành công",
      description: "Cảm ơn {user.mention}! Đơn hàng #{order.id} đã được thanh toán.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Sản phẩm", value: "{product.name}", inline: true },
        { name: "💰 Số tiền", value: "{order.total} VNĐ", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "✅ Payment Successful",
      description: "Thank you {user.mention}! Order #{order.id} has been paid.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Amount", value: "{order.total} VNĐ", inline: true },
      ],
      enabled: true,
    },
  },
  giao_hang: {
    vi: {
      title: "📦 Đơn hàng đã được giao",
      description: "Đơn hàng #{order.id} của bạn đã được giao thành công!",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Sản phẩm", value: "{product.name}", inline: true },
        { name: "👤 Khách hàng", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📦 Order Delivered",
      description: "Your order #{order.id} has been delivered successfully!",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "👤 Customer", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
  },
  don_hang_chi_tiet: {
    vi: {
      title: "📋 Chi tiết đơn hàng #{order.id}",
      description: "",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Khách hàng", value: "{user.mention}", inline: true },
        { name: "📦 Sản phẩm", value: "{product.name}", inline: true },
        { name: "💰 Tổng tiền", value: "{order.total} VNĐ", inline: true },
        { name: "📋 Trạng thái", value: "{order.status}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📋 Order Details #{order.id}",
      description: "",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Customer", value: "{user.mention}", inline: true },
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Total", value: "{order.total} VNĐ", inline: true },
        { name: "📋 Status", value: "{order.status}", inline: true },
      ],
      enabled: true,
    },
  },
  coupon: {
    vi: {
      title: "🏷️ Mã giảm giá",
      description: "Mã **{coupon.code}** đã được áp dụng!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "💸 Giảm", value: "{coupon.discount}", inline: true },
        { name: "📅 Hết hạn", value: "{coupon.expires_at}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🏷️ Coupon Applied",
      description: "Code **{coupon.code}** has been applied!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "💸 Discount", value: "{coupon.discount}", inline: true },
        { name: "📅 Expires", value: "{coupon.expires_at}", inline: true },
      ],
      enabled: true,
    },
  },
  ban_shop: {
    vi: {
      title: "🚫 Cấm mua hàng",
      description: "{user.mention} đã bị cấm mua hàng.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Lý do", value: "{reason}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🚫 Shop Banned",
      description: "{user.mention} has been banned from shopping.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
  },
  unban_shop: {
    vi: {
      title: "✅ Bỏ cấm mua hàng",
      description: "{user.mention} đã được bỏ cấm mua hàng.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Người thực hiện", value: "{mod}", inline: true }],
      enabled: true,
    },
    en: {
      title: "✅ Shop Unbanned",
      description: "{user.mention} has been unbanned from shopping.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Moderator", value: "{mod}", inline: true }],
      enabled: true,
    },
  },
  // ── Ticket (bổ sung) ──
  ticket_transcript: {
    vi: {
      title: "📄 Transcript Ticket",
      description: "Transcript của ticket **#{ticket.id}** đã được lưu.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Tạo bởi", value: "{user.name}", inline: true },
        { name: "📝 Số tin nhắn", value: "{message_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📄 Ticket Transcript",
      description: "Transcript for ticket **#{ticket.id}** has been saved.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Created by", value: "{user.name}", inline: true },
        { name: "📝 Messages", value: "{message_count}", inline: true },
      ],
      enabled: true,
    },
  },
  ticket_feedback: {
    vi: {
      title: "⭐ Đánh giá hỗ trợ",
      description: "Ticket **#{ticket.id}** đã được đóng.\nVui lòng đánh giá chất lượng hỗ trợ!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Staff", value: "{staff.mention}", inline: true }],
      enabled: true,
    },
    en: {
      title: "⭐ Support Feedback",
      description: "Ticket **#{ticket.id}** has been closed.\nPlease rate the quality of support!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Staff", value: "{staff.mention}", inline: true }],
      enabled: true,
    },
  },
  // ── Kiểm duyệt (bổ sung) ──
  timeout: {
    vi: {
      title: "⏱️ Bị timeout",
      description: "{user.mention} đã bị timeout trong server **{server}**.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "Hãy tuân thủ nội quy server", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Thời gian", value: "{duration}", inline: true },
        { name: "📋 Lý do", value: "{reason}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "⏱️ Timed Out",
      description: "{user.mention} has been timed out in **{server}**.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "Please follow the server rules", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Duration", value: "{duration}", inline: true },
        { name: "📋 Reason", value: "{reason}", inline: true },
      ],
      enabled: true,
    },
  },
  // ── Cộng đồng (bổ sung) ──
  invite_join: {
    vi: {
      title: "🎉 Thành viên mới từ invite",
      description: "{user.mention} đã tham gia qua link của **{inviter}**!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🔗 Code invite", value: "{invite_code}", inline: true },
        { name: "📊 Tổng invite", value: "{invite.count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎉 New Member via Invite",
      description: "{user.mention} joined via **{inviter}**'s invite!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🔗 Invite Code", value: "{invite_code}", inline: true },
        { name: "📊 Total Invites", value: "{invite.count}", inline: true },
      ],
      enabled: true,
    },
  },
  invite_leaderboard: {
    vi: {
      title: "🏆 Bảng xếp hạng Invite",
      description: "Top thành viên có nhiều lượt invite nhất trong **{server}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🥇 Top 1", value: "{top1}", inline: false },
        { name: "🥈 Top 2", value: "{top2}", inline: false },
        { name: "🥉 Top 3", value: "{top3}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "🏆 Invite Leaderboard",
      description: "Top members with the most invites in **{server}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🥇 Top 1", value: "{top1}", inline: false },
        { name: "🥈 Top 2", value: "{top2}", inline: false },
        { name: "🥉 Top 3", value: "{top3}", inline: false },
      ],
      enabled: true,
    },
  },
  giveaway_banned: {
    vi: {
      title: "⛔ Cấm tham gia Giveaway",
      description: "{user.mention} đã bị cấm tham gia giveaway.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Lý do", value: "{reason}", inline: false }],
      enabled: true,
    },
    en: {
      title: "⛔ Giveaway Banned",
      description: "{user.mention} has been banned from participating in giveaways.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
  },
  // ── Tiện ích (bổ sung) ──
  sticky_message: {
    vi: {
      title: "{sticky.title}",
      description: "{sticky.content}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Sticky Message", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "{sticky.title}",
      description: "{sticky.content}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Sticky Message", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
};
