import type { EmbedTemplate } from "./embedTypes";

type EmbedLang = Omit<EmbedTemplate, "id" | "event_type" | "name">;

export const DEFAULTS: Record<string, { vi: EmbedLang; en: EmbedLang }> = {
  don_hang_moi: {
    vi: {
      title: "New Order",
      description: "Please complete payment to finalize your order.\nExpires in 15 minutes.",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Awaiting payment...",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Order ID", value: "#{order.id}", inline: true },
        { name: "Customer", value: "{user.mention}", inline: true },
        { name: "Product", value: "{product.name}", inline: false },
        { name: "Amount", value: "{order.total} VND", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "New Order",
      description: "Please complete payment to finalize your order.\nExpires in 15 minutes.",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Awaiting payment...",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Order ID", value: "#{order.id}", inline: true },
        { name: "Customer", value: "{user.mention}", inline: true },
        { name: "Product", value: "{product.name}", inline: false },
        { name: "Amount", value: "{order.total} VND", inline: true },
      ],
      enabled: true,
    },
  },
  don_hang_het_han: {
    vi: {
      title: "Order Expired",
      description: "Your order #{order.id} has expired due to non-payment after 15 minutes.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "Create a new order to continue shopping.",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Product", value: "{product.name}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Order Expired",
      description: "Your order #{order.id} has expired due to non-payment after 15 minutes.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "Create a new order to continue shopping.",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Product", value: "{product.name}", inline: true },
      ],
      enabled: true,
    },
  },
  ghi_chu_don_hang: {
    vi: {
      title: "📝 Order Note",
      description: "Order #{order.id} by {user.mention} has been updated with a note.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Infinity Mall",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "📝 Note", value: "{note}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "📝 Order Note",
      description: "Order #{order.id} by {user.mention} has been updated with a note.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Infinity Mall",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "📝 Note", value: "{note}", inline: false },
      ],
      enabled: true,
    },
  },
  bang_gia: {
    vi: {
      title: "🛒 Product Price List",
      description: "Select a product from the menu below to view details and package prices.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Click a product name below for details",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🛒 Product Price List",
      description: "Select a product from the menu below to view details and package prices.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Click a product name below for details",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  san_pham: {
    vi: {
      title: "🛍️ {product.name}",
      description: "{product.description}",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Product currently on sale",
      thumbnail_url: "{product.image_url}",
      image_url: "",
      fields: [
        { name: "💰 Price", value: "{product.price} VND", inline: true },
        { name: "📦 Stock", value: "{product.stock}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🛍️ {product.name}",
      description: "{product.description}",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Product currently on sale",
      thumbnail_url: "{product.image_url}",
      image_url: "",
      fields: [
        { name: "💰 Price", value: "{product.price} VND", inline: true },
        { name: "📦 Stock", value: "{product.stock}", inline: true },
      ],
      enabled: true,
    },
  },

  san_pham_detail: {
    vi: {
      title: "📦 {product.name}",
      description: "{product.description}",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "Contact admin to place an order",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "🔹 {package.name}", value: "💰 **{package.price}VND**\n{package.description}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "📦 {product.name}",
      description: "{product.description}",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "Contact admin to place an order",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "🔹 {package.name}", value: "💰 **{package.price}VND**\n{package.description}", inline: false },
      ],
      enabled: true,
    },
  },
  feedback: {
    vi: {
      title: "New Feedback",
      description: "{user} submitted a review for {product.name}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Feedback system",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Rating", value: "{stars}", inline: true },
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "New Feedback",
      description: "{user} submitted a review for {product.name}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Feedback system",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Rating", value: "{stars}", inline: true },
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
  },
  giveaway: {
    vi: {
      title: "GIVEAWAY",
      description: "{prize}\n\nPress the button below to enter!\nEnds: {ends_at}",
      color: "#FF73FA",
      author: "Hosted by {host}",
      author_icon_url: "",
      footer: "Ends at {ends_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "GIVEAWAY",
      description: "{prize}\n\nPress the button below to enter!\nEnds: {ends_at}",
      color: "#FF73FA",
      author: "Hosted by {host}",
      author_icon_url: "",
      footer: "Ends at {ends_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners_count}", inline: true },
      ],
      enabled: true,
    },
  },
  ket_qua_giveaway: {
    vi: {
      title: "Giveaway Results",
      description: "The giveaway has ended!\nPrize: {prize}",
      color: "#FF73FA",
      author: "",
      author_icon_url: "",
      footer: "Congratulations to the winners!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "Giveaway Results",
      description: "The giveaway has ended!\nPrize: {prize}",
      color: "#FF73FA",
      author: "",
      author_icon_url: "",
      footer: "Congratulations to the winners!",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Winners", value: "{winners}", inline: false },
      ],
      enabled: true,
    },
  },

  reaction_role_panel: {
    vi: {
      title: "🎭 Reaction Role",
      description: "Choose the role you want by reacting below!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "React to get a role • Remove reaction to remove role",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎭 Reaction Role",
      description: "Choose the role you want by reacting below!",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "React to get a role • Remove reaction to remove role",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  starboard_post: {
    vi: {
      title: "⭐ Starboard",
      description: "{user.mention} received ⭐ **{star_count}** stars in {channel}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Starboard",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "⭐ Starboard",
      description: "{user.mention} received ⭐ **{star_count}** stars in {channel}",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Starboard",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Content", value: "{content}", inline: false },
      ],
      enabled: true,
    },
  },
  canh_bao: {
    vi: {
      title: "Warning",
      description: "{user.mention} has received a warning.",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Please follow the server rules",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Total Warnings", value: "{warn_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Warning",
      description: "{user.mention} has received a warning.",
      color: "#FEE75C",
      author: "",
      author_icon_url: "",
      footer: "Please follow the server rules",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Total Warnings", value: "{warn_count}", inline: true },
      ],
      enabled: true,
    },
  },

  kick: {
    vi: {
      title: "👢 Kicked from Server",
      description: "{user.mention} has been kicked from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "👢 Kicked from Server",
      description: "{user.mention} has been kicked from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
  },
  ban: {
    vi: {
      title: "🔨 Permanently Banned",
      description: "{user.mention} has been banned from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🔨 Permanently Banned",
      description: "{user.mention} has been banned from the server.",
      color: "#ED4245",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod}", inline: true },
      ],
      enabled: true,
    },
  },
  qr_thanh_toan: {
    vi: {
      title: "💳 Payment for Order #{order.id}",
      description: "Scan the QR code below to pay.\nYour order will expire in **15 minutes**.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Scan QR with your banking app",
      thumbnail_url: "",
      image_url: "{qr_url}",
      fields: [
        { name: "Amount", value: "{order.total} VND", inline: true },
        { name: "Transfer Content", value: "{transfer_content}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "💳 Payment for Order #{order.id}",
      description: "Scan the QR code below to pay.\nYour order will expire in **15 minutes**.",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Scan QR with your banking app",
      thumbnail_url: "",
      image_url: "{qr_url}",
      fields: [
        { name: "Amount", value: "{order.total} VND", inline: true },
        { name: "Transfer Note", value: "{transfer_content}", inline: true },
      ],
      enabled: true,
    },
  },
  qr_thanh_toan_payos: {
    vi: {
      title: "💳 Payment — PayOS",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Click to pay]({qr_url})",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Scan QR with your banking app",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Transfer Content", value: "{transfer_content}", inline: true },
        { name: "Expires", value: "15 minutes", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "💳 Payment — PayOS",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Click to pay]({qr_url})",
      color: "#5865F2",
      author: "",
      author_icon_url: "",
      footer: "Scan QR with your banking app",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Transfer Content", value: "{transfer_content}", inline: true },
        { name: "Expires", value: "15 minutes", inline: true },
      ],
      enabled: true,
    },
  },
  qr_thanh_toan_paypal: {
    vi: {
      title: "💳 Payment — PayPal",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Pay with PayPal]({qr_url})",
      color: "#0070BA",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💳 Payment — PayPal",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Pay with PayPal]({qr_url})",
      color: "#0070BA",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  qr_thanh_toan_crypto: {
    vi: {
      title: "💳 Payment — Crypto",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Pay with Crypto]({qr_url})",
      color: "#F7931A",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💳 Payment — Crypto",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n[Pay with Crypto]({qr_url})",
      color: "#F7931A",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  qr_thanh_toan_manual: {
    vi: {
      title: "💳 Manual Payment",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n**Bank:** {bank_name}\n**Account:** {account_holder}\n**Number:** {account_number}\n**Transfer content:** {transfer_content}\n\n{instructions}",
      color: "#10B981",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💳 Manual Payment",
      description: "Order **#{order.id}**\nAmount: **{order.total}**\n\n**Bank:** {bank_name}\n**Account:** {account_holder}\n**Number:** {account_number}\n**Transfer content:** {transfer_content}\n\n{instructions}",
      color: "#10B981",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  bxh_chi_tieu: {
    vi: {
      title: "🏆 Spending Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 Spending Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  bxh_don_hang: {
    vi: {
      title: "🏆 Orders Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 Orders Leaderboard — {time_label}",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "",
      author_icon_url: "",
      footer: "Updated: {updated_at}",
      thumbnail_url: "",
      image_url: "",
      fields: [],
      enabled: true,
    },
  },
  unban: {
    vi: {
      title: "🔓 Member Unbanned",
      description: "{user.mention} has been unbanned.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Moderator", value: "{moderator}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🔓 Member Unbanned",
      description: "{user.mention} has been unbanned.",
      color: "#57F287",
      author: "",
      author_icon_url: "",
      footer: "",
      thumbnail_url: "",
      image_url: "",
      fields: [
        { name: "Moderator", value: "{moderator}", inline: true },
      ],
      enabled: true,
    },
  },


  log_message_delete: {
    vi: {
      title: "🗑️ Message Deleted",
      description: "A message by {user.mention} in {channel} has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🗑️ Message Deleted",
      description: "A message by {user.mention} in {channel} has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
  },
  log_message_edit: {
    vi: {
      title: "✏️ Message Edited",
      description: "{user.mention} edited a message in {channel}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: false },
        { name: "After", value: "{after}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "✏️ Message Edited",
      description: "{user.mention} edited a message in {channel}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: false },
        { name: "After", value: "{after}", inline: false },
      ],
      enabled: true,
    },
  },
  log_message_bulk_delete: {
    vi: {
      title: "🗑️ Bulk Delete",
      description: "**{count}** messages were deleted in {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🗑️ Bulk Delete",
      description: "**{count}** messages were deleted in {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_join: {
    vi: {
      title: "🔊 Joined Voice",
      description: "{user.mention} joined {channel}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔊 Joined Voice",
      description: "{user.mention} joined {channel}.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_leave: {
    vi: {
      title: "🔇 Left Voice",
      description: "{user.mention} left {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔇 Left Voice",
      description: "{user.mention} left {channel}.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_voice_move: {
    vi: {
      title: "🔀 Moved Voice",
      description: "{user.mention} moved from {from} to {to}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔀 Moved Voice",
      description: "{user.mention} moved from {from} to {to}.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_member_join: {
    vi: {
      title: "📥 New Member",
      description: "{user.mention} has joined the server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Account Age", value: "{account_age}", inline: true },
        { name: "Member #", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📥 New Member",
      description: "{user.mention} has joined the server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Account Age", value: "{account_age}", inline: true },
        { name: "Member #", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
  },
  log_member_leave: {
    vi: {
      title: "📤 Member Left",
      description: "{user.mention} has left the server.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Roles", value: "{roles}", inline: false },
        { name: "Remaining", value: "{member_count} members", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📤 Member Left",
      description: "{user.mention} has left the server.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Roles", value: "{roles}", inline: false },
        { name: "Remaining", value: "{member_count} members", inline: true },
      ],
      enabled: true,
    },
  },
  log_nickname_change: {
    vi: {
      title: "📝 Nickname Changed",
      description: "{user.mention} changed their nickname.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: true },
        { name: "After", value: "{after}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📝 Nickname Changed",
      description: "{user.mention} changed their nickname.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Before", value: "{before}", inline: true },
        { name: "After", value: "{after}", inline: true },
      ],
      enabled: true,
    },
  },
  log_role_update: {
    vi: {
      title: "🎭 Role Updated",
      description: "Roles for {user.mention} have been updated.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Changes", value: "{changes}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🎭 Role Updated",
      description: "Roles for {user.mention} have been updated.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Changes", value: "{changes}", inline: false }],
      enabled: true,
    },
  },
  log_channel_create: {
    vi: {
      title: "📺 Channel Created",
      description: "Channel {channel} ({type}) has been created.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📺 Channel Created",
      description: "Channel {channel} ({type}) has been created.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  log_channel_delete: {
    vi: {
      title: "📺 Channel Deleted",
      description: "Channel **{channel.name}** ({type}) has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📺 Channel Deleted",
      description: "Channel **{channel.name}** ({type}) has been deleted.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  // ── AutoMod ──
  automod_warn: {
    vi: {
      title: "⚠️ AutoMod — Warning",
      description: "{user.mention} has been warned by AutoMod.\n**Reason:** {reason}",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channel", value: "{channel}", inline: true }],
      enabled: true,
    },
    en: {
      title: "⚠️ AutoMod — Warning",
      description: "{user.mention} has been warned by AutoMod.\n**Reason:** {reason}",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channel", value: "{channel}", inline: true }],
      enabled: true,
    },
  },
  automod_mute: {
    vi: {
      title: "🔇 AutoMod — Mute",
      description: "{user.mention} has been muted by AutoMod.\n**Reason:** {reason}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Duration", value: "{duration}", inline: true }],
      enabled: true,
    },
    en: {
      title: "🔇 AutoMod — Mute",
      description: "{user.mention} has been muted by AutoMod.\n**Reason:** {reason}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Duration", value: "{duration}", inline: true }],
      enabled: true,
    },
  },
  automod_kick: {
    vi: {
      title: "👢 AutoMod — Kick",
      description: "{user.mention} has been kicked by AutoMod.\n**Reason:** {reason}",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👢 AutoMod — Kick",
      description: "{user.mention} has been kicked by AutoMod.\n**Reason:** {reason}",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  automod_delete: {
    vi: {
      title: "🗑️ AutoMod — Message Deleted",
      description: "A message by {user.mention} was deleted by AutoMod.\n**Reason:** {reason}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🗑️ AutoMod — Message Deleted",
      description: "A message by {user.mention} was deleted by AutoMod.\n**Reason:** {reason}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Content", value: "{content}", inline: false }],
      enabled: true,
    },
  },
  // ── AFK ──
  afk_set: {
    vi: {
      title: "💤 AFK",
      description: "{user.mention} is now AFK: **{reason}**",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💤 AFK",
      description: "{user.mention} is now AFK: **{reason}**",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  afk_return: {
    vi: {
      title: "👋 Welcome Back",
      description: "{user.mention} is back! (AFK {duration})",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👋 Welcome Back",
      description: "{user.mention} is back! (AFK {duration})",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },

  leaderboard: {
    vi: {
      title: "🏆 XP Leaderboard",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "Updated: {updated_at}", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏆 XP Leaderboard",
      description: "{leaderboard_lines}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "Updated: {updated_at}", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_menu: {
    vi: {
      title: "📋 Help — {bot_name}",
      description: "Hello {user.mention}!\nSelect a **category** below to view the command list.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a category to continue", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📋 Help — {bot_name}",
      description: "Hello {user.mention}!\nSelect a **category** below to view the command list.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a category to continue", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_category: {
    vi: {
      title: "{category_emoji} {category_name}",
      description: "Commands in **{category_name}**:\n{commands_list}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a command for details", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "{category_emoji} {category_name}",
      description: "Commands in **{category_name}**:\n{commands_list}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "{bot_name} • Select a command for details", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  help_command: {
    vi: {
      title: "{command_emoji} `/{command_name}`",
      description: "{command_desc}",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "{bot_name}", thumbnail_url: "", image_url: "",
      fields: [{ name: "📌 Usage", value: "{command_usage}", inline: false }],
      enabled: true,
    },
    en: {
      title: "{command_emoji} `/{command_name}`",
      description: "{command_desc}",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "{bot_name}", thumbnail_url: "", image_url: "",
      fields: [{ name: "📌 Usage", value: "{command_usage}", inline: false }],
      enabled: true,
    },
  },
  // ── Interactions — With Target ──
  interact_airkiss: {
    vi: {
      title: "😘 Airkiss!",
      description: "{user.mention} blows a kiss at {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😘 Airkiss!",
      description: "{user.mention} blows a kiss at {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_angrystare: {
    vi: {
      title: "😠 Angry Stare!",
      description: "{user.mention} stares angrily at {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😠 Angry Stare!",
      description: "{user.mention} stares angrily at {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_bite: {
    vi: {
      title: "😬 Bite!",
      description: "{user.mention} bites {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😬 Bite!",
      description: "{user.mention} bites {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_brofist: {
    vi: {
      title: "🤜 Brofist!",
      description: "{user.mention} fist-bumps {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤜 Brofist!",
      description: "{user.mention} fist-bumps {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cuddle: {
    vi: {
      title: "🤗 Cuddle!",
      description: "{user.mention} cuddles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤗 Cuddle!",
      description: "{user.mention} cuddles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_handhold: {
    vi: {
      title: "🤝 Handhold!",
      description: "{user.mention} holds hands with {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤝 Handhold!",
      description: "{user.mention} holds hands with {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_hug: {
    vi: {
      title: "🫂 Hug!",
      description: "{user.mention} hugs {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫂 Hug!",
      description: "{user.mention} hugs {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_kiss: {
    vi: {
      title: "💋 Kiss!",
      description: "{user.mention} kisses {target.mention}",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💋 Kiss!",
      description: "{user.mention} kisses {target.mention}",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_lick: {
    vi: {
      title: "👅 Lick!",
      description: "{user.mention} licks {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👅 Lick!",
      description: "{user.mention} licks {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nom: {
    vi: {
      title: "😋 Nom!",
      description: "{user.mention} noms on {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😋 Nom!",
      description: "{user.mention} noms on {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nuzzle: {
    vi: {
      title: "🥰 Nuzzle!",
      description: "{user.mention} nuzzles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥰 Nuzzle!",
      description: "{user.mention} nuzzles {target.mention}",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pat: {
    vi: {
      title: "🤚 Pat!",
      description: "{user.mention} pats {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤚 Pat!",
      description: "{user.mention} pats {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pinch: {
    vi: {
      title: "🤏 Pinch!",
      description: "{user.mention} pinches {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤏 Pinch!",
      description: "{user.mention} pinches {target.mention}",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_poke: {
    vi: {
      title: "👉 Poke!",
      description: "{user.mention} pokes {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👉 Poke!",
      description: "{user.mention} pokes {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_punch: {
    vi: {
      title: "👊 Punch!",
      description: "{user.mention} punches {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👊 Punch!",
      description: "{user.mention} punches {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_slap: {
    vi: {
      title: "🫲 Slap!",
      description: "{user.mention} slaps {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫲 Slap!",
      description: "{user.mention} slaps {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smack: {
    vi: {
      title: "💥 Smack!",
      description: "{user.mention} smacks {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💥 Smack!",
      description: "{user.mention} smacks {target.mention}",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_tickle: {
    vi: {
      title: "🤭 Tickle!",
      description: "{user.mention} tickles {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤭 Tickle!",
      description: "{user.mention} tickles {target.mention}",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_wave: {
    vi: {
      title: "👋 Wave!",
      description: "{user.mention} waves at {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👋 Wave!",
      description: "{user.mention} waves at {target.mention}",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_wink: {
    vi: {
      title: "😉 Wink!",
      description: "{user.mention} winks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😉 Wink!",
      description: "{user.mention} winks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_stare: {
    vi: {
      title: "👀 Stare!",
      description: "{user.mention} stares at {target.mention}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👀 Stare!",
      description: "{user.mention} stares at {target.mention}",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_peek: {
    vi: {
      title: "🫣 Peek!",
      description: "{user.mention} peeks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫣 Peek!",
      description: "{user.mention} peeks at {target.mention}",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  // ── Interactions — Expressions ──
  interact_bleh: {
    vi: {
      title: "😝 Bleh!",
      description: "{user.mention} sticks their tongue out",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😝 Bleh!",
      description: "{user.mention} sticks their tongue out",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_blush: {
    vi: {
      title: "😊 Blush!",
      description: "{user.mention} blushes",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😊 Blush!",
      description: "{user.mention} blushes",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_celebrate: {
    vi: {
      title: "🎉 Celebrate!",
      description: "{user.mention} celebrates",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🎉 Celebrate!",
      description: "{user.mention} celebrates",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cheers: {
    vi: {
      title: "🍻 Cheers!",
      description: "{user.mention} cheers",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🍻 Cheers!",
      description: "{user.mention} cheers",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_clap: {
    vi: {
      title: "👏 Clap!",
      description: "{user.mention} claps",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👏 Clap!",
      description: "{user.mention} claps",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_confused: {
    vi: {
      title: "😕 Confused!",
      description: "{user.mention} is confused",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😕 Confused!",
      description: "{user.mention} is confused",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cool: {
    vi: {
      title: "😎 Cool!",
      description: "{user.mention} looks cool",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😎 Cool!",
      description: "{user.mention} looks cool",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_cry: {
    vi: {
      title: "😢 Cry!",
      description: "{user.mention} cries",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😢 Cry!",
      description: "{user.mention} cries",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_dance: {
    vi: {
      title: "💃 Dance!",
      description: "{user.mention} dances",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "💃 Dance!",
      description: "{user.mention} dances",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_drool: {
    vi: {
      title: "🤤 Drool!",
      description: "{user.mention} drools",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤤 Drool!",
      description: "{user.mention} drools",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_evillaugh: {
    vi: {
      title: "😈 Evil Laugh!",
      description: "{user.mention} laughs evilly",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😈 Evil Laugh!",
      description: "{user.mention} laughs evilly",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_facepalm: {
    vi: {
      title: "🤦 Facepalm!",
      description: "{user.mention} facepalm",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤦 Facepalm!",
      description: "{user.mention} facepalms",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_happy: {
    vi: {
      title: "😄 Happy!",
      description: "{user.mention} is happy",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😄 Happy!",
      description: "{user.mention} is happy",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_headbang: {
    vi: {
      title: "🤘 Headbang!",
      description: "{user.mention} headbang",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤘 Headbang!",
      description: "{user.mention} headbangs",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_huh: {
    vi: {
      title: "❓ Huh?",
      description: "{user.mention} is confused — huh?",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "❓ Huh?",
      description: "{user.mention} is confused — huh?",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_laugh: {
    vi: {
      title: "😂 Laugh!",
      description: "{user.mention} laughs",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😂 Laugh!",
      description: "{user.mention} laughs",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_love: {
    vi: {
      title: "❤️ Love!",
      description: "{user.mention} is feeling love",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "❤️ Love!",
      description: "{user.mention} is feeling love",
      color: "#E91E63",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_mad: {
    vi: {
      title: "😡 Mad!",
      description: "{user.mention} is angry",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😡 Mad!",
      description: "{user.mention} is angry",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nervous: {
    vi: {
      title: "😰 Nervous!",
      description: "{user.mention} is nervous",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😰 Nervous!",
      description: "{user.mention} is nervous",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_no: {
    vi: {
      title: "🙅 No!",
      description: "{user.mention} shakes their head",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙅 No!",
      description: "{user.mention} shakes their head",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nosebleed: {
    vi: {
      title: "🫠 Nosebleed!",
      description: "{user.mention} gets a nosebleed",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🫠 Nosebleed!",
      description: "{user.mention} gets a nosebleed",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_nyah: {
    vi: {
      title: "😜 Nyah~",
      description: "{user.mention} nyah~",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😜 Nyah~",
      description: "{user.mention} says nyah~",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_pout: {
    vi: {
      title: "😤 Pout!",
      description: "{user.mention} pouts",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😤 Pout!",
      description: "{user.mention} pouts",
      color: "#E67E22",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_roll: {
    vi: {
      title: "🙄 Roll!",
      description: "{user.mention} rolls their eyes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙄 Roll!",
      description: "{user.mention} rolls their eyes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_run: {
    vi: {
      title: "🏃 Run!",
      description: "{user.mention} runs",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🏃 Run!",
      description: "{user.mention} runs",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sad: {
    vi: {
      title: "😞 Sad!",
      description: "{user.mention} is sad",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😞 Sad!",
      description: "{user.mention} is sad",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_scared: {
    vi: {
      title: "😱 Scared!",
      description: "{user.mention} is scared",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😱 Scared!",
      description: "{user.mention} is scared",
      color: "#8E44AD",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shout: {
    vi: {
      title: "📢 Shout!",
      description: "{user.mention} shouts",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "📢 Shout!",
      description: "{user.mention} shouts",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shrug: {
    vi: {
      title: "🤷 Shrug!",
      description: "{user.mention} shrugs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤷 Shrug!",
      description: "{user.mention} shrugs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_shy: {
    vi: {
      title: "🙈 Shy!",
      description: "{user.mention} is shy",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙈 Shy!",
      description: "{user.mention} is shy",
      color: "#FF69B4",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sigh: {
    vi: {
      title: "😮‍💨 Sigh!",
      description: "{user.mention} sighs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😮‍💨 Sigh!",
      description: "{user.mention} sighs",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sip: {
    vi: {
      title: "🍵 Sip!",
      description: "{user.mention} takes a sip",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🍵 Sip!",
      description: "{user.mention} takes a sip",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sleep: {
    vi: {
      title: "😴 Sleep!",
      description: "{user.mention} falls asleep",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😴 Sleep!",
      description: "{user.mention} falls asleep",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_slowclap: {
    vi: {
      title: "👏 Slow Clap!",
      description: "{user.mention} slow claps",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👏 Slow Clap!",
      description: "{user.mention} slow claps",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smile: {
    vi: {
      title: "😊 Smile!",
      description: "{user.mention} laughs",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😊 Smile!",
      description: "{user.mention} smiles",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_smug: {
    vi: {
      title: "😏 Smug!",
      description: "{user.mention} looks smug",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😏 Smug!",
      description: "{user.mention} looks smug",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sneeze: {
    vi: {
      title: "🤧 Sneeze!",
      description: "{user.mention} sneezes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🤧 Sneeze!",
      description: "{user.mention} sneezes",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sorry: {
    vi: {
      title: "🙏 Sorry!",
      description: "{user.mention} apologizes",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🙏 Sorry!",
      description: "{user.mention} apologizes",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_stop: {
    vi: {
      title: "🛑 Stop!",
      description: "{user.mention} says stop",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🛑 Stop!",
      description: "{user.mention} says stop",
      color: "#E74C3C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_surprised: {
    vi: {
      title: "😲 Surprised!",
      description: "{user.mention} is surprised",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😲 Surprised!",
      description: "{user.mention} is surprised",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_sweat: {
    vi: {
      title: "😓 Sweat!",
      description: "{user.mention} sweats",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😓 Sweat!",
      description: "{user.mention} sweats",
      color: "#3498DB",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_thumbsup: {
    vi: {
      title: "👍 Thumbs Up!",
      description: "{user.mention} gives a thumbs up",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "👍 Thumbs Up!",
      description: "{user.mention} gives a thumbs up",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_tired: {
    vi: {
      title: "😩 Tired!",
      description: "{user.mention} is tired",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😩 Tired!",
      description: "{user.mention} is tired",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_woah: {
    vi: {
      title: "😮 Woah!",
      description: "{user.mention} woah",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "😮 Woah!",
      description: "{user.mention} says woah",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yawn: {
    vi: {
      title: "🥱 Yawn!",
      description: "{user.mention} yawns",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥱 Yawn!",
      description: "{user.mention} yawns",
      color: "#95A5A6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yay: {
    vi: {
      title: "🥳 Yay!",
      description: "{user.mention} yay!",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🥳 Yay!",
      description: "{user.mention} says yay!",
      color: "#F1C40F",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  interact_yes: {
    vi: {
      title: "✅ Yes!",
      description: "{user.mention} nods",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
    en: {
      title: "✅ Yes!",
      description: "{user.mention} nods",
      color: "#2ECC71",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "",
      image_url: "{gif_url}",
      fields: [],
      enabled: true,
    },
  },
  // ── Orders (supplemental) ──
  thanh_toan: {
    vi: {
      title: "✅ Payment Successful",
      description: "Thank you {user.mention}! Order #{order.id} has been paid.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Amount", value: "{order.total} VND", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "✅ Payment Successful",
      description: "Thank you {user.mention}! Order #{order.id} has been paid.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Amount", value: "{order.total} VND", inline: true },
      ],
      enabled: true,
    },
  },
  giao_hang: {
    vi: {
      title: "📦 Order Delivered",
      description: "Your order #{order.id} has been delivered successfully!",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "👤 Customer", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📦 Order Delivered",
      description: "Your order #{order.id} has been delivered successfully!",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "👤 Customer", value: "{user.mention}", inline: true },
      ],
      enabled: true,
    },
  },
  don_hang_chi_tiet: {
    vi: {
      title: "📋 Order Details #{order.id}",
      description: "",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Customer", value: "{user.mention}", inline: true },
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Total", value: "{order.total} VND", inline: true },
        { name: "📋 Status", value: "{order.status}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "📋 Order Details #{order.id}",
      description: "",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 Customer", value: "{user.mention}", inline: true },
        { name: "📦 Product", value: "{product.name}", inline: true },
        { name: "💰 Total", value: "{order.total} VND", inline: true },
        { name: "📋 Status", value: "{order.status}", inline: true },
      ],
      enabled: true,
    },
  },
  coupon: {
    vi: {
      title: "🏷️ Coupon Applied",
      description: "Code **{coupon.code}** has been applied!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "💸 Discount", value: "{coupon.discount}", inline: true },
        { name: "📅 Expires", value: "{coupon.expires_at}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🏷️ Coupon Applied",
      description: "Code **{coupon.code}** has been applied!",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "💸 Discount", value: "{coupon.discount}", inline: true },
        { name: "📅 Expires", value: "{coupon.expires_at}", inline: true },
      ],
      enabled: true,
    },
  },
  ban_shop: {
    vi: {
      title: "🚫 Shop Banned",
      description: "{user.mention} has been banned from shopping.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
    en: {
      title: "🚫 Shop Banned",
      description: "{user.mention} has been banned from shopping.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
  },
  unban_shop: {
    vi: {
      title: "✅ Shop Unbanned",
      description: "{user.mention} has been unbanned from shopping.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Moderator", value: "{mod}", inline: true }],
      enabled: true,
    },
    en: {
      title: "✅ Shop Unbanned",
      description: "{user.mention} has been unbanned from shopping.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "👮 Moderator", value: "{mod}", inline: true }],
      enabled: true,
    },
  },
  // ── Moderation (supplemental) ──
  timeout: {
    vi: {
      title: "⏱️ Timed Out",
      description: "{user.mention} has been timed out in **{server}**.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "Please follow the server rules", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Duration", value: "{duration}", inline: true },
        { name: "📋 Reason", value: "{reason}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "⏱️ Timed Out",
      description: "{user.mention} has been timed out in **{server}**.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "Please follow the server rules", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Duration", value: "{duration}", inline: true },
        { name: "📋 Reason", value: "{reason}", inline: true },
      ],
      enabled: true,
    },
  },
  // ── Community (supplemental) ──
  invite_join: {
    vi: {
      title: "🎉 New Member via Invite",
      description: "{user.mention} joined via **{inviter}**'s invite!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🔗 Invite Code", value: "{invite_code}", inline: true },
        { name: "📊 Total Invites", value: "{invite.count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "🎉 New Member via Invite",
      description: "{user.mention} joined via **{inviter}**'s invite!",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🔗 Invite Code", value: "{invite_code}", inline: true },
        { name: "📊 Total Invites", value: "{invite.count}", inline: true },
      ],
      enabled: true,
    },
  },
  invite_leaderboard: {
    vi: {
      title: "🏆 Invite Leaderboard",
      description: "Top members with the most invites in **{server}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🥇 Top 1", value: "{top1}", inline: false },
        { name: "🥈 Top 2", value: "{top2}", inline: false },
        { name: "🥉 Top 3", value: "{top3}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "🏆 Invite Leaderboard",
      description: "Top members with the most invites in **{server}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "🥇 Top 1", value: "{top1}", inline: false },
        { name: "🥈 Top 2", value: "{top2}", inline: false },
        { name: "🥉 Top 3", value: "{top3}", inline: false },
      ],
      enabled: true,
    },
  },
  giveaway_banned: {
    vi: {
      title: "⛔ Giveaway Banned",
      description: "{user.mention} has been banned from participating in giveaways.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
    en: {
      title: "⛔ Giveaway Banned",
      description: "{user.mention} has been banned from participating in giveaways.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📋 Reason", value: "{reason}", inline: false }],
      enabled: true,
    },
  },
  // ── Utilities (supplemental) ──
  sticky_message: {
    vi: {
      title: "{sticky.title}",
      description: "{sticky.content}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Sticky Message", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "{sticky.title}",
      description: "{sticky.content}",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Sticky Message", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  // ── Extended Moderation ────────────────────────────────────────────────────
  softban: {
    vi: {
      title: "Softbanned",
      description: "{user.mention} has been softbanned from **{server}**.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "Softban — messages deleted", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod.name}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Softbanned",
      description: "{user.mention} has been softbanned from **{server}**.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "Softban — messages deleted", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod.name}", inline: true },
      ],
      enabled: true,
    },
  },
  mute: {
    vi: {
      title: "Muted",
      description: "{user.mention} has been muted in **{server}**.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Please follow the server rules", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Duration", value: "{duration}", inline: true },
        { name: "Reason", value: "{reason}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "Muted",
      description: "{user.mention} has been muted in **{server}**.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "Please follow server rules", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Duration", value: "{duration}", inline: true },
        { name: "Reason", value: "{reason}", inline: false },
      ],
      enabled: true,
    },
  },
  deafen: {
    vi: {
      title: "Deafened",
      description: "{user.mention} has been server deafened.",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod.name}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Deafened",
      description: "{user.mention} has been server deafened.",
      color: "#9B59B6",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Reason", value: "{reason}", inline: false },
        { name: "Mod", value: "{mod.name}", inline: true },
      ],
      enabled: true,
    },
  },
  rolepersist: {
    vi: {
      title: "Role Persist",
      description: "Role **{role.name}** has been persistently assigned to {user.mention}.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Mod", value: "{mod.name}", inline: true }],
      enabled: true,
    },
    en: {
      title: "Role Persist",
      description: "Role **{role.name}** has been persistently assigned to {user.mention}.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Mod", value: "{mod.name}", inline: true }],
      enabled: true,
    },
  },
  temprole: {
    vi: {
      title: "Temporary Role",
      description: "Role **{role.name}** assigned to {user.mention} for **{duration}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Mod", value: "{mod.name}", inline: true },
        { name: "Expires", value: "{expires_at}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "Temporary Role",
      description: "Role **{role.name}** assigned to {user.mention} for **{duration}**.",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "Mod", value: "{mod.name}", inline: true },
        { name: "Expires", value: "{expires_at}", inline: true },
      ],
      enabled: true,
    },
  },
  lockdown_start: {
    vi: {
      title: "Lockdown",
      description: "Server **{server}** is now in lockdown mode.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channels Locked", value: "{count}", inline: true }],
      enabled: true,
    },
    en: {
      title: "Lockdown",
      description: "Server **{server}** is now in lockdown mode.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channels Locked", value: "{count}", inline: true }],
      enabled: true,
    },
  },
  lockdown_end: {
    vi: {
      title: "Lockdown Ended",
      description: "Server **{server}** lockdown has been lifted.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channels Unlocked", value: "{count}", inline: true }],
      enabled: true,
    },
    en: {
      title: "Lockdown Ended",
      description: "Server **{server}** lockdown has been lifted.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "Channels Unlocked", value: "{count}", inline: true }],
      enabled: true,
    },
  },
  // ── Security & Recovery ──
  verification_log: {
    vi: {
      title: "✅ Verification Successful",
      description: "{user.mention} has been verified successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 User", value: "{user.tag}", inline: true },
        { name: "📧 Email", value: "{email}", inline: true },
        { name: "🌐 IP", value: "{ip}", inline: true },
        { name: "⚠️ Risk Score", value: "{risk_score}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "✅ Verification Successful",
      description: "{user.mention} has been verified successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 User", value: "{user.tag}", inline: true },
        { name: "📧 Email", value: "{email}", inline: true },
        { name: "🌐 IP", value: "{ip}", inline: true },
        { name: "⚠️ Risk Score", value: "{risk_score}", inline: true },
      ],
      enabled: true,
    },
  },
  verification_denied: {
    vi: {
      title: "❌ Verification Denied",
      description: "A user was denied verification.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 User", value: "{user.tag}", inline: true },
        { name: "📝 Reason", value: "{reason}", inline: false },
      ],
      enabled: true,
    },
    en: {
      title: "❌ Verification Denied",
      description: "A user was denied verification.",
      color: "#ED4245",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "👤 User", value: "{user.tag}", inline: true },
        { name: "📝 Reason", value: "{reason}", inline: false },
      ],
      enabled: true,
    },
  },
  backup_completed: {
    vi: {
      title: "✅ Backup Completed",
      description: "Server backup completed successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📋 Type", value: "{backup_type}", inline: true },
        { name: "📁 Channels", value: "{channel_count}", inline: true },
        { name: "🎭 Roles", value: "{role_count}", inline: true },
        { name: "👥 Members", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "✅ Backup Completed",
      description: "Server backup completed successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📋 Type", value: "{backup_type}", inline: true },
        { name: "📁 Channels", value: "{channel_count}", inline: true },
        { name: "🎭 Roles", value: "{role_count}", inline: true },
        { name: "👥 Members", value: "{member_count}", inline: true },
      ],
      enabled: true,
    },
  },
  restore_started: {
    vi: {
      title: "🔄 Restoring...",
      description: "Restoring server from backup.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔄 Restoring...",
      description: "Restoring server from backup.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  restore_completed: {
    vi: {
      title: "✅ Restore Completed",
      description: "Server has been restored successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "✅ Restore Completed",
      description: "Server has been restored successfully.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  member_pull_started: {
    vi: {
      title: "🔄 Pulling Members...",
      description: "Pulling **{total_members}** members back to the server.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
    en: {
      title: "🔄 Pulling Members...",
      description: "Pulling **{total_members}** members back to the server.",
      color: "#5865F2",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [],
      enabled: true,
    },
  },
  member_pull_completed: {
    vi: {
      title: "✅ Member Pull Completed",
      description: "Members have been pulled back to the server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "✅ Success", value: "{pulled}", inline: true },
        { name: "❌ Failed", value: "{failed}", inline: true },
        { name: "📊 Total", value: "{total}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "✅ Member Pull Completed",
      description: "Members have been pulled back to the server.",
      color: "#57F287",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "✅ Success", value: "{pulled}", inline: true },
        { name: "❌ Failed", value: "{failed}", inline: true },
        { name: "📊 Total", value: "{total}", inline: true },
      ],
      enabled: true,
    },
  },
  flash_sale_start: {
    vi: {
      title: "⚡ Flash Sale Started!",
      description: "**{product.name}** — Package **{package.name}** is on sale!\n🔥 Discount: **{sale.discount}**",
      color: "#FF6B35",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Ends At", value: "{sale.ends_at}", inline: true },
        { name: "📦 Quantity", value: "{sale.qty_limit}", inline: true },
        { name: "🎫 Coupons", value: "{sale.allow_coupon}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "⚡ Flash Sale Started!",
      description: "**{product.name}** — Package **{package.name}** is on sale!\n🔥 Discount: **{sale.discount}**",
      color: "#FF6B35",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "⏰ Ends At", value: "{sale.ends_at}", inline: true },
        { name: "📦 Quantity", value: "{sale.qty_limit}", inline: true },
        { name: "🎫 Coupons", value: "{sale.allow_coupon}", inline: true },
      ],
      enabled: true,
    },
  },
  flash_sale_end: {
    vi: {
      title: "🏁 Flash Sale Ended",
      description: "Flash sale for **{product.name}** — **{package.name}** has ended.",
      color: "#99AAB5",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "🛒 Sold", value: "{sale.qty_used} / {sale.qty_limit}", inline: true }],
      enabled: true,
    },
    en: {
      title: "🏁 Flash Sale Ended",
      description: "Flash sale for **{product.name}** — **{package.name}** has ended.",
      color: "#99AAB5",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "🛒 Sold", value: "{sale.qty_used} / {sale.qty_limit}", inline: true }],
      enabled: true,
    },
  },
  out_of_stock_admin: {
    vi: {
      title: "⚠️ Out of Stock — Manual Delivery Required",
      description: "Order **#{order.id}** by {user.mention} for **{product.name}** requires manual delivery.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Package", value: "{product.name}", inline: true },
        { name: "🆔 Order", value: "#{order.id}", inline: true },
      ],
      enabled: true,
    },
    en: {
      title: "⚠️ Out of Stock — Manual Delivery Required",
      description: "Order **#{order.id}** by {user.mention} for **{product.name}** requires manual delivery.",
      color: "#FEE75C",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [
        { name: "📦 Package", value: "{product.name}", inline: true },
        { name: "🆔 Order", value: "#{order.id}", inline: true },
      ],
      enabled: true,
    },
  },
  spending_leaderboard_auto: {
    vi: {
      title: "🏆 Spending Leaderboard — {period}",
      description: "{leaderboard}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📅 Date", value: "{date}", inline: true }],
      enabled: true,
    },
    en: {
      title: "🏆 Spending Leaderboard — {period}",
      description: "{leaderboard}",
      color: "#F0B232",
      author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
      fields: [{ name: "📅 Date", value: "{date}", inline: true }],
      enabled: true,
    },
  },
};
