import type { EmbedEventDef } from "./embedTypes";
import {
  ShoppingCart, Timer, Star, Gift,
  Trophy, Trash2,
  Ticket, TicketX, UserCheck, UserMinus, Ban,
  QrCode,
  ShieldOff, LayoutGrid, ShieldAlert,
  LogOut, Pencil, Volume2, VolumeX, ArrowRightLeft,
  LogIn, Hash, Shield, Moon, Zap, AlertTriangle,
  Heart, Mic, HelpCircle,
  Mail, TrendingUp,
} from "lucide-react";

// ─── Event definitions ───────────────────────────────────────────────────────

export const EMBED_EVENTS: EmbedEventDef[] = [
  // ── Đơn hàng ──
  { key: "don_hang_moi",      label: "Đơn hàng mới",           icon: ShoppingCart, desc: "Khi admin tạo đơn /tao_don" },
  { key: "qr_thanh_toan",     label: "QR Thanh toán",          icon: QrCode,       desc: "Gửi ảnh QR PayOS cho khách" },
  { key: "don_hang_het_han",  label: "Đơn hàng hết hạn",      icon: Timer,        desc: "Khi đơn quá 15 phút chưa thanh toán" },
  { key: "ghi_chu_don_hang",  label: "Ghi chú đơn hàng",      icon: ShoppingCart, desc: "Khi admin thêm ghi chú vào đơn hàng" },
  { key: "bang_gia",          label: "Bảng giá sản phẩm",     icon: ShoppingCart, desc: "Embed tổng quan khi dùng /bang_gia hoặc /san_pham" },
  { key: "san_pham_detail",   label: "Chi tiết sản phẩm",      icon: ShoppingCart, desc: "Embed chi tiết gói giá khi chọn sản phẩm (/san_pham)" },
  { key: "bxh_chi_tieu",      label: "BXH Chi tiêu",           icon: Trophy,       desc: "Embed bảng xếp hạng chi tiêu" },
  { key: "bxh_don_hang",      label: "BXH Đơn hàng",           icon: Trophy,       desc: "Embed bảng xếp hạng đơn hàng" },
  { key: "feedback",          label: "Feedback khách hàng",    icon: Star,         desc: "Khi user dùng /feedback" },
  // ── Cộng đồng ──
  { key: "giveaway",          label: "Giveaway bắt đầu",       icon: Gift,         desc: "Khi tạo /giveaway" },
  { key: "ket_qua_giveaway",  label: "Kết quả Giveaway",       icon: Trophy,       desc: "Khi giveaway kết thúc, công bố winner" },
  { key: "dm_welcome",        label: "DM chào mừng riêng tư",  icon: Mail,         desc: "Gửi tin nhắn chào mừng riêng cho thành viên mới" },
  { key: "reaction_role_panel",label: "Panel Reaction Role",   icon: Heart,        desc: "Panel chọn role bằng reaction" },
  { key: "starboard_post",    label: "Bài đăng Starboard",     icon: Star,         desc: "Khi tin nhắn được thêm vào starboard" },
  // ── Ticket ──
  { key: "ticket_mo",         label: "Mở Ticket",              icon: Ticket,       desc: "Khi user tạo ticket mới" },
  { key: "ticket_dong",       label: "Đóng Ticket",            icon: TicketX,      desc: "Khi ticket bị đóng" },
  { key: "ticket_nhan",       label: "Nhận Ticket",            icon: UserCheck,    desc: "Khi staff nhận ticket (claim)" },
  { key: "ticket_unclaim",    label: "Bỏ nhận Ticket",         icon: UserMinus,    desc: "Khi staff bỏ claim ticket" },
  { key: "ticket_panel",      label: "Panel Ticket",           icon: LayoutGrid,   desc: "Embed panel chứa buttons tạo ticket" },
  // ── Kiểm duyệt ──
  { key: "canh_bao",          label: "Cảnh báo thành viên",    icon: ShieldAlert,  desc: "Khi admin dùng /warn" },
  { key: "kick",              label: "Kick thành viên",        icon: UserMinus,    desc: "Khi bot kick user" },
  { key: "ban",               label: "Ban thành viên",         icon: Ban,          desc: "Khi bot ban user" },
  { key: "unban",             label: "Unban thành viên",       icon: ShieldOff,    desc: "Khi bot unban user" },
  { key: "automod_warn",      label: "AutoMod: Cảnh báo",     icon: AlertTriangle, desc: "Khi AutoMod cảnh báo user" },
  { key: "automod_mute",      label: "AutoMod: Mute",         icon: Shield,        desc: "Khi AutoMod mute user" },
  { key: "automod_kick",      label: "AutoMod: Kick",         icon: UserMinus,     desc: "Khi AutoMod kick user" },
  { key: "automod_delete",    label: "AutoMod: Xóa tin nhắn", icon: Trash2,        desc: "Khi AutoMod xóa tin nhắn vi phạm" },
  // ── Tiện ích ──
  { key: "afk_set",           label: "Đặt AFK",               icon: Moon,          desc: "Khi user đặt trạng thái AFK" },
  { key: "afk_return",        label: "Trở lại từ AFK",        icon: Zap,           desc: "Khi user AFK quay lại" },
  { key: "tempvoice_create",  label: "Tạo phòng voice",       icon: Mic,           desc: "Khi bot tạo phòng voice tạm và gửi panel nút" },
  { key: "tempvoice_panel",   label: "Panel Voice",           icon: Mic,           desc: "Panel điều khiển/temp voice do admin gửi" },
  { key: "tempvoice_action",  label: "Log hành động voice",   icon: Mic,           desc: "Khi user dùng nút điều khiển phòng voice" },
  // ── Leveling ──
  { key: "level_up",          label: "Lên level",              icon: TrendingUp,   desc: "Khi user lên level mới" },
  { key: "level_reward",      label: "Level Reward",          icon: Gift,          desc: "Khi user nhận role reward theo level" },
  { key: "leaderboard",       label: "Bảng xếp hạng XP",      icon: Trophy,        desc: "Embed bảng xếp hạng XP" },
  // ── Help ──
  { key: "help_menu",         label: "Help — Menu chính",     icon: HelpCircle,    desc: "Embed chào mừng khi dùng /help" },
  { key: "help_category",     label: "Help — Danh mục",       icon: HelpCircle,    desc: "Embed hiển thị lệnh trong một danh mục" },
  { key: "help_command",      label: "Help — Chi tiết lệnh",  icon: HelpCircle,    desc: "Embed chi tiết một lệnh cụ thể" },
  // ── Logging ──
  { key: "log_message_delete",     label: "Log: Xóa tin nhắn",       icon: Trash2,          desc: "Khi tin nhắn bị xóa" },
  { key: "log_message_edit",       label: "Log: Sửa tin nhắn",       icon: Pencil,          desc: "Khi tin nhắn được sửa" },
  { key: "log_message_bulk_delete",label: "Log: Xóa hàng loạt",      icon: Trash2,          desc: "Khi xóa nhiều tin nhắn cùng lúc" },
  { key: "log_voice_join",         label: "Log: Vào voice",           icon: Volume2,         desc: "Khi user vào voice channel" },
  { key: "log_voice_leave",        label: "Log: Rời voice",           icon: VolumeX,         desc: "Khi user rời voice channel" },
  { key: "log_voice_move",         label: "Log: Chuyển voice",        icon: ArrowRightLeft,  desc: "Khi user chuyển voice channel" },
  { key: "log_member_join",        label: "Log: Thành viên mới",      icon: LogIn,           desc: "Khi member tham gia server" },
  { key: "log_member_leave",       label: "Log: Thành viên rời",      icon: LogOut,          desc: "Khi member rời server" },
  { key: "log_nickname_change",    label: "Log: Đổi nickname",        icon: Pencil,          desc: "Khi member đổi nickname" },
  { key: "log_role_update",        label: "Log: Thay đổi role",       icon: ShieldAlert,     desc: "Khi role của member thay đổi" },
  { key: "log_channel_create",     label: "Log: Tạo kênh",            icon: Hash,            desc: "Khi kênh mới được tạo" },
  { key: "log_channel_delete",     label: "Log: Xóa kênh",            icon: Hash,            desc: "Khi kênh bị xóa" },
  // ── Tương tác — Có mục tiêu ──
  { key: "interact_airkiss",    label: "Airkiss",       icon: Heart, desc: "Gửi nụ hôn gió cho người khác" },
  { key: "interact_angrystare", label: "Angry Stare",   icon: Heart, desc: "Nhìn giận dữ người khác" },
  { key: "interact_bite",       label: "Bite",          icon: Heart, desc: "Cắn người khác" },
  { key: "interact_brofist",    label: "Brofist",       icon: Heart, desc: "Đấm tay với người khác" },
  { key: "interact_cuddle",     label: "Cuddle",        icon: Heart, desc: "Ôm ấp người khác" },
  { key: "interact_handhold",   label: "Handhold",      icon: Heart, desc: "Nắm tay người khác" },
  { key: "interact_hug",        label: "Hug",           icon: Heart, desc: "Ôm người khác" },
  { key: "interact_kiss",       label: "Kiss",          icon: Heart, desc: "Hôn người khác" },
  { key: "interact_lick",       label: "Lick",          icon: Heart, desc: "Liếm người khác" },
  { key: "interact_nom",        label: "Nom",           icon: Heart, desc: "Ăn người khác" },
  { key: "interact_nuzzle",     label: "Nuzzle",        icon: Heart, desc: "Cọ mũi với người khác" },
  { key: "interact_pat",        label: "Pat",           icon: Heart, desc: "Xoa đầu người khác" },
  { key: "interact_pinch",      label: "Pinch",         icon: Heart, desc: "Véo người khác" },
  { key: "interact_poke",       label: "Poke",          icon: Heart, desc: "Chọc người khác" },
  { key: "interact_punch",      label: "Punch",         icon: Heart, desc: "Đấm người khác" },
  { key: "interact_slap",       label: "Slap",          icon: Heart, desc: "Tát người khác" },
  { key: "interact_smack",      label: "Smack",         icon: Heart, desc: "Đánh người khác" },
  { key: "interact_tickle",     label: "Tickle",        icon: Heart, desc: "Cù người khác" },
  { key: "interact_wave",       label: "Wave",          icon: Heart, desc: "Vẫy tay với người khác" },
  { key: "interact_wink",       label: "Wink",          icon: Heart, desc: "Nháy mắt với người khác" },
  { key: "interact_stare",      label: "Stare",         icon: Heart, desc: "Nhìn chằm chằm người khác" },
  { key: "interact_peek",       label: "Peek",          icon: Heart, desc: "Nhìn trộm người khác" },
  // ── Tương tác — Biểu cảm ──
  { key: "interact_bleh",       label: "Bleh",          icon: Heart, desc: "Le lưỡi" },
  { key: "interact_blush",      label: "Blush",         icon: Heart, desc: "Đỏ mặt" },
  { key: "interact_celebrate",  label: "Celebrate",     icon: Heart, desc: "Ăn mừng" },
  { key: "interact_cheers",     label: "Cheers",        icon: Heart, desc: "Nâng ly" },
  { key: "interact_clap",       label: "Clap",          icon: Heart, desc: "Vỗ tay" },
  { key: "interact_confused",   label: "Confused",      icon: Heart, desc: "Bối rối" },
  { key: "interact_cool",       label: "Cool",          icon: Heart, desc: "Ngầu" },
  { key: "interact_cry",        label: "Cry",           icon: Heart, desc: "Khóc" },
  { key: "interact_dance",      label: "Dance",         icon: Heart, desc: "Nhảy" },
  { key: "interact_drool",      label: "Drool",         icon: Heart, desc: "Chảy nước miếng" },
  { key: "interact_evillaugh",  label: "Evil Laugh",    icon: Heart, desc: "Cười ác" },
  { key: "interact_facepalm",   label: "Facepalm",      icon: Heart, desc: "Facepalm" },
  { key: "interact_happy",      label: "Happy",         icon: Heart, desc: "Vui vẻ" },
  { key: "interact_headbang",   label: "Headbang",      icon: Heart, desc: "Headbang" },
  { key: "interact_huh",        label: "Huh",           icon: Heart, desc: "Hả?" },
  { key: "interact_laugh",      label: "Laugh",         icon: Heart, desc: "Cười" },
  { key: "interact_love",       label: "Love",          icon: Heart, desc: "Yêu" },
  { key: "interact_mad",        label: "Mad",           icon: Heart, desc: "Giận dữ" },
  { key: "interact_nervous",    label: "Nervous",       icon: Heart, desc: "Lo lắng" },
  { key: "interact_no",         label: "No",            icon: Heart, desc: "Lắc đầu" },
  { key: "interact_nosebleed",  label: "Nosebleed",     icon: Heart, desc: "Chảy máu mũi" },
  { key: "interact_nyah",       label: "Nyah",          icon: Heart, desc: "Nyah~" },
  { key: "interact_pout",       label: "Pout",          icon: Heart, desc: "Phụng phịu" },
  { key: "interact_roll",       label: "Roll",          icon: Heart, desc: "Lăn" },
  { key: "interact_run",        label: "Run",           icon: Heart, desc: "Chạy" },
  { key: "interact_sad",        label: "Sad",           icon: Heart, desc: "Buồn" },
  { key: "interact_scared",     label: "Scared",        icon: Heart, desc: "Sợ hãi" },
  { key: "interact_shout",      label: "Shout",         icon: Heart, desc: "Hét" },
  { key: "interact_shrug",      label: "Shrug",         icon: Heart, desc: "Nhún vai" },
  { key: "interact_shy",        label: "Shy",           icon: Heart, desc: "Ngại ngùng" },
  { key: "interact_sigh",       label: "Sigh",          icon: Heart, desc: "Thở dài" },
  { key: "interact_sip",        label: "Sip",           icon: Heart, desc: "Nhâm nhi" },
  { key: "interact_sleep",      label: "Sleep",         icon: Heart, desc: "Ngủ" },
  { key: "interact_slowclap",   label: "Slow Clap",     icon: Heart, desc: "Vỗ tay chậm" },
  { key: "interact_smile",      label: "Smile",         icon: Heart, desc: "Cười" },
  { key: "interact_smug",       label: "Smug",          icon: Heart, desc: "Tự mãn" },
  { key: "interact_sneeze",     label: "Sneeze",        icon: Heart, desc: "Hắt xì" },
  { key: "interact_sorry",      label: "Sorry",         icon: Heart, desc: "Xin lỗi" },
  { key: "interact_stop",       label: "Stop",          icon: Heart, desc: "Dừng lại" },
  { key: "interact_surprised",  label: "Surprised",     icon: Heart, desc: "Ngạc nhiên" },
  { key: "interact_sweat",      label: "Sweat",         icon: Heart, desc: "Toát mồ hôi" },
  { key: "interact_thumbsup",   label: "Thumbs Up",     icon: Heart, desc: "Thích" },
  { key: "interact_tired",      label: "Tired",         icon: Heart, desc: "Mệt" },
  { key: "interact_woah",       label: "Woah",          icon: Heart, desc: "Woah" },
  { key: "interact_yawn",       label: "Yawn",          icon: Heart, desc: "Ngáp" },
  { key: "interact_yay",        label: "Yay",           icon: Heart, desc: "Yay!" },
  { key: "interact_yes",        label: "Yes",           icon: Heart, desc: "Gật đầu" },
];

// ─── Event groups ────────────────────────────────────────────────────────────

export const EVENT_GROUPS: { label: string; keys: string[] }[] = [
  { label: "Đơn hàng",    keys: ["don_hang_moi", "qr_thanh_toan", "don_hang_het_han", "ghi_chu_don_hang", "bang_gia", "san_pham_detail", "bxh_chi_tieu", "bxh_don_hang", "feedback"] },
  { label: "Cộng đồng",   keys: ["giveaway", "ket_qua_giveaway", "dm_welcome", "reaction_role_panel", "starboard_post"] },
  { label: "Ticket",      keys: ["ticket_mo", "ticket_dong", "ticket_nhan", "ticket_unclaim", "ticket_panel"] },
  { label: "Kiểm duyệt", keys: ["canh_bao", "kick", "ban", "unban", "automod_warn", "automod_mute", "automod_kick", "automod_delete"] },
  { label: "Tiện ích",    keys: ["afk_set", "afk_return", "tempvoice_create", "tempvoice_panel", "tempvoice_action"] },
  { label: "Leveling",    keys: ["level_up", "level_reward", "leaderboard"] },
  { label: "Help",        keys: ["help_menu", "help_category", "help_command"] },
  { label: "Logging",     keys: ["log_message_delete", "log_message_edit", "log_message_bulk_delete", "log_voice_join", "log_voice_leave", "log_voice_move", "log_member_join", "log_member_leave", "log_nickname_change", "log_role_update", "log_channel_create", "log_channel_delete"] },
  { label: "Tương tác — Có mục tiêu", keys: ["interact_airkiss", "interact_angrystare", "interact_bite", "interact_brofist", "interact_cuddle", "interact_handhold", "interact_hug", "interact_kiss", "interact_lick", "interact_nom", "interact_nuzzle", "interact_pat", "interact_pinch", "interact_poke", "interact_punch", "interact_slap", "interact_smack", "interact_tickle", "interact_wave", "interact_wink", "interact_stare", "interact_peek"] },
  { label: "Tương tác — Biểu cảm", keys: ["interact_bleh", "interact_blush", "interact_celebrate", "interact_cheers", "interact_clap", "interact_confused", "interact_cool", "interact_cry", "interact_dance", "interact_drool", "interact_evillaugh", "interact_facepalm", "interact_happy", "interact_headbang", "interact_huh", "interact_laugh", "interact_love", "interact_mad", "interact_nervous", "interact_no", "interact_nosebleed", "interact_nyah", "interact_pout", "interact_roll", "interact_run", "interact_sad", "interact_scared", "interact_shout", "interact_shrug", "interact_shy", "interact_sigh", "interact_sip", "interact_sleep", "interact_slowclap", "interact_smile", "interact_smug", "interact_sneeze", "interact_sorry", "interact_stop", "interact_surprised", "interact_sweat", "interact_thumbsup", "interact_tired", "interact_woah", "interact_yawn", "interact_yay", "interact_yes"] },
];

// ─── Variables reference ─────────────────────────────────────────────────────

export const VARIABLES: { token: string; desc: string }[] = [
  { token: "{user}",              desc: "Tên người dùng" },
  { token: "{user.mention}",      desc: "@mention người dùng" },
  { token: "{user.id}",           desc: "Discord ID" },
  { token: "{order.id}",          desc: "Mã đơn hàng (#12345)" },
  { token: "{order.total}",       desc: "Tổng tiền (100,000)" },
  { token: "{order.status}",      desc: "Trạng thái đơn hàng" },
  { token: "{order.created_at}",  desc: "Ngày tạo đơn" },
  { token: "{note}",              desc: "Ghi chú đơn hàng" },
  { token: "{product.name}",      desc: "Tên sản phẩm" },
  { token: "{product.description}", desc: "Mô tả sản phẩm" },
  { token: "{package.name}",      desc: "Tên gói sản phẩm (san_pham_detail)" },
  { token: "{package.price}",     desc: "Giá gói sản phẩm (san_pham_detail)" },
  { token: "{package.description}", desc: "Mô tả gói sản phẩm (san_pham_detail)" },
  { token: "{product.price}",     desc: "Giá sản phẩm" },
  { token: "{product.stock}",     desc: "Số lượng tồn kho" },
  { token: "{product.image_url}", desc: "Ảnh sản phẩm" },
  { token: "{qr_url}",            desc: "URL ảnh QR thanh toán" },
  { token: "{transfer_content}",  desc: "Nội dung chuyển khoản" },
  { token: "{coupon.code}",       desc: "Mã coupon" },
  { token: "{coupon.discount}",   desc: "Giá trị giảm giá" },
  { token: "{coupon.expires_at}", desc: "Hạn sử dụng coupon" },
  { token: "{package}",           desc: "Nội dung gói (cho đơn custom)" },
  { token: "{date}",              desc: "Ngày giờ hiện tại" },
  { token: "{server}",            desc: "Tên server" },
  { token: "{member_count}",      desc: "Số thành viên" },
  { token: "{prize}",             desc: "Phần thưởng (giveaway)" },
  { token: "{ends_at}",           desc: "Thời gian kết thúc (giveaway)" },
  { token: "{host}",              desc: "Người tổ chức (giveaway)" },
  { token: "{winners_count}",     desc: "Số người thắng (giveaway)" },
  { token: "{winners}",           desc: "Tên người thắng (ket_qua_giveaway)" },
  { token: "{reason}",            desc: "Lý do (warn/ban/kick/cấm)" },
  { token: "{warn_count}",        desc: "Tổng số cảnh báo" },
  { token: "{moderator}",         desc: "Người thực hiện (mod)" },
  { token: "{stars}",             desc: "Số sao (feedback)" },
  { token: "{content}",           desc: "Nội dung feedback" },
  { token: "{channel.name}",     desc: "Tên kênh Discord" },
  { token: "{panel.channel}",    desc: "Kênh được gửi panel" },
  { token: "{button.count}",     desc: "Số nút temp voice đang bật" },
  { token: "{buttons}",          desc: "Danh sách nút temp voice đang bật" },

  { token: "{channel.mention}",  desc: "Mention kênh Discord" },
  { token: "{channel.id}",       desc: "ID kênh Discord" },
  { token: "{target}",           desc: "Tên user mục tiêu" },
  { token: "{target.mention}",   desc: "Mention user mục tiêu" },
  { token: "{target.id}",        desc: "ID user mục tiêu" },
  { token: "{action}",           desc: "Hành động được thực hiện" },
  { token: "{details}",          desc: "Chi tiết hành động" },
  { token: "{level}",            desc: "Level hiện tại" },
  { token: "{old_level}",        desc: "Level trước đó" },
  { token: "{xp}",               desc: "Tổng XP" },
  { token: "{rank}",             desc: "Thứ hạng leveling" },
  { token: "{progress}",         desc: "Tiến độ level hiện tại" },
  { token: "{progress_percent}", desc: "Phần trăm tiến độ level" },
  { token: "{next_level_xp}",    desc: "XP cần cho level tiếp theo" },
  { token: "{leaderboard}",      desc: "Nội dung leaderboard" },
  { token: "{reward.role}",      desc: "Role reward theo level" },
  { token: "{ticket.id}",         desc: "ID ticket" },
  { token: "{close_reason}",      desc: "Lý do đóng ticket" },
  { token: "{staff.mention}",     desc: "Staff nhận ticket" },
  { token: "{duration}",          desc: "Thời gian timeout" },
  { token: "{mod}",               desc: "Tên mod thực hiện" },
  { token: "{invite_code}",       desc: "Mã invite" },
  { token: "{inviter}",           desc: "Người mời" },
  { token: "{top1}",              desc: "Top 1 BXH mời" },
  { token: "{top2}",              desc: "Top 2 BXH mời" },
  { token: "{top3}",              desc: "Top 3 BXH mời" },
  { token: "{sticky.title}",      desc: "Tiêu đề sticky" },
  { token: "{sticky.content}",    desc: "Nội dung sticky" },
  { token: "{channel.name}",      desc: "Tên kênh voice" },
  { token: "{channel}",           desc: "Mention kênh (log)" },
  { token: "{before}",            desc: "Nội dung trước (edit/nick)" },
  { token: "{after}",             desc: "Nội dung sau (edit/nick)" },
  { token: "{message.url}",       desc: "Link tin nhắn" },
  { token: "{count}",             desc: "Số lượng (bulk delete)" },
  { token: "{from}",              desc: "Kênh voice cũ" },
  { token: "{to}",                desc: "Kênh voice mới" },
  { token: "{account_age}",       desc: "Thời gian tạo tài khoản" },
  { token: "{roles}",             desc: "Danh sách role" },
  { token: "{changes}",           desc: "Thay đổi role" },
  { token: "{type}",              desc: "Loại kênh" },
  { token: "{reason}",            desc: "Lý do (automod, afk)" },
  { token: "{duration}",          desc: "Thời gian (mute, AFK)" },
  { token: "{message.url}",       desc: "Link tới tin nhắn gốc" },
  { token: "{time_label}",        desc: "Thời gian BXH (Hôm nay, 7 ngày...)" },
  { token: "{leaderboard_lines}", desc: "Nội dung BXH (danh sách top)" },
  { token: "{updated_at}",        desc: "Thời gian cập nhật BXH" },
  { token: "{target}",            desc: "Tên người được tương tác" },
  { token: "{target.mention}",    desc: "@mention người được tương tác" },
  { token: "{action}",            desc: "Hành động tương tác" },
  { token: "{emoji}",             desc: "Emoji tương tác" },
  { token: "{gif_url}",           desc: "URL ảnh GIF tương tác" },
];
