import type { EmbedEventDef } from "./embedTypes";
import {
  ShoppingCart, Timer, Star, Gift,
  Trophy, Trash2,
  Ban,
  QrCode,
  ShieldOff, ShieldAlert,
  LogOut, Pencil, Volume2, VolumeX, ArrowRightLeft,
  LogIn, Hash, Shield, Moon, Zap, ZapOff, AlertTriangle,
  Heart, HelpCircle,
  CheckCircle, Package, PackageX, ClipboardList, Tag, UserPlus, Pin, UserMinus,
  Archive, RotateCcw, BrainCircuit, ImageIcon,
  XCircle, Bell, BarChart3, Rss, Sun, AtSign, UserCheck,
} from "lucide-react";

// ─── Event definitions ───────────────────────────────────────────────────────

export const EMBED_EVENTS: EmbedEventDef[] = [
  // ── Orders ──
  { key: "don_hang_moi",      label: "New Order",           labelEn: "New Order",           icon: ShoppingCart, desc: "When admin creates an order /tao_don" },
  { key: "qr_thanh_toan",     label: "Payment QR",          labelEn: "Payment QR",          icon: QrCode,       desc: "Send PayOS QR image to customer" },
  { key: "qr_thanh_toan_payos",  label: "Payment — PayOS",   labelEn: "Payment — PayOS",    icon: QrCode, desc: "PayOS-specific payment embed" },
  { key: "qr_thanh_toan_paypal", label: "Payment — PayPal",  labelEn: "Payment — PayPal",   icon: QrCode, desc: "PayPal-specific payment embed" },
  { key: "qr_thanh_toan_crypto", label: "Payment — Crypto",  labelEn: "Payment — Crypto",   icon: QrCode, desc: "Crypto-specific payment embed" },
  { key: "qr_thanh_toan_manual", label: "Payment — Manual",  labelEn: "Payment — Manual",   icon: QrCode, desc: "Manual bank transfer payment embed" },
  { key: "don_hang_het_han",  label: "Expired Order",      labelEn: "Expired Order",       icon: Timer,        desc: "When order is unpaid after 15 minutes" },
  { key: "ghi_chu_don_hang",  label: "Order Note",      labelEn: "Order Note",          icon: ShoppingCart, desc: "When admin adds a note to an order" },
  { key: "bang_gia",          label: "Price List",     labelEn: "Price List",          icon: ShoppingCart, desc: "Overview embed for /bang_gia or /san_pham" },
  { key: "bxh_chi_tieu",      label: "Spending Leaderboard",           labelEn: "Spending Leaderboard", icon: Trophy,       desc: "Spending leaderboard embed" },
  { key: "bxh_don_hang",      label: "Order Leaderboard",           labelEn: "Order Leaderboard",   icon: Trophy,       desc: "Order leaderboard embed" },
  { key: "milestone_reached", label: "Milestone Reached (DM)",      labelEn: "Milestone Reached",   icon: Trophy,       desc: "DM sent to user when they reach a spending milestone" },
  { key: "feedback",          label: "Customer Feedback",    labelEn: "Customer Feedback",   icon: Star,         desc: "When user uses /feedback" },
  { key: "thanh_toan",        label: "Payment Success",  labelEn: "Payment Success",     icon: CheckCircle,  desc: "When customer pays successfully" },
  { key: "giao_hang",         label: "Delivery",              labelEn: "Delivery",            icon: Package,      desc: "When order is delivered" },
  { key: "don_hang_chi_tiet", label: "Order Detail",      labelEn: "Order Detail",        icon: ClipboardList,desc: "Order detail embed for /don_hang" },
  { key: "coupon",            label: "Coupon",            labelEn: "Coupon",              icon: Tag,          desc: "When sending coupon to user" },
  { key: "ban_shop",          label: "Shop Ban",           labelEn: "Shop Ban",            icon: Ban,          desc: "When user is banned from shopping" },
  { key: "unban_shop",        label: "Shop Unban",        labelEn: "Shop Unban",          icon: ShieldOff,    desc: "When user is unbanned from shopping" },
  { key: "flash_sale_start",  label: "Flash Sale Start",  labelEn: "Flash Sale Start",    icon: Zap,          desc: "Posted when a flash sale begins" },
  { key: "flash_sale_end",    label: "Flash Sale End",    labelEn: "Flash Sale End",      icon: ZapOff,       desc: "Posted when a flash sale ends" },
  { key: "out_of_stock_admin",label: "Out of Stock (Admin)", labelEn: "Out of Stock (Admin)", icon: PackageX,   desc: "Admin notified when item is out of stock" },
  { key: "spending_leaderboard_auto", label: "Auto Leaderboard", labelEn: "Auto Leaderboard", icon: Trophy,     desc: "Auto-posted spending leaderboard" },
  // ── Community ──
  { key: "giveaway",          label: "Giveaway",       labelEn: "Giveaway",            icon: Gift,         desc: "When creating /giveaway" },
  { key: "ket_qua_giveaway",  label: "Giveaway Result",       labelEn: "Giveaway Result",     icon: Trophy,       desc: "When giveaway ends, announce winner" },
  { key: "reaction_role_panel",label: "Panel Reaction Role",   labelEn: "Reaction Role Panel", icon: Heart,        desc: "Reaction role selection panel" },
  { key: "starboard_post",    label: "Starboard Post",     labelEn: "Starboard Post",      icon: Star,         desc: "When message is added to starboard" },
  { key: "invite_join",       label: "Invite Join",  labelEn: "Invite Join",         icon: UserPlus,     desc: "When member joins via invite" },
  { key: "invite_leaderboard",label: "Invite Leaderboard",             labelEn: "Invite Leaderboard",  icon: Trophy,       desc: "Invite leaderboard" },
  { key: "giveaway_banned",   label: "Giveaway Banned",  labelEn: "Giveaway Banned",     icon: Ban,          desc: "When user is banned from giveaways" },
  // ── Moderation ──
  { key: "canh_bao",          label: "Warning",    labelEn: "Warning",              icon: ShieldAlert,  desc: "When admin uses /warn" },
  { key: "kick",              label: "Kick",        labelEn: "Kick",                 icon: UserMinus,    desc: "When bot kicks a user" },
  { key: "ban",               label: "Ban",         labelEn: "Ban",                  icon: Ban,          desc: "When bot bans a user" },
  { key: "unban",             label: "Unban",       labelEn: "Unban",                icon: ShieldOff,    desc: "When bot unbans a user" },
  { key: "automod_warn",      label: "AutoMod Warning",     labelEn: "AutoMod Warning",      icon: AlertTriangle, desc: "When AutoMod warns a user" },
  { key: "automod_mute",      label: "AutoMod: Mute",         labelEn: "AutoMod Mute",         icon: Shield,        desc: "When AutoMod mutes a user" },
  { key: "automod_kick",      label: "AutoMod: Kick",         labelEn: "AutoMod Kick",         icon: UserMinus,     desc: "When AutoMod kicks a user" },
  { key: "automod_delete",    label: "AutoMod Delete", labelEn: "AutoMod Delete",       icon: Trash2,        desc: "When AutoMod deletes a violating message" },
  { key: "timeout",           label: "Timeout",               labelEn: "Timeout",              icon: Timer,         desc: "When user is timed out" },
  { key: "softban",          label: "Softban",               labelEn: "Softban",              icon: Ban,           desc: "When user is softbanned (ban + unban to delete messages)" },
  { key: "mute",             label: "Mute",                  labelEn: "Mute",                 icon: Shield,        desc: "When user is muted/timed out by a mod" },
  { key: "deafen",           label: "Deafen",                labelEn: "Deafen",               icon: Shield,        desc: "When user is deafened in voice" },
  { key: "rolepersist",      label: "Role Persist",          labelEn: "Role Persist",         icon: Shield,        desc: "When assigning a persistent role (persists through leave/rejoin)" },
  { key: "temprole",         label: "Temp Role",             labelEn: "Temp Role",            icon: Timer,         desc: "When assigning a temporary role" },
  { key: "lockdown_start",   label: "Lockdown Start",     labelEn: "Lockdown Start",       icon: Shield,        desc: "When server enters lockdown mode" },
  { key: "lockdown_end",     label: "Lockdown End",     labelEn: "Lockdown End",         icon: ShieldOff,     desc: "When server exits lockdown" },
  // ── Utilities ──
  { key: "afk_set",           label: "AFK Set",               labelEn: "AFK Set",              icon: Moon,          desc: "When user goes AFK" },
  { key: "afk_return",        label: "AFK Return",        labelEn: "AFK Return",           icon: Sun,           desc: "When user returns from AFK" },
  { key: "afk_mention",       label: "AFK Mention",       labelEn: "AFK Mention",          icon: AtSign,        desc: "When an AFK user is mentioned" },
  { key: "sticky_message",    label: "Sticky Message", labelEn: "Sticky Message",       icon: Pin,           desc: "Auto sticky message embed" },
  // ── Help ──
  { key: "help_menu",         label: "Help Menu",     labelEn: "Help Menu",            icon: HelpCircle,    desc: "Welcome embed for /help" },
  { key: "help_category",     label: "Help Category",       labelEn: "Help Category",        icon: HelpCircle,    desc: "Embed showing commands in a category" },
  { key: "help_command",      label: "Help Command",  labelEn: "Help Command",         icon: HelpCircle,    desc: "Embed for a specific command detail" },
  // ── Logging ──
  { key: "log_message_delete",     label: "Log: Message Deleted",       labelEn: "Message Deleted",       icon: Trash2,          desc: "When a message is deleted" },
  { key: "log_message_edit",       label: "Log: Message Edited",       labelEn: "Message Edited",        icon: Pencil,          desc: "When a message is edited" },
  { key: "log_message_bulk_delete",label: "Log: Bulk Delete",      labelEn: "Bulk Delete",           icon: Trash2,          desc: "When multiple messages are deleted at once" },
  { key: "log_voice_join",         label: "Log: Voice Join",           labelEn: "Voice Join",            icon: Volume2,         desc: "When user joins a voice channel" },
  { key: "log_voice_leave",        label: "Log: Voice Leave",           labelEn: "Voice Leave",           icon: VolumeX,         desc: "When user leaves a voice channel" },
  { key: "log_voice_move",         label: "Log: Voice Move",        labelEn: "Voice Move",            icon: ArrowRightLeft,  desc: "When user switches voice channel" },
  { key: "log_member_join",        label: "Log: Member Join",      labelEn: "Member Join",           icon: LogIn,           desc: "When a member joins the server" },
  { key: "log_member_leave",       label: "Log: Member Leave",      labelEn: "Member Leave",          icon: LogOut,          desc: "When a member leaves the server" },
  { key: "log_nickname_change",    label: "Log: Nickname Change",        labelEn: "Nickname Change",       icon: Pencil,          desc: "When member changes nickname" },
  { key: "log_role_update",        label: "Log: Role Update",       labelEn: "Role Update",           icon: ShieldAlert,     desc: "When member roles change" },
  { key: "log_channel_create",     label: "Log: Channel Created",            labelEn: "Channel Created",       icon: Hash,            desc: "When a new channel is created" },
  { key: "log_channel_delete",     label: "Log: Channel Deleted",            labelEn: "Channel Deleted",       icon: Hash,            desc: "When a channel is deleted" },
  // ── Interactions — Targeted ──
  { key: "interact_airkiss",    label: "Airkiss",       labelEn: "Air Kiss",      icon: Heart, desc: "Blow a kiss at someone" },
  { key: "interact_angrystare", label: "Angry Stare",   labelEn: "Angry Stare",   icon: Heart, desc: "Stare angrily at someone" },
  { key: "interact_bite",       label: "Bite",          labelEn: "Bite",          icon: Heart, desc: "Bite someone" },
  { key: "interact_brofist",    label: "Brofist",       labelEn: "Brofist",       icon: Heart, desc: "Fist-bump someone" },
  { key: "interact_cuddle",     label: "Cuddle",        labelEn: "Cuddle",        icon: Heart, desc: "Cuddle someone" },
  { key: "interact_handhold",   label: "Handhold",      labelEn: "Hand Hold",     icon: Heart, desc: "Hold hands with someone" },
  { key: "interact_hug",        label: "Hug",           labelEn: "Hug",           icon: Heart, desc: "Hug someone" },
  { key: "interact_kiss",       label: "Kiss",          labelEn: "Kiss",          icon: Heart, desc: "Kiss someone" },
  { key: "interact_lick",       label: "Lick",          labelEn: "Lick",          icon: Heart, desc: "Lick someone" },
  { key: "interact_nom",        label: "Nom",           labelEn: "Nom",           icon: Heart, desc: "Nom on someone" },
  { key: "interact_nuzzle",     label: "Nuzzle",        labelEn: "Nuzzle",        icon: Heart, desc: "Nuzzle someone" },
  { key: "interact_pat",        label: "Pat",           labelEn: "Pat",           icon: Heart, desc: "Pat someone" },
  { key: "interact_pinch",      label: "Pinch",         labelEn: "Pinch",         icon: Heart, desc: "Pinch someone" },
  { key: "interact_poke",       label: "Poke",          labelEn: "Poke",          icon: Heart, desc: "Poke someone" },
  { key: "interact_punch",      label: "Punch",         labelEn: "Punch",         icon: Heart, desc: "Punch someone" },
  { key: "interact_slap",       label: "Slap",          labelEn: "Slap",          icon: Heart, desc: "Slap someone" },
  { key: "interact_smack",      label: "Smack",         labelEn: "Smack",         icon: Heart, desc: "Smack someone" },
  { key: "interact_tickle",     label: "Tickle",        labelEn: "Tickle",        icon: Heart, desc: "Tickle someone" },
  { key: "interact_wave",       label: "Wave",          labelEn: "Wave",          icon: Heart, desc: "Wave at someone" },
  { key: "interact_wink",       label: "Wink",          labelEn: "Wink",          icon: Heart, desc: "Wink at someone" },
  { key: "interact_stare",      label: "Stare",         labelEn: "Stare",         icon: Heart, desc: "Stare at someone" },
  { key: "interact_peek",       label: "Peek",          labelEn: "Peek",          icon: Heart, desc: "Peek at someone" },
  // ── Interactions — Expressions ──
  { key: "interact_bleh",       label: "Bleh", labelEn: "Bleh",          icon: Heart, desc: "Stick out tongue", descEn: "Stick out tongue" },
  { key: "interact_blush",      label: "Blush", labelEn: "Blush",         icon: Heart, desc: "Blush", descEn: "Blush" },
  { key: "interact_celebrate",  label: "Celebrate", labelEn: "Celebrate",     icon: Heart, desc: "Celebrate", descEn: "Celebrate" },
  { key: "interact_cheers",     label: "Cheers", labelEn: "Cheers",        icon: Heart, desc: "Raise a toast", descEn: "Raise a toast" },
  { key: "interact_clap",       label: "Clap", labelEn: "Clap",          icon: Heart, desc: "Clap", descEn: "Clap" },
  { key: "interact_confused",   label: "Confused", labelEn: "Confused",      icon: Heart, desc: "Look confused", descEn: "Look confused" },
  { key: "interact_cool",       label: "Cool", labelEn: "Cool",          icon: Heart, desc: "Act cool", descEn: "Act cool" },
  { key: "interact_cry",        label: "Cry", labelEn: "Cry",           icon: Heart, desc: "Cry", descEn: "Cry" },
  { key: "interact_dance",      label: "Dance", labelEn: "Dance",         icon: Heart, desc: "Dance", descEn: "Dance" },
  { key: "interact_drool",      label: "Drool", labelEn: "Drool",         icon: Heart, desc: "Drool", descEn: "Drool" },
  { key: "interact_evillaugh",  label: "Evil Laugh", labelEn: "Evil Laugh",    icon: Heart, desc: "Evil laugh", descEn: "Evil laugh" },
  { key: "interact_facepalm",   label: "Facepalm", labelEn: "Facepalm",      icon: Heart, desc: "Facepalm", descEn: "Facepalm" },
  { key: "interact_happy",      label: "Happy", labelEn: "Happy",         icon: Heart, desc: "Feel happy", descEn: "Feel happy" },
  { key: "interact_headbang",   label: "Headbang", labelEn: "Headbang",      icon: Heart, desc: "Headbang", descEn: "Headbang" },
  { key: "interact_huh",        label: "Huh", labelEn: "Huh",           icon: Heart, desc: "Look puzzled", descEn: "Look puzzled" },
  { key: "interact_laugh",      label: "Laugh", labelEn: "Laugh",         icon: Heart, desc: "Laugh", descEn: "Laugh" },
  { key: "interact_love",       label: "Love", labelEn: "Love",          icon: Heart, desc: "Express love", descEn: "Express love" },
  { key: "interact_mad",        label: "Mad", labelEn: "Mad",           icon: Heart, desc: "Get mad", descEn: "Get mad" },
  { key: "interact_nervous",    label: "Nervous", labelEn: "Nervous",       icon: Heart, desc: "Feel nervous", descEn: "Feel nervous" },
  { key: "interact_no",         label: "No", labelEn: "No",            icon: Heart, desc: "Shake head no", descEn: "Shake head no" },
  { key: "interact_nosebleed",  label: "Nosebleed", labelEn: "Nosebleed",     icon: Heart, desc: "Nosebleed", descEn: "Nosebleed" },
  { key: "interact_nyah",       label: "Nyah", labelEn: "Nyah",          icon: Heart, desc: "Nyah~", descEn: "Nyah~" },
  { key: "interact_pout",       label: "Pout", labelEn: "Pout",          icon: Heart, desc: "Pout", descEn: "Pout" },
  { key: "interact_roll",       label: "Roll", labelEn: "Roll",          icon: Heart, desc: "Roll around", descEn: "Roll around" },
  { key: "interact_run",        label: "Run", labelEn: "Run",           icon: Heart, desc: "Run away", descEn: "Run away" },
  { key: "interact_sad",        label: "Sad", labelEn: "Sad",           icon: Heart, desc: "Feel sad", descEn: "Feel sad" },
  { key: "interact_scared",     label: "Scared", labelEn: "Scared",        icon: Heart, desc: "Feel scared", descEn: "Feel scared" },
  { key: "interact_shout",      label: "Shout", labelEn: "Shout",         icon: Heart, desc: "Shout", descEn: "Shout" },
  { key: "interact_shrug",      label: "Shrug", labelEn: "Shrug",         icon: Heart, desc: "Shrug", descEn: "Shrug" },
  { key: "interact_shy",        label: "Shy", labelEn: "Shy",           icon: Heart, desc: "Feel shy", descEn: "Feel shy" },
  { key: "interact_sigh",       label: "Sigh", labelEn: "Sigh",          icon: Heart, desc: "Sigh", descEn: "Sigh" },
  { key: "interact_sip",        label: "Sip", labelEn: "Sip",           icon: Heart, desc: "Sip a drink", descEn: "Sip a drink" },
  { key: "interact_sleep",      label: "Sleep", labelEn: "Sleep",         icon: Heart, desc: "Fall asleep", descEn: "Fall asleep" },
  { key: "interact_slowclap",   label: "Slow Clap", labelEn: "Slow Clap",     icon: Heart, desc: "Slow clap", descEn: "Slow clap" },
  { key: "interact_smile",      label: "Smile", labelEn: "Smile",         icon: Heart, desc: "Laugh", descEn: "Smile" },
  { key: "interact_smug",       label: "Smug", labelEn: "Smug",          icon: Heart, desc: "Look smug", descEn: "Look smug" },
  { key: "interact_sneeze",     label: "Sneeze", labelEn: "Sneeze",        icon: Heart, desc: "Sneeze", descEn: "Sneeze" },
  { key: "interact_sorry",      label: "Sorry", labelEn: "Sorry",         icon: Heart, desc: "Apologize", descEn: "Apologize" },
  { key: "interact_stop",       label: "Stop", labelEn: "Stop",          icon: Heart, desc: "Signal to stop", descEn: "Signal to stop" },
  { key: "interact_surprised",  label: "Surprised", labelEn: "Surprised",     icon: Heart, desc: "Look surprised", descEn: "Look surprised" },
  { key: "interact_sweat",      label: "Sweat", labelEn: "Sweat",         icon: Heart, desc: "Sweat nervously", descEn: "Sweat nervously" },
  { key: "interact_thumbsup",   label: "Thumbs Up", labelEn: "Thumbs Up",     icon: Heart, desc: "Thumbs up", descEn: "Thumbs up" },
  { key: "interact_tired",      label: "Tired", labelEn: "Tired",         icon: Heart, desc: "Feel tired", descEn: "Feel tired" },
  { key: "interact_woah",       label: "Woah", labelEn: "Woah",          icon: Heart, desc: "Woah", descEn: "Woah" },
  { key: "interact_yawn",       label: "Yawn", labelEn: "Yawn",          icon: Heart, desc: "Yawn", descEn: "Yawn" },
  { key: "interact_yay",        label: "Yay", labelEn: "Yay",           icon: Heart, desc: "Yay!", descEn: "Yay!" },
  { key: "interact_yes",        label: "Yes", labelEn: "Yes",           icon: Heart, desc: "Nod yes", descEn: "Nod yes" },
  // ── Security & Recovery ──
  // ── Backup & Restore ──
  { key: "backup_completed",       label: "Backup Completed",        labelEn: "Backup Completed",       icon: Archive,      desc: "When server backup is completed" },
  { key: "restore_started",        label: "Restore Started",          labelEn: "Restore Started",        icon: RotateCcw,    desc: "When server restore starts" },
  { key: "restore_completed",      label: "Restore Completed",      labelEn: "Restore Completed",      icon: CheckCircle,  desc: "When server restore is completed" },
  // ── Server Alerts ──
  { key: "alert_mass_ban",        label: "Mass Ban Alert",       labelEn: "Mass Ban Alert",         icon: AlertTriangle, desc: "When multiple consecutive bans are detected" },
  { key: "alert_mass_kick",       label: "Mass Kick Alert",      labelEn: "Mass Kick Alert",        icon: AlertTriangle, desc: "When multiple consecutive kicks are detected" },
  { key: "alert_channel_delete",  label: "Channel Delete Alert",      labelEn: "Channel Delete Alert",   icon: Trash2,        desc: "When multiple consecutive channel deletions are detected" },
  { key: "alert_role_delete",     label: "Role Delete Alert",       labelEn: "Role Delete Alert",      icon: Trash2,        desc: "When multiple consecutive role deletions are detected" },
  { key: "alert_nuke_detect",     label: "Nuke Detected",          labelEn: "Nuke Detected",          icon: Zap,           desc: "When server nuke behavior is detected" },
  // ── AI Chat ──
  { key: "ai_response",           label: "AI Response",            labelEn: "AI Response",            icon: BrainCircuit,  desc: "When AI bot responds to a question" },
  { key: "ai_image",              label: "AI Image Generated",     labelEn: "AI Image Generated",     icon: ImageIcon,     desc: "When AI generates an image" },
  // ── Auto Role ──
  { key: "autorole_assign",       label: "Role Assigned",          labelEn: "Role Assigned",          icon: UserCheck,     desc: "When an auto role is assigned" },
  // ── Forms ──
  { key: "form_submitted",        label: "Form Submitted",         labelEn: "Form Submitted",         icon: ClipboardList, desc: "When a form is submitted" },
  { key: "form_approved",         label: "Form Approved",          labelEn: "Form Approved",          icon: CheckCircle,   desc: "When a submission is approved" },
  { key: "form_rejected",         label: "Form Rejected",          labelEn: "Form Rejected",          icon: XCircle,       desc: "When a submission is rejected" },
  // ── Reminders ──
  { key: "reminder_fire",         label: "Reminder Fire",          labelEn: "Reminder Fire",          icon: Bell,          desc: "When a reminder fires" },
  // ── Polls ──
  { key: "poll_created",          label: "Poll Created",           labelEn: "Poll Created",           icon: BarChart3,     desc: "When a poll is created" },
  { key: "poll_ended",            label: "Poll Ended",             labelEn: "Poll Ended",             icon: BarChart3,     desc: "When a poll ends" },
  // ── Social Feeds ──
  { key: "social_feed_post",      label: "Feed Post",              labelEn: "Feed Post",              icon: Rss,           desc: "When a new feed item is posted" },
  // ── Staff Management ──
  { key: "staff_clockin",         label: "Staff Clocked In",       labelEn: "Staff Clocked In",       icon: UserCheck,     desc: "When a staff member clocks in" },
  { key: "staff_clockout",        label: "Staff Clocked Out",      labelEn: "Staff Clocked Out",      icon: UserCheck,     desc: "When a staff member clocks out" },
  { key: "staff_commission_paid", label: "Commission Paid",        labelEn: "Commission Paid",        icon: UserCheck,     desc: "When admin marks commission as paid" },
  // ── Queue / Support Tickets ──
  { key: "ticket_opened",         label: "Ticket Opened",          labelEn: "Ticket Opened",          icon: UserCheck,     desc: "When a support ticket is opened" },
  { key: "ticket_claimed",        label: "Ticket Claimed",         labelEn: "Ticket Claimed",         icon: UserCheck,     desc: "When a staff member claims a ticket" },
  { key: "ticket_resolved",       label: "Ticket Resolved",        labelEn: "Ticket Resolved",        icon: UserCheck,     desc: "When a ticket is marked resolved" },
  { key: "ticket_closed",         label: "Ticket Closed",          labelEn: "Ticket Closed",          icon: UserCheck,     desc: "When a ticket is closed" },
  { key: "ticket_sla_breach",     label: "Ticket SLA Breach",      labelEn: "Ticket SLA Breach",      icon: UserCheck,     desc: "When a ticket breaches its SLA" },
];

// ─── Event groups ────────────────────────────────────────────────────────────

export const EVENT_GROUPS: { label: string; labelEn: string; keys: string[] }[] = [
  { label: "Orders",    labelEn: "Orders",         keys: ["don_hang_moi", "don_hang_chi_tiet", "don_hang_het_han", "ghi_chu_don_hang", "bang_gia"] },
  { label: "Payments",  labelEn: "Payments",       keys: ["qr_thanh_toan", "qr_thanh_toan_payos", "qr_thanh_toan_paypal", "qr_thanh_toan_crypto", "qr_thanh_toan_manual", "thanh_toan"] },
  { label: "Delivery & Products", labelEn: "Delivery & Products", keys: ["giao_hang", "coupon", "flash_sale_start", "flash_sale_end", "out_of_stock_admin"] },
  { label: "Shop Management", labelEn: "Shop Management", keys: ["ban_shop", "unban_shop", "feedback", "bxh_chi_tieu", "bxh_don_hang", "spending_leaderboard_auto", "milestone_reached"] },
  { label: "Community",   labelEn: "Community",      keys: ["giveaway", "ket_qua_giveaway", "giveaway_banned", "reaction_role_panel", "starboard_post", "invite_join", "invite_leaderboard"] },
  { label: "Moderation", labelEn: "Moderation",      keys: ["canh_bao", "kick", "ban", "unban", "softban", "mute", "deafen", "timeout", "rolepersist", "temprole", "lockdown_start", "lockdown_end"] },
  { label: "AutoMod",   labelEn: "AutoMod",         keys: ["automod_warn", "automod_mute", "automod_kick", "automod_delete"] },
  { label: "Logging",     labelEn: "Logging",         keys: ["log_message_delete", "log_message_edit", "log_message_bulk_delete", "log_voice_join", "log_voice_leave", "log_voice_move", "log_member_join", "log_member_leave", "log_nickname_change", "log_role_update", "log_channel_create", "log_channel_delete"] },
  { label: "Interactions — Targeted", labelEn: "Interactions — Targeted", keys: ["interact_airkiss", "interact_angrystare", "interact_bite", "interact_brofist", "interact_cuddle", "interact_handhold", "interact_hug", "interact_kiss", "interact_lick", "interact_nom", "interact_nuzzle", "interact_pat", "interact_pinch", "interact_poke", "interact_punch", "interact_slap", "interact_smack", "interact_tickle", "interact_wave", "interact_wink", "interact_stare", "interact_peek"] },
  { label: "Interactions — Expressions", labelEn: "Interactions — Expressions", keys: ["interact_bleh", "interact_blush", "interact_celebrate", "interact_cheers", "interact_clap", "interact_confused", "interact_cool", "interact_cry", "interact_dance", "interact_drool", "interact_evillaugh", "interact_facepalm", "interact_happy", "interact_headbang", "interact_huh", "interact_laugh", "interact_love", "interact_mad", "interact_nervous", "interact_no", "interact_nosebleed", "interact_nyah", "interact_pout", "interact_roll", "interact_run", "interact_sad", "interact_scared", "interact_shout", "interact_shrug", "interact_shy", "interact_sigh", "interact_sip", "interact_sleep", "interact_slowclap", "interact_smile", "interact_smug", "interact_sneeze", "interact_sorry", "interact_stop", "interact_surprised", "interact_sweat", "interact_thumbsup", "interact_tired", "interact_woah", "interact_yawn", "interact_yay", "interact_yes"] },
  { label: "Backup & Restore", labelEn: "Backup & Restore", keys: ["backup_completed", "restore_started", "restore_completed"] },
  { label: "Server Alerts", labelEn: "Server Alerts", keys: ["alert_mass_ban", "alert_mass_kick", "alert_channel_delete", "alert_role_delete", "alert_nuke_detect"] },
  { label: "Utilities",    labelEn: "Utilities",       keys: ["sticky_message", "afk_set", "afk_return", "afk_mention", "help_menu", "help_category", "help_command", "reminder_fire"] },
  { label: "AI Chat", labelEn: "AI Chat", keys: ["ai_response", "ai_image"] },
  { label: "Auto Role", labelEn: "Auto Role", keys: ["autorole_assign"] },
  { label: "Forms", labelEn: "Forms", keys: ["form_submitted", "form_approved", "form_rejected"] },
  { label: "Polls", labelEn: "Polls", keys: ["poll_created", "poll_ended"] },
  { label: "Social Feeds", labelEn: "Social Feeds", keys: ["social_feed_post"] },
  { label: "Staff Management", labelEn: "Staff Management", keys: ["staff_clockin", "staff_clockout", "staff_commission_paid"] },
  { label: "Support Queue", labelEn: "Support Queue", keys: ["ticket_opened", "ticket_claimed", "ticket_resolved", "ticket_closed", "ticket_sla_breach"] },
];

// ─── Variables reference ─────────────────────────────────────────────────────

export const VARIABLES: { token: string; desc: string; descEn: string }[] = [
  { token: "{user}",              desc: "Username",                    descEn: "Username" },
  { token: "{user.mention}",      desc: "@mention of the user",               descEn: "@mention of the user" },
  { token: "{user.id}",           desc: "Discord ID",                        descEn: "Discord user ID" },
  { token: "{order.id}",          desc: "Order ID (#12345)",              descEn: "Order ID (#12345)" },
  { token: "{order.total}",       desc: "Order total amount",               descEn: "Order total amount" },
  { token: "{order.status}",      desc: "Order status",              descEn: "Order status" },
  { token: "{order.note}",        desc: "Order note",                 descEn: "Order note" },
  { token: "{order.created_at}",  desc: "Order creation date",                     descEn: "Order creation date" },
  { token: "{note}",              desc: "Order note",                 descEn: "Order note" },
  { token: "{product.name}",      desc: "Product name",                     descEn: "Product name" },
  { token: "{product.description}", desc: "Product description",                 descEn: "Product description" },
  { token: "{package.name}",      desc: "Package name (san_pham_detail)", descEn: "Package name (san_pham_detail)" },
  { token: "{package.price}",     desc: "Package price (san_pham_detail)", descEn: "Package price (san_pham_detail)" },
  { token: "{package.description}", desc: "Package description (san_pham_detail)", descEn: "Package description (san_pham_detail)" },
  { token: "{product.price}",     desc: "Product price",                     descEn: "Product price" },
  { token: "{product.stock}",     desc: "Product stock quantity",                 descEn: "Product stock quantity" },
  { token: "{product.image_url}", desc: "Product image URL",                     descEn: "Product image URL" },
  { token: "{qr_url}",            desc: "Payment QR image URL",            descEn: "Payment QR image URL" },
  { token: "{transfer_content}",  desc: "Bank transfer content",            descEn: "Bank transfer content" },
  { token: "{bank_name}",         desc: "Bank name (manual payment)",   descEn: "Bank name (manual payment)" },
  { token: "{account_holder}",    desc: "Account holder (manual payment)",   descEn: "Account holder (manual payment)" },
  { token: "{account_number}",    desc: "Account number (manual payment)",    descEn: "Account number (manual payment)" },
  { token: "{instructions}",      desc: "Payment instructions (manual)",    descEn: "Payment instructions (manual)" },
  { token: "{coupon.code}",       desc: "Coupon code",                        descEn: "Coupon code" },
  { token: "{coupon.discount}",   desc: "Discount value",                 descEn: "Discount value" },
  { token: "{coupon.type}",       desc: "Discount type (% or amount)",   descEn: "Discount type (% or amount)" },
  { token: "{coupon.expires_at}", desc: "Coupon expiry date",               descEn: "Coupon expiry date" },
  { token: "{package}",           desc: "Package content (custom order)",    descEn: "Package content (custom order)" },
  { token: "{date}",              desc: "Current date and time",                descEn: "Current date and time" },
  { token: "{server}",            desc: "Server name",                       descEn: "Server name" },
  { token: "{member_count}",      desc: "Member count",                    descEn: "Member count" },
  { token: "{prize}",             desc: "Giveaway prize",           descEn: "Giveaway prize" },
  { token: "{ends_at}",           desc: "Giveaway end time",    descEn: "Giveaway end time" },
  { token: "{host}",              desc: "Giveaway host",         descEn: "Giveaway host" },
  { token: "{winners_count}",     desc: "Number of winners",        descEn: "Number of winners" },
  { token: "{winners}",           desc: "Winner names", descEn: "Winner names" },
  { token: "{reason}",            desc: "Reason (warn/ban/kick)",        descEn: "Reason (warn/ban/kick)" },
  { token: "{warn_count}",        desc: "Total warning count",                 descEn: "Total warning count" },
  { token: "{moderator}",         desc: "Moderator who performed the action",            descEn: "Moderator who performed the action" },
  { token: "{stars}",             desc: "Star rating (feedback)",                descEn: "Star rating (feedback)" },
  { token: "{content}",           desc: "Feedback content",                descEn: "Feedback content" },
  { token: "{channel.name}",      desc: "Discord channel name",                 descEn: "Discord channel name" },
  { token: "{panel.channel}",     desc: "Channel where panel was sent",              descEn: "Channel where panel was sent" },
  { token: "{button.count}",      desc: "Number of active temp voice buttons",       descEn: "Number of active temp voice buttons" },
  { token: "{buttons}",           desc: "List of active temp voice buttons", descEn: "List of active temp voice buttons" },
  { token: "{channel.mention}",   desc: "Discord channel mention",             descEn: "Discord channel mention" },
  { token: "{channel.id}",        desc: "Discord channel ID",                  descEn: "Discord channel ID" },
  { token: "{target}",            desc: "Target user name",                descEn: "Target user name" },
  { token: "{target.mention}",    desc: "Target user @mention",            descEn: "Target user @mention" },
  { token: "{target.id}",         desc: "Target user ID",                 descEn: "Target user ID" },
  { token: "{action}",            desc: "Action performed",         descEn: "Action performed" },
  { token: "{details}",           desc: "Action details",               descEn: "Action details" },
  { token: "{duration}",          desc: "Timeout / AFK duration",          descEn: "Timeout / AFK duration" },
  { token: "{mod}",               desc: "Moderator name",                descEn: "Moderator name" },
  { token: "{invite_code}",       desc: "Invite code",                        descEn: "Invite code" },
  { token: "{inviter}",           desc: "Person who sent the invite",                        descEn: "Person who sent the invite" },
  { token: "{invite.count}",      desc: "Total invite count",                descEn: "Total invite count" },
  { token: "{top1}",              desc: "Invite leaderboard #1",                    descEn: "Invite leaderboard #1" },
  { token: "{top2}",              desc: "Invite leaderboard #2",                    descEn: "Invite leaderboard #2" },
  { token: "{top3}",              desc: "Invite leaderboard #3",                    descEn: "Invite leaderboard #3" },
  { token: "{sticky.title}",      desc: "Sticky message title",                   descEn: "Sticky message title" },
  { token: "{sticky.content}",    desc: "Sticky message content",                  descEn: "Sticky message content" },
  { token: "{channel}",           desc: "Channel mention (log)",               descEn: "Channel mention (log)" },
  { token: "{before}",            desc: "Content before (edit/nick)",       descEn: "Content before (edit/nick)" },
  { token: "{after}",             desc: "Content after (edit/nick)",         descEn: "Content after (edit/nick)" },
  { token: "{message.url}",       desc: "Message link",                    descEn: "Message link" },
  { token: "{count}",             desc: "Count (bulk delete)",           descEn: "Count (bulk delete)" },
  { token: "{from}",              desc: "Previous voice channel",                    descEn: "Previous voice channel" },
  { token: "{to}",                desc: "New voice channel",                   descEn: "New voice channel" },
  { token: "{account_age}",       desc: "Account creation age",          descEn: "Account creation age" },
  { token: "{roles}",             desc: "Role list",                   descEn: "Role list" },
  { token: "{changes}",           desc: "Role changes",                    descEn: "Role changes" },
  { token: "{type}",              desc: "Channel type",                        descEn: "Channel type" },
  { token: "{time_label}",        desc: "Leaderboard period (Today, 7 days...)", descEn: "Leaderboard period (Today, 7 days...)" },
  { token: "{leaderboard_lines}", desc: "Leaderboard lines (top list)",     descEn: "Leaderboard lines (top list)" },
  { token: "{milestone.name}",    desc: "Milestone name",                    descEn: "Milestone name" },
  { token: "{milestone.threshold}", desc: "Milestone threshold amount",      descEn: "Milestone threshold amount" },
  { token: "{role.mention}",      desc: "Granted role mention",              descEn: "Granted role mention" },
  { token: "{user.total}",        desc: "User total spent",                  descEn: "User total spent" },
  { token: "{updated_at}",        desc: "Leaderboard last updated",           descEn: "Leaderboard last updated" },
  { token: "{emoji}",             desc: "Interaction emoji",                  descEn: "Interaction emoji" },
  { token: "{gif_url}",           desc: "Interaction GIF URL",            descEn: "Interaction GIF URL" },
  { token: "{role.name}",         desc: "Role name (rolepersist/temprole)",   descEn: "Role name (rolepersist/temprole)" },
  { token: "{expires_at}",        desc: "Expiry time (temprole)",     descEn: "Expiry time (temprole)" },
  { token: "{case_number}",       desc: "Moderation case number",                  descEn: "Moderation case number" },
  { token: "{note_id}",           desc: "Moderation note ID",                   descEn: "Moderation note ID" },
  { token: "{email}",             desc: "Verification email",                   descEn: "Verification email" },
  { token: "{ip}",                desc: "Verification IP address",             descEn: "Verification IP address" },
  { token: "{risk_score}",        desc: "Verification risk score",            descEn: "Verification risk score" },
  { token: "{user.tag}",          desc: "Tag Discord (user#0001)",          descEn: "Discord tag (user#0001)" },
  { token: "{backup_type}",       desc: "Backup type (full/config/discord)", descEn: "Backup type (full/config/discord)" },
  { token: "{channel_count}",     desc: "Channel count in backup",             descEn: "Channel count in backup" },
  { token: "{role_count}",        desc: "Role count in backup",              descEn: "Role count in backup" },
  { token: "{total_members}",     desc: "Total members to pull",          descEn: "Total members to pull" },
  { token: "{pulled}",            desc: "Members pulled successfully",     descEn: "Members pulled successfully" },
  { token: "{failed}",            desc: "Members pull failed",       descEn: "Members pull failed" },
  { token: "{total}",             desc: "Total",                        descEn: "Total" },
  // AI Chat
  { token: "{ai.response}",      desc: "Câu trả lời từ AI",            descEn: "AI response text" },
  { token: "{ai.prompt}",        desc: "Câu hỏi/prompt gửi cho AI",    descEn: "Prompt sent to AI" },
  { token: "{ai.provider}",      desc: "Provider AI (gemini/groq...)",  descEn: "AI provider name" },
  { token: "{ai.model}",         desc: "Model AI đang dùng",           descEn: "AI model name" },
  // Auto Role
  { token: "{role.name}",         desc: "Role name",                    descEn: "Role name" },
  // Forms
  { token: "{form.title}",        desc: "Form template title",          descEn: "Form template title" },
  { token: "{form.id}",           desc: "Form ID",                      descEn: "Form ID" },
  // Reminders
  { token: "{reminder.message}",  desc: "Reminder message",             descEn: "Reminder message" },
  // Polls
  { token: "{poll.question}",     desc: "Poll question",                descEn: "Poll question" },
  { token: "{poll.options}",      desc: "Poll options",                 descEn: "Poll options" },
  { token: "{poll.results}",      desc: "Poll results",                 descEn: "Poll results" },
  { token: "{poll.total_votes}",  desc: "Total votes",                  descEn: "Total votes" },
  { token: "{poll.end_time}",     desc: "Poll end time",                descEn: "Poll end time" },
  // Social Feeds
  { token: "{feed.title}",        desc: "Feed item title",              descEn: "Feed item title" },
  { token: "{feed.url}",          desc: "Feed item URL",                descEn: "Feed item URL" },
  { token: "{feed.platform}",     desc: "Feed platform",                descEn: "Feed platform" },
  { token: "{feed.author}",       desc: "Feed author",                  descEn: "Feed author" },
  // AFK
  { token: "{afk.reason}",        desc: "AFK reason",                   descEn: "AFK reason" },
  { token: "{afk.duration}",      desc: "AFK duration",                 descEn: "AFK duration" },
  { token: "{afk.user}",          desc: "AFK user",                     descEn: "AFK user" },
  { token: "{afk.since}",         desc: "AFK since",                    descEn: "AFK since" },
  // Staff Management
  { token: "{staff.name}",         desc: "Staff member name",            descEn: "Staff member name" },
  { token: "{staff.role_title}",   desc: "Staff role title",             descEn: "Staff role title" },
  { token: "{shift.clock_in}",     desc: "Shift clock-in time",          descEn: "Shift clock-in time" },
  { token: "{shift.duration}",     desc: "Shift duration (minutes)",     descEn: "Shift duration (minutes)" },
  { token: "{commission.amount}",  desc: "Commission amount",            descEn: "Commission amount" },
  { token: "{commission.order_count}", desc: "Number of orders in payout", descEn: "Number of orders in payout" },
  // Queue / Support Tickets
  { token: "{ticket.number}",      desc: "Ticket number",                descEn: "Ticket number" },
  { token: "{ticket.subject}",     desc: "Ticket subject",               descEn: "Ticket subject" },
  { token: "{ticket.priority}",    desc: "Ticket priority",              descEn: "Ticket priority" },
  { token: "{ticket.category}",    desc: "Ticket category",              descEn: "Ticket category" },
  { token: "{ticket.created_at}",  desc: "Ticket creation time",         descEn: "Ticket creation time" },
  { token: "{ticket.rating}",      desc: "User rating (1-5)",            descEn: "User rating (1-5)" },
];
