import type { EmbedTemplate } from "./embedTypes";

export const DEFAULTS: Record<string, Omit<EmbedTemplate, "id" | "event_type" | "name">> = {
  don_hang_moi: {
    title: "Đơn hàng mới",
    description: "Vui lòng thanh toán để hoàn tất đơn hàng.\nHết hạn sau 15 phút.",
    color: "#F0B232",
    author: "",
    author_icon_url: "",
    footer: "Đang chờ thanh toán...",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "ID Đơn", value: "#{order.id}", inline: true },
      { name: "Khách hàng", value: "{user.mention}", inline: true },
      { name: "Sản phẩm", value: "{product.name}", inline: false },
      { name: "Số tiền", value: "{order.total} VNĐ", inline: true },
    ],
    enabled: true,
  },
  don_hang_het_han: {
    title: "Đơn hàng đã hết hạn",
    description: "Đơn hàng #{order.id} của bạn đã hết hạn do chưa thanh toán sau 15 phút.",
    color: "#ED4245",
    author: "",
    author_icon_url: "",
    footer: "Tạo đơn mới để tiếp tục mua hàng.",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Sản phẩm", value: "{product.name}", inline: true },
    ],
    enabled: true,
  },
  ghi_chu_don_hang: {
    title: "📝 Ghi chú đơn hàng",
    description: "Đơn hàng #{order.id} của {user.mention} vừa được cập nhật ghi chú.",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "Infinity Mall",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "📦 Sản phẩm", value: "{product.name}", inline: true },
      { name: "📝 Ghi chú", value: "{note}", inline: false },
    ],
    enabled: true,
  },
  bang_gia: {
    title: "🛒 Bảng Giá Sản Phẩm",
    description: "Chọn sản phẩm từ menu bên dưới để xem chi tiết và giá các gói.",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "Bấm vào tên sản phẩm bên dưới để xem chi tiết",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  san_pham_detail: {
    title: "📦 {product.name}",
    description: "{product.description}",
    color: "#57F287",
    author: "",
    author_icon_url: "",
    footer: "Liên hệ admin để đặt hàng",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "🔹 {package.name}", value: "💰 **{package.price}đ**\n{package.description}", inline: false },
    ],
    enabled: true,
  },
  feedback: {
    title: "Feedback mới",
    description: "{user} đã gửi đánh giá cho {product.name}",
    color: "#FEE75C",
    author: "",
    author_icon_url: "",
    footer: "Feedback system",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Xếp hạng", value: "{stars}", inline: true },
      { name: "Nội dung", value: "{content}", inline: false },
    ],
    enabled: true,
  },
  giveaway: {
    title: "GIVEAWAY",
    description: "{prize}\n\nNhấn nút bên dưới để tham gia!\nKết thúc: {ends_at}",
    color: "#FF73FA",
    author: "Tổ chức bởi {host}",
    author_icon_url: "",
    footer: "Kết thúc lúc {ends_at}",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Số người thắng", value: "{winners_count}", inline: true },
    ],
    enabled: true,
  },
  ket_qua_giveaway: {
    title: "Kết quả Giveaway",
    description: "Giveaway đã kết thúc!\nPhần thưởng: {prize}",
    color: "#FF73FA",
    author: "",
    author_icon_url: "",
    footer: "Chúc mừng người chiến thắng!",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Người thắng", value: "{winners}", inline: false },
    ],
    enabled: true,
  },
  dm_welcome: {
    title: "👋 Chào mừng {user.name}!",
    description: "Chào mừng {user.mention} đến với **{server.name}**!\nHãy đọc kênh {rules_channel} và tận hưởng!",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "{server.name}",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  reaction_role_panel: {
    title: "🎭 Reaction Role",
    description: "Chọn role bạn muốn bằng cách react bên dưới!",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "React để nhận role • Bỏ react để gỡ role",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  starboard_post: {
    title: "⭐ Starboard",
    description: "{user.mention} nhận ⭐ **{star_count}** sao trong {channel}",
    color: "#FEE75C",
    author: "",
    author_icon_url: "",
    footer: "Starboard",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Nội dung", value: "{content}", inline: false },
    ],
    enabled: true,
  },
  canh_bao: {
    title: "Cảnh báo",
    description: "{user.mention} đã nhận cảnh báo.",
    color: "#FEE75C",
    author: "",
    author_icon_url: "",
    footer: "Hãy tuân thủ nội quy server",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Lý do", value: "{reason}", inline: false },
      { name: "Tổng cảnh báo", value: "{warn_count}", inline: true },
    ],
    enabled: true,
  },
  ticket_mo: {
    title: "🎫 Ticket #{ticket_id} đã được tạo",
    description: "Xin chào {user.mention}!\nTicket của bạn đã được tạo.\nVui lòng mô tả vấn đề để được hỗ trợ.",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "Hỗ trợ sẽ đến sớm!",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Ticket ID", value: "#{ticket_id}", inline: true },
    ],
    enabled: true,
  },
  ticket_dong: {
    title: "🔒 Ticket đã đóng",
    description: "Ticket #{ticket_id} của {user.mention} đã được đóng.",
    color: "#ED4245",
    author: "",
    author_icon_url: "",
    footer: "",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Lý do", value: "{close_reason}", inline: false },
    ],
    enabled: true,
  },
  ticket_nhan: {
    title: "✋ Ticket đã được nhận",
    description: "{staff.mention} đã nhận ticket #{ticket_id}.",
    color: "#57F287",
    author: "",
    author_icon_url: "",
    footer: "Chúng tôi sẽ hỗ trợ bạn sớm nhất!",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  kick: {
    title: "👢 Đã kick khỏi server",
    description: "{user.mention} đã bị kick khỏi server.",
    color: "#ED4245",
    author: "",
    author_icon_url: "",
    footer: "",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Lý do", value: "{reason}", inline: false },
      { name: "Mod", value: "{mod}", inline: true },
    ],
    enabled: true,
  },
  ban: {
    title: "🔨 Đã bị cấm vĩnh viễn",
    description: "{user.mention} đã bị ban khỏi server.",
    color: "#ED4245",
    author: "",
    author_icon_url: "",
    footer: "",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Lý do", value: "{reason}", inline: false },
      { name: "Mod", value: "{mod}", inline: true },
    ],
    enabled: true,
  },
  qr_thanh_toan: {
    title: "💳 Thanh toán đơn hàng #{order.id}",
    description: "Quét mã QR bên dưới để thanh toán.\nĐơn hàng sẽ hết hạn sau **15 phút**.",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "Quét QR bằng app ngân hàng",
    thumbnail_url: "",
    image_url: "{qr_url}",
    fields: [
      { name: "Số tiền", value: "{order.total} VNĐ", inline: true },
      { name: "Nội dung CK", value: "{transfer_content}", inline: true },
    ],
    enabled: true,
  },
  bxh_chi_tieu: {
    title: "🏆 BXH Chi tiêu — {time_label}",
    description: "{leaderboard_lines}",
    color: "#F0B232",
    author: "",
    author_icon_url: "",
    footer: "Cập nhật: {updated_at}",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  bxh_don_hang: {
    title: "🏆 BXH Đơn hàng — {time_label}",
    description: "{leaderboard_lines}",
    color: "#F0B232",
    author: "",
    author_icon_url: "",
    footer: "Cập nhật: {updated_at}",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  unban: {
    title: "🔓 Unban thành viên",
    description: "{user.mention} đã được unban.",
    color: "#57F287",
    author: "",
    author_icon_url: "",
    footer: "",
    thumbnail_url: "",
    image_url: "",
    fields: [
      { name: "Người thực hiện", value: "{moderator}", inline: true },
    ],
    enabled: true,
  },
  ticket_unclaim: {
    title: "↩️ Bỏ nhận Ticket",
    description: "{staff.mention} đã bỏ nhận ticket này.",
    color: "#95A5A6",
    author: "",
    author_icon_url: "",
    footer: "Ticket #{ticket.id}",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  ticket_panel: {
    title: "🎫 Hỗ trợ",
    description: "Chọn loại hỗ trợ bên dưới để tạo ticket.",
    color: "#5865F2",
    author: "",
    author_icon_url: "",
    footer: "",
    thumbnail_url: "",
    image_url: "",
    fields: [],
    enabled: true,
  },
  log_message_delete: {
    title: "🗑️ Tin nhắn bị xóa",
    description: "Tin nhắn của {user.mention} trong {channel} đã bị xóa.",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [{ name: "Nội dung", value: "{content}", inline: false }],
    enabled: true,
  },
  log_message_edit: {
    title: "✏️ Tin nhắn được sửa",
    description: "{user.mention} đã sửa tin nhắn trong {channel}.",
    color: "#FEE75C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Trước", value: "{before}", inline: false },
      { name: "Sau", value: "{after}", inline: false },
    ],
    enabled: true,
  },
  log_message_bulk_delete: {
    title: "🗑️ Xóa hàng loạt",
    description: "**{count}** tin nhắn đã bị xóa trong {channel}.",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  log_voice_join: {
    title: "🔊 Vào voice",
    description: "{user.mention} đã vào {channel}.",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  log_voice_leave: {
    title: "🔇 Rời voice",
    description: "{user.mention} đã rời {channel}.",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  log_voice_move: {
    title: "🔀 Chuyển voice",
    description: "{user.mention} đã chuyển từ {from} sang {to}.",
    color: "#FEE75C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  log_member_join: {
    title: "📥 Thành viên mới",
    description: "{user.mention} đã tham gia server.",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Tạo tài khoản", value: "{account_age}", inline: true },
      { name: "Thành viên thứ", value: "{member_count}", inline: true },
    ],
    enabled: true,
  },
  log_member_leave: {
    title: "📤 Thành viên rời",
    description: "{user.mention} đã rời server.",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Roles", value: "{roles}", inline: false },
      { name: "Còn lại", value: "{member_count} thành viên", inline: true },
    ],
    enabled: true,
  },
  log_nickname_change: {
    title: "📝 Đổi nickname",
    description: "{user.mention} đã đổi nickname.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Trước", value: "{before}", inline: true },
      { name: "Sau", value: "{after}", inline: true },
    ],
    enabled: true,
  },
  log_role_update: {
    title: "🎭 Thay đổi role",
    description: "Role của {user.mention} đã được thay đổi.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [{ name: "Thay đổi", value: "{changes}", inline: false }],
    enabled: true,
  },
  log_channel_create: {
    title: "📺 Kênh mới",
    description: "Kênh {channel} ({type}) đã được tạo.",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  log_channel_delete: {
    title: "📺 Kênh bị xóa",
    description: "Kênh **{channel.name}** ({type}) đã bị xóa.",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  // ── AutoMod ──
  automod_warn: {
    title: "⚠️ AutoMod — Cảnh báo",
    description: "{user.mention} đã bị cảnh báo bởi AutoMod.\n**Lý do:** {reason}",
    color: "#FEE75C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [{ name: "Kênh", value: "{channel}", inline: true }],
    enabled: true,
  },
  automod_mute: {
    title: "🔇 AutoMod — Mute",
    description: "{user.mention} đã bị mute bởi AutoMod.\n**Lý do:** {reason}",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [{ name: "Thời gian", value: "{duration}", inline: true }],
    enabled: true,
  },
  automod_kick: {
    title: "👢 AutoMod — Kick",
    description: "{user.mention} đã bị kick bởi AutoMod.\n**Lý do:** {reason}",
    color: "#ED4245",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  automod_delete: {
    title: "🗑️ AutoMod — Xóa tin nhắn",
    description: "Tin nhắn của {user.mention} đã bị xóa bởi AutoMod.\n**Lý do:** {reason}",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [{ name: "Nội dung", value: "{content}", inline: false }],
    enabled: true,
  },
  // ── AFK ──
  afk_set: {
    title: "💤 AFK",
    description: "{user.mention} đã đặt AFK: **{reason}**",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  afk_return: {
    title: "👋 Đã trở lại",
    description: "{user.mention} đã trở lại! (AFK {duration})",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  tempvoice_create: {
    title: "🔊 Voice tạm đã tạo",
    description: "{user.mention} đã tạo kênh voice **{channel.name}**.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "Dùng nút bên dưới để quản lý phòng", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Kênh", value: "{channel.mention}", inline: true },
      { name: "Chủ phòng", value: "{user.mention}", inline: true },
    ],
    enabled: true,
  },
  tempvoice_panel: {
    title: "🎙️ Điều khiển phòng voice",
    description: "Panel quản lý phòng voice tạm cho **{server}**.\n\nVào phòng voice của bạn rồi dùng các nút bên dưới để khóa, đổi tên, giới hạn, cấp quyền hoặc chuyển chủ phòng.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "Temp Voice Control Panel", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Kênh gửi", value: "{panel.channel}", inline: true },
      { name: "Nút bật", value: "{button.count}", inline: true },
    ],
    enabled: true,
  },
  tempvoice_action: {
    title: "🎙️ Temp Voice Action",
    description: "{user.mention} đã **{action}** trong {channel.mention}.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "Temp Voice Logs", thumbnail_url: "", image_url: "",
    fields: [
      { name: "Mục tiêu", value: "{target.mention}", inline: true },
      { name: "Chi tiết", value: "{details}", inline: true },
    ],
    enabled: true,
  },
  level_up: {
    title: "🎉 Lên Level {level}!",
    description: "Chúc mừng {user.mention} đã lên **Level {level}**!",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "Tiếp tục chat để lên level nhé!", thumbnail_url: "", image_url: "",
    fields: [
      { name: "XP hiện tại", value: "{current_xp}", inline: true },
      { name: "XP tiếp theo", value: "{next_level_xp}", inline: true },
    ],
    enabled: true,
  },
  level_reward: {
    title: "🎁 Level Reward",
    description: "{user.mention} đã nhận reward **{reward.role}** ở Level {level}.",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  leaderboard: {
    title: "🏆 Bảng xếp hạng XP",
    description: "{leaderboard_lines}",
    color: "#F0B232",
    author: "", author_icon_url: "", footer: "Cập nhật: {updated_at}", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  help_menu: {
    title: "📋 Trợ giúp — {bot_name}",
    description: "Xin chào {user.mention}!\nChọn **danh mục** bên dưới để xem danh sách lệnh.",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "{bot_name} • Chọn danh mục để tiếp tục", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  help_category: {
    title: "{category_emoji} {category_name}",
    description: "Danh sách lệnh trong **{category_name}**:\n{commands_list}",
    color: "#5865F2",
    author: "", author_icon_url: "", footer: "{bot_name} • Chọn lệnh để xem chi tiết", thumbnail_url: "", image_url: "",
    fields: [],
    enabled: true,
  },
  help_command: {
    title: "{command_emoji} `/{command_name}`",
    description: "{command_desc}",
    color: "#57F287",
    author: "", author_icon_url: "", footer: "{bot_name}", thumbnail_url: "", image_url: "",
    fields: [{ name: "📌 Cách dùng", value: "{command_usage}", inline: false }],
    enabled: true,
  },
  // ── Tương tác — Có mục tiêu ──
  interact_airkiss: {
    title: "😘 Airkiss!",
    description: "{user.mention} gửi nụ hôn gió cho {target.mention}",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_angrystare: {
    title: "😠 Angry Stare!",
    description: "{user.mention} nhìn giận dữ {target.mention}",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_bite: {
    title: "😬 Bite!",
    description: "{user.mention} cắn {target.mention}",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_brofist: {
    title: "🤜 Brofist!",
    description: "{user.mention} đấm tay với {target.mention}",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_cuddle: {
    title: "🤗 Cuddle!",
    description: "{user.mention} ôm ấp {target.mention}",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_handhold: {
    title: "🤝 Handhold!",
    description: "{user.mention} nắm tay {target.mention}",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_hug: {
    title: "🫂 Hug!",
    description: "{user.mention} ôm {target.mention}",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_kiss: {
    title: "💋 Kiss!",
    description: "{user.mention} hôn {target.mention}",
    color: "#E91E63",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_lick: {
    title: "👅 Lick!",
    description: "{user.mention} liếm {target.mention}",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_nom: {
    title: "😋 Nom!",
    description: "{user.mention} ăn {target.mention}",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_nuzzle: {
    title: "🥰 Nuzzle!",
    description: "{user.mention} cọ mũi với {target.mention}",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_pat: {
    title: "🤚 Pat!",
    description: "{user.mention} xoa đầu {target.mention}",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_pinch: {
    title: "🤏 Pinch!",
    description: "{user.mention} véo {target.mention}",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_poke: {
    title: "👉 Poke!",
    description: "{user.mention} chọc {target.mention}",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_punch: {
    title: "👊 Punch!",
    description: "{user.mention} đấm {target.mention}",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_slap: {
    title: "🫲 Slap!",
    description: "{user.mention} tát {target.mention}",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_smack: {
    title: "💥 Smack!",
    description: "{user.mention} đánh {target.mention}",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_tickle: {
    title: "🤭 Tickle!",
    description: "{user.mention} cù {target.mention}",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_wave: {
    title: "👋 Wave!",
    description: "{user.mention} vẫy tay với {target.mention}",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_wink: {
    title: "😉 Wink!",
    description: "{user.mention} nháy mắt với {target.mention}",
    color: "#9B59B6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_stare: {
    title: "👀 Stare!",
    description: "{user.mention} nhìn chằm chằm {target.mention}",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_peek: {
    title: "🫣 Peek!",
    description: "{user.mention} nhìn trộm {target.mention}",
    color: "#9B59B6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  // ── Tương tác — Biểu cảm ──
  interact_bleh: {
    title: "😝 Bleh!",
    description: "{user.mention} le lưỡi",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_blush: {
    title: "😊 Blush!",
    description: "{user.mention} đỏ mặt",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_celebrate: {
    title: "🎉 Celebrate!",
    description: "{user.mention} ăn mừng",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_cheers: {
    title: "🍻 Cheers!",
    description: "{user.mention} nâng ly",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_clap: {
    title: "👏 Clap!",
    description: "{user.mention} vỗ tay",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_confused: {
    title: "😕 Confused!",
    description: "{user.mention} bối rối",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_cool: {
    title: "😎 Cool!",
    description: "{user.mention} ngầu",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_cry: {
    title: "😢 Cry!",
    description: "{user.mention} khóc",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_dance: {
    title: "💃 Dance!",
    description: "{user.mention} nhảy",
    color: "#9B59B6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_drool: {
    title: "🤤 Drool!",
    description: "{user.mention} chảy nước miếng",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_evillaugh: {
    title: "😈 Evil Laugh!",
    description: "{user.mention} cười ác",
    color: "#8E44AD",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_facepalm: {
    title: "🤦 Facepalm!",
    description: "{user.mention} facepalm",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_happy: {
    title: "😄 Happy!",
    description: "{user.mention} vui vẻ",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_headbang: {
    title: "🤘 Headbang!",
    description: "{user.mention} headbang",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_huh: {
    title: "❓ Huh?",
    description: "{user.mention} hả?",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_laugh: {
    title: "😂 Laugh!",
    description: "{user.mention} cười",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_love: {
    title: "❤️ Love!",
    description: "{user.mention} yêu",
    color: "#E91E63",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_mad: {
    title: "😡 Mad!",
    description: "{user.mention} giận dữ",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_nervous: {
    title: "😰 Nervous!",
    description: "{user.mention} lo lắng",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_no: {
    title: "🙅 No!",
    description: "{user.mention} lắc đầu",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_nosebleed: {
    title: "🫠 Nosebleed!",
    description: "{user.mention} chảy máu mũi",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_nyah: {
    title: "😜 Nyah~",
    description: "{user.mention} nyah~",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_pout: {
    title: "😤 Pout!",
    description: "{user.mention} phụng phịu",
    color: "#E67E22",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_roll: {
    title: "🙄 Roll!",
    description: "{user.mention} lăn",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_run: {
    title: "🏃 Run!",
    description: "{user.mention} chạy",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sad: {
    title: "😞 Sad!",
    description: "{user.mention} buồn",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_scared: {
    title: "😱 Scared!",
    description: "{user.mention} sợ hãi",
    color: "#8E44AD",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_shout: {
    title: "📢 Shout!",
    description: "{user.mention} hét",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_shrug: {
    title: "🤷 Shrug!",
    description: "{user.mention} nhún vai",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_shy: {
    title: "🙈 Shy!",
    description: "{user.mention} ngại ngùng",
    color: "#FF69B4",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sigh: {
    title: "😮‍💨 Sigh!",
    description: "{user.mention} thở dài",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sip: {
    title: "🍵 Sip!",
    description: "{user.mention} nhâm nhi",
    color: "#2ECC71",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sleep: {
    title: "😴 Sleep!",
    description: "{user.mention} ngủ",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_slowclap: {
    title: "👏 Slow Clap!",
    description: "{user.mention} vỗ tay chậm",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_smile: {
    title: "😊 Smile!",
    description: "{user.mention} cười",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_smug: {
    title: "😏 Smug!",
    description: "{user.mention} tự mãn",
    color: "#9B59B6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sneeze: {
    title: "🤧 Sneeze!",
    description: "{user.mention} hắt xì",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sorry: {
    title: "🙏 Sorry!",
    description: "{user.mention} xin lỗi",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_stop: {
    title: "🛑 Stop!",
    description: "{user.mention} dừng lại",
    color: "#E74C3C",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_surprised: {
    title: "😲 Surprised!",
    description: "{user.mention} ngạc nhiên",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_sweat: {
    title: "😓 Sweat!",
    description: "{user.mention} toát mồ hôi",
    color: "#3498DB",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_thumbsup: {
    title: "👍 Thumbs Up!",
    description: "{user.mention} thích",
    color: "#2ECC71",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_tired: {
    title: "😩 Tired!",
    description: "{user.mention} mệt",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_woah: {
    title: "😮 Woah!",
    description: "{user.mention} woah",
    color: "#9B59B6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_yawn: {
    title: "🥱 Yawn!",
    description: "{user.mention} ngáp",
    color: "#95A5A6",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_yay: {
    title: "🥳 Yay!",
    description: "{user.mention} yay!",
    color: "#F1C40F",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
  interact_yes: {
    title: "✅ Yes!",
    description: "{user.mention} gật đầu",
    color: "#2ECC71",
    author: "", author_icon_url: "", footer: "", thumbnail_url: "",
    image_url: "{gif_url}",
    fields: [],
    enabled: true,
  },
};

