// AUTO-GENERATED by scripts/generate-otaku-reactions.js - do not edit by hand.
// Edit src/bot/commands/otaku-reactions/definitions.js and re-run the generator instead.
const { createOtakuReactionCommand } = require('../../utils/otakuReactionFactory');
const definitions = require('../../commands/otaku-reactions/definitions');

const definition = definitions.find((entry) => entry.name === 'nyah');

if (!definition) {
  throw new Error('otaku-reactions: missing definition for "nyah" - run scripts/generate-otaku-reactions.js again.');
}

module.exports = createOtakuReactionCommand(definition);
